const spec = {
    sections: [
        { heading: "Overview", intent: "what it is", targetWords: 200, required: true, keywordRules: { include: ["mug"], primaryInHeading: true } },
        { heading: "Care", intent: "how to keep it", targetWords: 150, required: false, keywordRules: { include: [], primaryInHeading: false } },
    ],
    tone: "warm and precise",
    length: { min: 600, max: 1200 },
    keywordRules: { primaryInTitle: true, primaryInH1: true, primaryInFirstParagraph: true, maxDensity: 0.02 },
    linkRules: { upDepth: 1, downLinks: true, siblingMinWeight: 0.5, maxLinks: 8, maxPerTarget: 2, parentLinkWithinParagraphs: 2, childrenSection: true },
    metaRules: { titlePattern: "{primaryKeyword} | {siteName}", descriptionMax: 155 },
    images: { featured: true, inline: 1, source: "wpmedia" },
    modelProfiles: [{ role: "writer", provider: "openai", model: "gpt-5" }],
    recipe: [
        { name: "resolve_context", enabled: true },
        { name: "generate_body", enabled: true },
        { name: "publish", enabled: false },
    ],
};

export const confirmableArgs: Readonly<Record<string, Record<string, unknown>>> = {
    sites_create: { name: "Clay and Kiln", baseUrl: "https://clayandkiln.com", username: "editor", password: "***", allowInsecure: false },
    sites_update: { id: "s1", name: "Clay & Kiln", password: "***", status: "paused", defaultTemplateId: "t1" },
    sites_delete: { id: "s1" },
    graph_create_entity: {
        name: "Travel Mugs",
        kind: "product",
        intent: "commercial",
        primaryKeyword: "travel mug",
        secondaryKeywords: ["insulated mug", "mug with lid"],
        anchors: [{ text: "travel mugs", source: "user", weight: 1 }],
    },
    graph_update_entity: { id: "e1", name: "Ceramic Mugs", primaryKeyword: "ceramic mug" },
    graph_delete_entity: { id: "e1" },
    graph_set_anchors: { entityId: "e1", anchors: [{ text: "ceramic mugs", source: "user", weight: 1 }, { text: "stoneware mugs", source: "model", weight: 0.6 }] },
    graph_add_edge: { fromEntityId: "e2", toEntityId: "e1", kind: "parent", weight: 0.9, reason: "Travel mugs are a kind of mug." },
    graph_approve_edge: { id: "g1" },
    graph_reject_edge: { id: "g1" },
    graph_delete_edge: { id: "g1" },
    graph_recompute_scores: {},
    graph_propose_from_pages: {},
    graph_propose_related: { entityId: "e1" },
    pages_create: { path: "/mugs/travel/", title: "Travel Mugs", h1: "Travel mugs", wpType: "page", status: "planned", entityId: "e2", templateId: "t1", metaTitle: "", metaDescription: "", canonical: "" },
    pages_update: { id: "p1", title: "Travel mugs that keep coffee hot", status: "exists" },
    pages_delete: { id: "p1" },
    pages_map_to_entity: { pageId: "p1", entityId: "e2" },
    pages_unmap: { pageId: "p1" },
    pages_set_canonical: { entityId: "e2", pageId: "p1" },
    pages_replace_links: { pageId: "p1", links: [{ toPageId: "p2", toUrl: "/mugs/", anchorText: "ceramic mugs" }, { toUrl: "https://example.com", anchorText: "the source" }] },
    templates_create: { scope: "site", siteId: "s1", name: "Product page", pageKind: "product", spec },
    templates_update: { id: "t1", name: "Product page v2", spec },
    templates_delete: { id: "t1" },
    templates_set_override: { templateId: "t1", scope: "page", targetId: "p1", patch: { tone: "playful", length: { min: 300, max: 500 } } },
    templates_delete_override: { id: "o1" },
    policies_create: { scope: "site", siteId: "s1", name: "Strict", rules: { upDepth: 2, downLinks: true, siblingMinWeight: 0.7, maxLinks: 6, maxPerTarget: 1, parentLinkWithinParagraphs: 1, childrenSection: false }, forbidExternal: true, forbidSelf: true, anchorStrategy: "rotate" },
    policies_update: { id: "l1", name: "Looser", forbidExternal: false },
    policies_delete: { id: "l1" },
    runs_start: { pageIds: ["p1", "p2", "p3"], templateId: "t1", steps: ["generate_body", "publish"], publishMode: "publish", kind: "generate", maxUsd: 12.5, maxTokens: 400000 },
    runs_pause: { runId: "r1", reason: "budget check" },
    runs_resume: { runId: "r1" },
    runs_cancel: { runId: "r1" },
    runs_retry_step: { itemId: "i1" },
    sync_site: {},
    imports_apply: { path: "C:\\data\\pages.xlsx", mapping: { name: "Q3 sheet", columns: [{ field: "path", column: "URL" }, { field: "title", column: "Title" }], options: { keywordSeparator: ";" } }, saveMappingAs: "Q3 sheet" },
    imports_export: { path: "C:\\data\\export.xlsx" },
    imports_save_mapping: { name: "Q3 sheet", columns: [{ field: "path", column: "URL" }], options: {} },
    imports_delete_mapping: { id: "m1" },
    models_upsert: { provider: "openai", model: "gpt-5", contextTokens: 400000, maxOutputTokens: 32000, inputUsdPerM: 1.25, outputUsdPerM: 10, rpm: 500, tpm: 800000, supportsStructured: true, supportsImages: true, reasoning: true },
    models_disable: { provider: "openai", model: "gpt-4o" },
    models_set_profile: { role: "writer", provider: "openai", model: "gpt-5" },
    models_set_provider_key: { provider: "anthropic", apiKey: "***" },
    models_test_provider: { provider: "anthropic", model: "claude-sonnet-5" },
    content_judge_page: { pageId: "p1" },
    schedules_create: { name: "Nightly relink", cron: "0 3 * * *", entityId: "e1", status: "published", limit: 20, templateId: "t1", steps: ["relink_neighbors"], publishMode: "draft", maxUsd: 5, maxTokens: 0, enabled: true },
    schedules_update: { id: "c1", intervalMinutes: 90, enabled: false },
    schedules_delete: { id: "c1" },
    schedules_enable: { id: "c1" },
    schedules_disable: { id: "c1" },
    schedules_run_now: { id: "c1" },
};
