// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;
