// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateArticle(arg1:dto.CreateArticleManualRequest):Promise<dto.BaseResponse>;

export function CreateSchedule(arg1:dto.CreateScheduleRequest):Promise<dto.BaseResponse>;

export function CreateSite(arg1:dto.CreateSiteRequest):Promise<dto.BaseResponse>;

export function CreateTopic(arg1:dto.CreateTopicRequest):Promise<dto.BaseResponse>;

export function DeleteSite(arg1:number):Promise<dto.BaseResponse>;

export function GetArticles(arg1:dto.PaginationRequest):Promise<dto.BaseResponse>;

export function GetDashboard():Promise<dto.BaseResponse>;

export function GetPostingJobs(arg1:dto.PaginationRequest):Promise<dto.BaseResponse>;

export function GetSchedules(arg1:dto.PaginationRequest):Promise<dto.BaseResponse>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSettings():Promise<dto.BaseResponse>;

export function GetSites(arg1:dto.PaginationRequest):Promise<dto.BaseResponse>;

export function GetTopics(arg1:dto.PaginationRequest):Promise<dto.BaseResponse>;

export function PreviewArticle(arg1:dto.PreviewArticleRequest):Promise<dto.BaseResponse>;

export function QuitApp():Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function TestSiteConnection(arg1:dto.TestSiteConnectionRequest):Promise<dto.BaseResponse>;

export function UpdateSetting(arg1:dto.SettingRequest):Promise<dto.BaseResponse>;

export function UpdateSite(arg1:dto.UpdateSiteRequest):Promise<dto.BaseResponse>;
