// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CTX() {
  return window['go']['main']['App']['CTX']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
