// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CTX():Promise<context.Context>;

export function QuitApp():Promise<void>;

export function ShowWindow():Promise<void>;
