package ai

import (
	"context"
)

// Usage contains token usage and cost metrics for an AI operation
type Usage struct {
	InputTokens  int     // Tokens used for the prompt/input
	OutputTokens int     // Tokens used for the response/output
	TotalTokens  int     // Total tokens used
	CostUSD      float64 // Estimated cost in USD
	DurationMs   int64   // Operation duration in milliseconds
}

type Client interface {
	GenerateArticle(ctx context.Context, systemPrompt, userPrompt string) (*ArticleResult, error)
	GenerateTopicVariations(ctx context.Context, topic string, amount int) ([]string, error)
	GenerateSitemapStructure(ctx context.Context, systemPrompt, userPrompt string) (*SitemapStructureResult, error)
	GenerateLinkSuggestions(ctx context.Context, request *LinkSuggestionRequest) (*LinkSuggestionResult, error)
	InsertLinks(ctx context.Context, request *InsertLinksRequest) (*InsertLinksResult, error)
	GetProviderName() string
	GetModelName() string
}

type ArticleResult struct {
	Title      string
	Excerpt    string
	Content    string
	TokensUsed int     // Deprecated: use Usage.TotalTokens
	Cost       float64 // Deprecated: use Usage.CostUSD
	Usage      Usage   // Detailed usage metrics
}

// SitemapGeneratedNode represents a node generated by AI for sitemap structure
type SitemapGeneratedNode struct {
	Title    string                 `json:"title" jsonschema_description:"Page title, should be descriptive and SEO-friendly"`
	Slug     string                 `json:"slug" jsonschema_description:"URL slug for the page, lowercase with hyphens"`
	Keywords []string               `json:"keywords,omitempty" jsonschema_description:"Keywords for the page, used for SEO"`
	Children []SitemapGeneratedNode `json:"children,omitempty" jsonschema_description:"Child pages under this page"`
}

// SitemapStructureSchema is the JSON schema for AI response
type SitemapStructureSchema struct {
	Nodes []SitemapGeneratedNode `json:"nodes" jsonschema_description:"List of top-level nodes to add to the sitemap"`
}

// SitemapStructureResult contains the result of sitemap structure generation
type SitemapStructureResult struct {
	Nodes      []SitemapGeneratedNode
	TokensUsed int     // Deprecated: use Usage.TotalTokens
	Cost       float64 // Deprecated: use Usage.CostUSD
	Usage      Usage   // Detailed usage metrics
}

type ExistingLinkInfo struct {
	TargetNodeID int64  `json:"targetNodeId"`
	Status       string `json:"status"`
	IsOutgoing   bool   `json:"isOutgoing"`
}

type LinkSuggestionNode struct {
	ID            int64              `json:"id"`
	Title         string             `json:"title"`
	Path          string             `json:"path"`
	Keywords      []string           `json:"keywords,omitempty"`
	Content       string             `json:"content,omitempty"`
	OutgoingCount int                `json:"outgoingCount"`
	IncomingCount int                `json:"incomingCount"`
	ExistingLinks []ExistingLinkInfo `json:"existingLinks,omitempty"`
}

type LinkSuggestionRequest struct {
	Nodes        []LinkSuggestionNode
	SystemPrompt string
	UserPrompt   string
	MaxIncoming  int
	MaxOutgoing  int
}

type SuggestedLink struct {
	SourceNodeID int64   `json:"sourceNodeId" jsonschema_description:"ID of the page that will contain the link"`
	TargetNodeID int64   `json:"targetNodeId" jsonschema_description:"ID of the page being linked to"`
	AnchorText   string  `json:"anchorText" jsonschema_description:"Text for the hyperlink"`
	Reason       string  `json:"reason" jsonschema_description:"Brief explanation why this link is valuable"`
	Confidence   float64 `json:"confidence" jsonschema_description:"Confidence score from 0.0 to 1.0"`
}

type LinkSuggestionSchema struct {
	Links       []SuggestedLink `json:"links" jsonschema_description:"List of suggested internal links"`
	Explanation string          `json:"explanation" jsonschema_description:"Overall strategy explanation"`
}

type LinkSuggestionResult struct {
	Links       []SuggestedLink
	Explanation string
	Usage       Usage
}

// InsertLinkTarget represents a link to be inserted into content
type InsertLinkTarget struct {
	TargetPath string  // URL path to link to
	TargetTitle string // Title of the target page (for context)
	AnchorText *string // Suggested anchor text (optional, AI can choose)
}

// InsertLinksRequest contains the data for inserting links into existing HTML content
type InsertLinksRequest struct {
	Content     string             // Existing HTML content
	PageTitle   string             // Title of the current page
	PagePath    string             // Path of the current page
	Links       []InsertLinkTarget // Links to insert
	Language    string             // Content language
}

// InsertLinksResult contains the content with links inserted
type InsertLinksResult struct {
	Content      string // Modified HTML content with links
	LinksApplied int    // Number of links successfully inserted
	Usage        Usage  // Token usage metrics
}
