package ai

import (
	"context"
)

type Client interface {
	GenerateArticle(ctx context.Context, systemPrompt, userPrompt string) (*ArticleResult, error)
	GenerateTopicVariations(ctx context.Context, topic string, amount int) ([]string, error)
	GenerateSitemapStructure(ctx context.Context, systemPrompt, userPrompt string) (*SitemapStructureResult, error)
}

type ArticleResult struct {
	Title      string
	Excerpt    string
	Content    string
	TokensUsed int
	Cost       float64
}

// SitemapGeneratedNode represents a node generated by AI for sitemap structure
type SitemapGeneratedNode struct {
	Title    string                 `json:"title" jsonschema_description:"Page title, should be descriptive and SEO-friendly"`
	Slug     string                 `json:"slug" jsonschema_description:"URL slug for the page, lowercase with hyphens"`
	Keywords []string               `json:"keywords,omitempty" jsonschema_description:"Keywords for the page, used for SEO"`
	Children []SitemapGeneratedNode `json:"children,omitempty" jsonschema_description:"Child pages under this page"`
}

// SitemapStructureSchema is the JSON schema for AI response
type SitemapStructureSchema struct {
	Nodes []SitemapGeneratedNode `json:"nodes" jsonschema_description:"List of top-level nodes to add to the sitemap"`
}

// SitemapStructureResult contains the result of sitemap structure generation
type SitemapStructureResult struct {
	Nodes      []SitemapGeneratedNode
	TokensUsed int
	Cost       float64
}
