package ai

import (
	"context"
)

// Usage contains token usage and cost metrics for an AI operation
type Usage struct {
	InputTokens  int     // Tokens used for the prompt/input
	OutputTokens int     // Tokens used for the response/output
	TotalTokens  int     // Total tokens used
	CostUSD      float64 // Estimated cost in USD
	DurationMs   int64   // Operation duration in milliseconds
}

type Client interface {
	GenerateArticle(ctx context.Context, systemPrompt, userPrompt string) (*ArticleResult, error)
	GenerateTopicVariations(ctx context.Context, topic string, amount int) ([]string, error)
	GenerateSitemapStructure(ctx context.Context, systemPrompt, userPrompt string) (*SitemapStructureResult, error)
	// GetProviderName returns the provider name (e.g., "openai", "anthropic")
	GetProviderName() string
	// GetModelName returns the model name (e.g., "gpt-4", "claude-3-opus")
	GetModelName() string
}

type ArticleResult struct {
	Title      string
	Excerpt    string
	Content    string
	TokensUsed int     // Deprecated: use Usage.TotalTokens
	Cost       float64 // Deprecated: use Usage.CostUSD
	Usage      Usage   // Detailed usage metrics
}

// SitemapGeneratedNode represents a node generated by AI for sitemap structure
type SitemapGeneratedNode struct {
	Title    string                 `json:"title" jsonschema_description:"Page title, should be descriptive and SEO-friendly"`
	Slug     string                 `json:"slug" jsonschema_description:"URL slug for the page, lowercase with hyphens"`
	Keywords []string               `json:"keywords,omitempty" jsonschema_description:"Keywords for the page, used for SEO"`
	Children []SitemapGeneratedNode `json:"children,omitempty" jsonschema_description:"Child pages under this page"`
}

// SitemapStructureSchema is the JSON schema for AI response
type SitemapStructureSchema struct {
	Nodes []SitemapGeneratedNode `json:"nodes" jsonschema_description:"List of top-level nodes to add to the sitemap"`
}

// SitemapStructureResult contains the result of sitemap structure generation
type SitemapStructureResult struct {
	Nodes      []SitemapGeneratedNode
	TokensUsed int     // Deprecated: use Usage.TotalTokens
	Cost       float64 // Deprecated: use Usage.CostUSD
	Usage      Usage   // Detailed usage metrics
}
