// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetSummary(arg1:number,arg2:string,arg3:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_AIUsageSummary_>;

export function GetUsageByOperation(arg1:number,arg2:string,arg3:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_AIUsageByOperation_>;

export function GetUsageByPeriod(arg1:number,arg2:string,arg3:string,arg4:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_AIUsageByPeriod_>;

export function GetUsageByProvider(arg1:number,arg2:string,arg3:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_AIUsageByProvider_>;

export function GetUsageBySite(arg1:string,arg2:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_AIUsageBySite_>;

export function GetUsageLogs(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_AIUsageLogsResult_>;
