// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSummary(arg1, arg2, arg3) {
  return window['go']['handlers']['AIUsageHandler']['GetSummary'](arg1, arg2, arg3);
}

export function GetUsageByOperation(arg1, arg2, arg3) {
  return window['go']['handlers']['AIUsageHandler']['GetUsageByOperation'](arg1, arg2, arg3);
}

export function GetUsageByPeriod(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['AIUsageHandler']['GetUsageByPeriod'](arg1, arg2, arg3, arg4);
}

export function GetUsageByProvider(arg1, arg2, arg3) {
  return window['go']['handlers']['AIUsageHandler']['GetUsageByProvider'](arg1, arg2, arg3);
}

export function GetUsageBySite(arg1, arg2) {
  return window['go']['handlers']['AIUsageHandler']['GetUsageBySite'](arg1, arg2);
}

export function GetUsageLogs(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['AIUsageHandler']['GetUsageLogs'](arg1, arg2, arg3, arg4, arg5);
}
