// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function QuitApp():Promise<dto.Response_string_>;

export function SetContext(arg1:context.Context):Promise<void>;
