// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateArticle(arg1:dto.Article):Promise<dto.Response_string_>;

export function CreateDraft(arg1:number,arg2:string,arg3:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Article_>;

export function DeleteArticle(arg1:number):Promise<dto.Response_string_>;

export function DeleteFromWordPress(arg1:number):Promise<dto.Response_string_>;

export function GetArticle(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Article_>;

export function ImportAllFromSite(arg1:number):Promise<dto.Response_int_>;

export function ImportFromWordPress(arg1:number,arg2:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Article_>;

export function ListArticles(arg1:number,arg2:number,arg3:number):Promise<dto.PaginatedResponse_github_com_davidmovas_postulator_internal_dto_Article_>;

export function PublishDraft(arg1:number):Promise<dto.Response_string_>;

export function PublishToWordPress(arg1:dto.Article):Promise<dto.Response_string_>;

export function SyncFromWordPress(arg1:number):Promise<dto.Response_string_>;

export function UpdateArticle(arg1:dto.Article):Promise<dto.Response_string_>;

export function UpdateInWordPress(arg1:dto.Article):Promise<dto.Response_string_>;
