// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateArticle(arg1) {
  return window['go']['handlers']['ArticlesHandler']['CreateArticle'](arg1);
}

export function CreateDraft(arg1, arg2, arg3) {
  return window['go']['handlers']['ArticlesHandler']['CreateDraft'](arg1, arg2, arg3);
}

export function DeleteArticle(arg1) {
  return window['go']['handlers']['ArticlesHandler']['DeleteArticle'](arg1);
}

export function DeleteFromWordPress(arg1) {
  return window['go']['handlers']['ArticlesHandler']['DeleteFromWordPress'](arg1);
}

export function GetArticle(arg1) {
  return window['go']['handlers']['ArticlesHandler']['GetArticle'](arg1);
}

export function ImportAllFromSite(arg1) {
  return window['go']['handlers']['ArticlesHandler']['ImportAllFromSite'](arg1);
}

export function ImportFromWordPress(arg1, arg2) {
  return window['go']['handlers']['ArticlesHandler']['ImportFromWordPress'](arg1, arg2);
}

export function ListArticles(arg1, arg2, arg3) {
  return window['go']['handlers']['ArticlesHandler']['ListArticles'](arg1, arg2, arg3);
}

export function PublishDraft(arg1) {
  return window['go']['handlers']['ArticlesHandler']['PublishDraft'](arg1);
}

export function PublishToWordPress(arg1) {
  return window['go']['handlers']['ArticlesHandler']['PublishToWordPress'](arg1);
}

export function SyncFromWordPress(arg1) {
  return window['go']['handlers']['ArticlesHandler']['SyncFromWordPress'](arg1);
}

export function UpdateArticle(arg1) {
  return window['go']['handlers']['ArticlesHandler']['UpdateArticle'](arg1);
}

export function UpdateInWordPress(arg1) {
  return window['go']['handlers']['ArticlesHandler']['UpdateInWordPress'](arg1);
}
