// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateCategory(arg1:dto.Category):Promise<dto.Response_string_>;

export function CreateInWordPress(arg1:dto.Category):Promise<dto.Response_string_>;

export function DeleteCategory(arg1:number):Promise<dto.Response_string_>;

export function DeleteInWordPress(arg1:number):Promise<dto.Response_string_>;

export function GetCategory(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Category_>;

export function GetSiteStatistics(arg1:number,arg2:string,arg3:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Statistics_>;

export function GetStatistics(arg1:number,arg2:string,arg3:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Statistics_>;

export function ListSiteCategories(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Category_>;

export function SyncFromWordPress(arg1:number):Promise<dto.Response_string_>;

export function UpdateCategory(arg1:dto.Category):Promise<dto.Response_string_>;

export function UpdateInWordPress(arg1:dto.Category):Promise<dto.Response_string_>;
