// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['handlers']['CategoriesHandler']['CreateCategory'](arg1);
}

export function CreateInWordPress(arg1) {
  return window['go']['handlers']['CategoriesHandler']['CreateInWordPress'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['handlers']['CategoriesHandler']['DeleteCategory'](arg1);
}

export function DeleteInWordPress(arg1) {
  return window['go']['handlers']['CategoriesHandler']['DeleteInWordPress'](arg1);
}

export function GetCategory(arg1) {
  return window['go']['handlers']['CategoriesHandler']['GetCategory'](arg1);
}

export function GetSiteStatistics(arg1, arg2, arg3) {
  return window['go']['handlers']['CategoriesHandler']['GetSiteStatistics'](arg1, arg2, arg3);
}

export function GetStatistics(arg1, arg2, arg3) {
  return window['go']['handlers']['CategoriesHandler']['GetStatistics'](arg1, arg2, arg3);
}

export function ListSiteCategories(arg1) {
  return window['go']['handlers']['CategoriesHandler']['ListSiteCategories'](arg1);
}

export function SyncFromWordPress(arg1) {
  return window['go']['handlers']['CategoriesHandler']['SyncFromWordPress'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['handlers']['CategoriesHandler']['UpdateCategory'](arg1);
}

export function UpdateInWordPress(arg1) {
  return window['go']['handlers']['CategoriesHandler']['UpdateInWordPress'](arg1);
}
