// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function OpenDirectoryDialog(arg1:string):Promise<dto.Response_string_>;

export function OpenFileDialog(arg1:string,arg2:Array<dto.FileFilter>):Promise<dto.Response_string_>;

export function OpenMultipleFilesDialog(arg1:string,arg2:Array<dto.FileFilter>):Promise<dto.Response___string_>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<dto.FileFilter>):Promise<dto.Response_string_>;

export function SetContext(arg1:context.Context):Promise<void>;
