// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog(arg1) {
  return window['go']['handlers']['DialogsHandler']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['handlers']['DialogsHandler']['OpenFileDialog'](arg1, arg2);
}

export function OpenMultipleFilesDialog(arg1, arg2) {
  return window['go']['handlers']['DialogsHandler']['OpenMultipleFilesDialog'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['handlers']['DialogsHandler']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['handlers']['DialogsHandler']['SetContext'](arg1);
}
