// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuto() {
  return window['go']['handlers']['HealthCheckHandler']['CheckAuto']();
}

export function CheckSite(arg1) {
  return window['go']['handlers']['HealthCheckHandler']['CheckSite'](arg1);
}

export function GetHistory(arg1, arg2) {
  return window['go']['handlers']['HealthCheckHandler']['GetHistory'](arg1, arg2);
}

export function GetHistoryByPeriod(arg1, arg2, arg3) {
  return window['go']['handlers']['HealthCheckHandler']['GetHistoryByPeriod'](arg1, arg2, arg3);
}
