// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CheckAll():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_CheckAllResult_>;

export function CheckAuto():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_AutoCheckResult_>;

export function CheckSite(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_HealthCheckHistory_>;

export function GetHistory(arg1:number,arg2:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_HealthCheckHistory_>;

export function GetHistoryByPeriod(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<dto.PaginatedResponse_github_com_davidmovas_postulator_internal_dto_HealthCheckHistory_>;
