// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportAndAssignToSite(arg1, arg2) {
  return window['go']['handlers']['ImporterHandler']['ImportAndAssignToSite'](arg1, arg2);
}

export function ImportTopics(arg1) {
  return window['go']['handlers']['ImporterHandler']['ImportTopics'](arg1);
}
