// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ImportAndAssignToSite(arg1:string,arg2:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ImportResult_>;

export function ImportTopics(arg1:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ImportResult_>;
