// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateJob(arg1:dto.Job):Promise<dto.Response_string_>;

export function DeleteJob(arg1:number):Promise<dto.Response_string_>;

export function ExecuteManually(arg1:number):Promise<dto.Response_string_>;

export function GetJob(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Job_>;

export function ListJobs():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Job_>;

export function PauseJob(arg1:number):Promise<dto.Response_string_>;

export function ResumeJob(arg1:number):Promise<dto.Response_string_>;

export function UpdateJob(arg1:dto.Job):Promise<dto.Response_string_>;
