// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['handlers']['JobsHandler']['CreateJob'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['handlers']['JobsHandler']['DeleteJob'](arg1);
}

export function ExecuteManually(arg1) {
  return window['go']['handlers']['JobsHandler']['ExecuteManually'](arg1);
}

export function GetJob(arg1) {
  return window['go']['handlers']['JobsHandler']['GetJob'](arg1);
}

export function ListJobs() {
  return window['go']['handlers']['JobsHandler']['ListJobs']();
}

export function PauseJob(arg1) {
  return window['go']['handlers']['JobsHandler']['PauseJob'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['handlers']['JobsHandler']['ResumeJob'](arg1);
}

export function UpdateJob(arg1) {
  return window['go']['handlers']['JobsHandler']['UpdateJob'](arg1);
}
