// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLink(arg1) {
  return window['go']['handlers']['LinkingHandler']['AddLink'](arg1);
}

export function ApplyLinks(arg1) {
  return window['go']['handlers']['LinkingHandler']['ApplyLinks'](arg1);
}

export function ApproveLink(arg1) {
  return window['go']['handlers']['LinkingHandler']['ApproveLink'](arg1);
}

export function CancelApply(arg1) {
  return window['go']['handlers']['LinkingHandler']['CancelApply'](arg1);
}

export function CancelSuggest(arg1) {
  return window['go']['handlers']['LinkingHandler']['CancelSuggest'](arg1);
}

export function CreatePlan(arg1) {
  return window['go']['handlers']['LinkingHandler']['CreatePlan'](arg1);
}

export function DeletePlan(arg1) {
  return window['go']['handlers']['LinkingHandler']['DeletePlan'](arg1);
}

export function GetActivePlan(arg1) {
  return window['go']['handlers']['LinkingHandler']['GetActivePlan'](arg1);
}

export function GetLinkGraph(arg1) {
  return window['go']['handlers']['LinkingHandler']['GetLinkGraph'](arg1);
}

export function GetLinks(arg1) {
  return window['go']['handlers']['LinkingHandler']['GetLinks'](arg1);
}

export function GetLinksByNode(arg1, arg2) {
  return window['go']['handlers']['LinkingHandler']['GetLinksByNode'](arg1, arg2);
}

export function GetOrCreateActivePlan(arg1, arg2) {
  return window['go']['handlers']['LinkingHandler']['GetOrCreateActivePlan'](arg1, arg2);
}

export function GetPlan(arg1) {
  return window['go']['handlers']['LinkingHandler']['GetPlan'](arg1);
}

export function GetPlanBySitemap(arg1) {
  return window['go']['handlers']['LinkingHandler']['GetPlanBySitemap'](arg1);
}

export function ListPlans(arg1) {
  return window['go']['handlers']['LinkingHandler']['ListPlans'](arg1);
}

export function RejectLink(arg1) {
  return window['go']['handlers']['LinkingHandler']['RejectLink'](arg1);
}

export function RemoveLink(arg1) {
  return window['go']['handlers']['LinkingHandler']['RemoveLink'](arg1);
}

export function SuggestLinks(arg1) {
  return window['go']['handlers']['LinkingHandler']['SuggestLinks'](arg1);
}

export function UpdateLink(arg1) {
  return window['go']['handlers']['LinkingHandler']['UpdateLink'](arg1);
}
