// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddLink(arg1:dto.AddLinkRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_PlannedLink_>;

export function ApplyLinks(arg1:dto.ApplyLinksRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ApplyLinksResult_>;

export function ApproveLink(arg1:number):Promise<dto.Response_bool_>;

export function CancelApply(arg1:number):Promise<dto.Response_bool_>;

export function CancelSuggest(arg1:number):Promise<dto.Response_bool_>;

export function CreatePlan(arg1:dto.CreateLinkPlanRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function DeletePlan(arg1:number):Promise<dto.Response_bool_>;

export function GetActivePlan(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function GetLinkGraph(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkGraph_>;

export function GetLinks(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_PlannedLink_>;

export function GetLinksByNode(arg1:number,arg2:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_PlannedLink_>;

export function GetOrCreateActivePlan(arg1:number,arg2:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function GetPlan(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function GetPlanBySitemap(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function ListPlans(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_LinkPlan_>;

export function RejectLink(arg1:number):Promise<dto.Response_bool_>;

export function RemoveLink(arg1:number):Promise<dto.Response_bool_>;

export function SuggestLinks(arg1:dto.SuggestLinksRequest):Promise<dto.Response_bool_>;

export function UpdateLink(arg1:dto.UpdateLinkRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_PlannedLink_>;
