// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMedia(arg1, arg2) {
  return window['go']['handlers']['MediaHandler']['DeleteMedia'](arg1, arg2);
}

export function GetMedia(arg1, arg2) {
  return window['go']['handlers']['MediaHandler']['GetMedia'](arg1, arg2);
}

export function UploadMedia(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['MediaHandler']['UploadMedia'](arg1, arg2, arg3, arg4);
}

export function UploadMediaFromURL(arg1, arg2, arg3) {
  return window['go']['handlers']['MediaHandler']['UploadMediaFromURL'](arg1, arg2, arg3);
}
