// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function DeleteMedia(arg1:number,arg2:number):Promise<dto.Response_string_>;

export function GetMedia(arg1:number,arg2:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_MediaResult_>;

export function UploadMedia(arg1:number,arg2:string,arg3:string,arg4:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_MediaResult_>;

export function UploadMediaFromURL(arg1:number,arg2:string,arg3:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_MediaResult_>;
