// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreatePrompt(arg1:dto.Prompt):Promise<dto.Response_string_>;

export function DeletePrompt(arg1:number):Promise<dto.Response_string_>;

export function GetPrompt(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Prompt_>;

export function ListPrompts():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Prompt_>;

export function UpdatePrompt(arg1:dto.Prompt):Promise<dto.Response_string_>;
