// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePrompt(arg1) {
  return window['go']['handlers']['PromptsHandler']['CreatePrompt'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['handlers']['PromptsHandler']['DeletePrompt'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['handlers']['PromptsHandler']['GetPrompt'](arg1);
}

export function ListPrompts() {
  return window['go']['handlers']['PromptsHandler']['ListPrompts']();
}

export function UpdatePrompt(arg1) {
  return window['go']['handlers']['PromptsHandler']['UpdatePrompt'](arg1);
}
