// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateProvider(arg1:dto.Provider):Promise<dto.Response_string_>;

export function DeleteProvider(arg1:number):Promise<dto.Response_string_>;

export function GetAvailableModels(arg1:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Model_>;

export function GetProvider(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Provider_>;

export function ListActiveProviders():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Provider_>;

export function ListProviders():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Provider_>;

export function SetProviderStatus(arg1:number,arg2:boolean):Promise<dto.Response_string_>;

export function UpdateProvider(arg1:dto.Provider):Promise<dto.Response_string_>;

export function ValidateModel(arg1:string,arg2:string):Promise<dto.Response_string_>;
