// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProvider(arg1) {
  return window['go']['handlers']['ProvidersHandler']['CreateProvider'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['handlers']['ProvidersHandler']['DeleteProvider'](arg1);
}

export function GetAvailableModels(arg1) {
  return window['go']['handlers']['ProvidersHandler']['GetAvailableModels'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['handlers']['ProvidersHandler']['GetProvider'](arg1);
}

export function ListActiveProviders() {
  return window['go']['handlers']['ProvidersHandler']['ListActiveProviders']();
}

export function ListProviders() {
  return window['go']['handlers']['ProvidersHandler']['ListProviders']();
}

export function SetProviderStatus(arg1, arg2) {
  return window['go']['handlers']['ProvidersHandler']['SetProviderStatus'](arg1, arg2);
}

export function UpdateProvider(arg1) {
  return window['go']['handlers']['ProvidersHandler']['UpdateProvider'](arg1);
}

export function ValidateModel(arg1, arg2) {
  return window['go']['handlers']['ProvidersHandler']['ValidateModel'](arg1, arg2);
}
