// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorNode() {
  return window['go']['handlers']['ProxyHandler']['AddTorNode']();
}

export function CompareIPs() {
  return window['go']['handlers']['ProxyHandler']['CompareIPs']();
}

export function DetectTor() {
  return window['go']['handlers']['ProxyHandler']['DetectTor']();
}

export function Disable() {
  return window['go']['handlers']['ProxyHandler']['Disable']();
}

export function Enable() {
  return window['go']['handlers']['ProxyHandler']['Enable']();
}

export function GetDefaultTorNode() {
  return window['go']['handlers']['ProxyHandler']['GetDefaultTorNode']();
}

export function GetSettings() {
  return window['go']['handlers']['ProxyHandler']['GetSettings']();
}

export function GetState() {
  return window['go']['handlers']['ProxyHandler']['GetState']();
}

export function GetTorBrowserNode() {
  return window['go']['handlers']['ProxyHandler']['GetTorBrowserNode']();
}

export function TestAllNodes() {
  return window['go']['handlers']['ProxyHandler']['TestAllNodes']();
}

export function TestNode(arg1) {
  return window['go']['handlers']['ProxyHandler']['TestNode'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['handlers']['ProxyHandler']['UpdateSettings'](arg1);
}
