// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddTorNode():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxyNode_>;

export function CompareIPs():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_IPComparison_>;

export function DetectTor():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_TorDetectionResult_>;

export function Disable():Promise<dto.Response_string_>;

export function Enable():Promise<dto.Response_string_>;

export function GetDefaultTorNode():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxyNode_>;

export function GetSettings():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxySettings_>;

export function GetState():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxyState_>;

export function GetTorBrowserNode():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxyNode_>;

export function TestAllNodes():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_ProxyHealth_>;

export function TestNode(arg1:dto.ProxyNode):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ProxyHealth_>;

export function UpdateSettings(arg1:dto.ProxySettings):Promise<dto.Response_string_>;
