// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetHealthCheckSettings():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_HealthCheckSettings_>;

export function UpdateHealthCheckSettings(arg1:dto.HealthCheckSettings):Promise<dto.Response_string_>;
