// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['handlers']['SettingsHandler']['GetAppVersion']();
}

export function GetHealthCheckSettings() {
  return window['go']['handlers']['SettingsHandler']['GetHealthCheckSettings']();
}

export function UpdateHealthCheckSettings(arg1) {
  return window['go']['handlers']['SettingsHandler']['UpdateHealthCheckSettings'](arg1);
}
