// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNodeKeyword(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['AddNodeKeyword'](arg1, arg2);
}

export function CancelPageGeneration(arg1) {
  return window['go']['handlers']['SitemapsHandler']['CancelPageGeneration'](arg1);
}

export function CancelSitemapGeneration() {
  return window['go']['handlers']['SitemapsHandler']['CancelSitemapGeneration']();
}

export function ChangePublishStatus(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ChangePublishStatus'](arg1);
}

export function ClearHistory(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ClearHistory'](arg1);
}

export function CreateNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['CreateNode'](arg1);
}

export function CreateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['CreateSitemap'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DeleteNode'](arg1);
}

export function DeleteSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DeleteSitemap'](arg1);
}

export function DistributeKeywords(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DistributeKeywords'](arg1);
}

export function DuplicateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DuplicateSitemap'](arg1);
}

export function GenerateSitemapStructure(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GenerateSitemapStructure'](arg1);
}

export function GetDefaultPagePrompt() {
  return window['go']['handlers']['SitemapsHandler']['GetDefaultPagePrompt']();
}

export function GetHistoryState(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetHistoryState'](arg1);
}

export function GetNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNode'](arg1);
}

export function GetNodes(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNodes'](arg1);
}

export function GetNodesTree(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNodesTree'](arg1);
}

export function GetPageGenerationTask(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetPageGenerationTask'](arg1);
}

export function GetSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetSitemap'](arg1);
}

export function GetSitemapWithNodes(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetSitemapWithNodes'](arg1);
}

export function GetSupportedImportFormats() {
  return window['go']['handlers']['SitemapsHandler']['GetSupportedImportFormats']();
}

export function ImportNodes(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ImportNodes'](arg1);
}

export function LinkNodeToArticle(arg1) {
  return window['go']['handlers']['SitemapsHandler']['LinkNodeToArticle'](arg1);
}

export function LinkNodeToPage(arg1) {
  return window['go']['handlers']['SitemapsHandler']['LinkNodeToPage'](arg1);
}

export function ListActivePageGenerationTasks() {
  return window['go']['handlers']['SitemapsHandler']['ListActivePageGenerationTasks']();
}

export function ListSitemaps(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ListSitemaps'](arg1);
}

export function MoveNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['MoveNode'](arg1);
}

export function PausePageGeneration(arg1) {
  return window['go']['handlers']['SitemapsHandler']['PausePageGeneration'](arg1);
}

export function Redo(arg1) {
  return window['go']['handlers']['SitemapsHandler']['Redo'](arg1);
}

export function RemoveNodeKeyword(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['RemoveNodeKeyword'](arg1, arg2);
}

export function ResetNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ResetNode'](arg1);
}

export function ResumePageGeneration(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ResumePageGeneration'](arg1);
}

export function ScanIntoSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ScanIntoSitemap'](arg1);
}

export function ScanSite(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ScanSite'](arg1);
}

export function SetNodeKeywords(arg1) {
  return window['go']['handlers']['SitemapsHandler']['SetNodeKeywords'](arg1);
}

export function SetSitemapStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['SetSitemapStatus'](arg1, arg2);
}

export function StartPageGeneration(arg1) {
  return window['go']['handlers']['SitemapsHandler']['StartPageGeneration'](arg1);
}

export function SyncNodesFromWP(arg1) {
  return window['go']['handlers']['SitemapsHandler']['SyncNodesFromWP'](arg1);
}

export function Undo(arg1) {
  return window['go']['handlers']['SitemapsHandler']['Undo'](arg1);
}

export function UnlinkNodeContent(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UnlinkNodeContent'](arg1);
}

export function UpdateNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNode'](arg1);
}

export function UpdateNodeDesignStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodeDesignStatus'](arg1, arg2);
}

export function UpdateNodeGenerationStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodeGenerationStatus'](arg1, arg2);
}

export function UpdateNodePositions(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodePositions'](arg1);
}

export function UpdateNodePublishStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodePublishStatus'](arg1, arg2);
}

export function UpdateNodesToWP(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodesToWP'](arg1);
}

export function UpdateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateSitemap'](arg1);
}
