// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateSite(arg1:dto.Site):Promise<dto.Response_string_>;

export function DeleteSite(arg1:number):Promise<dto.Response_string_>;

export function GetSite(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Site_>;

export function GetSiteWithPassword(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Site_>;

export function ListSites():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Site_>;

export function UpdateSite(arg1:dto.Site):Promise<dto.Response_string_>;

export function UpdateSitePassword(arg1:number,arg2:string):Promise<dto.Response_string_>;
