// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddNodeKeyword(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function CreateNode(arg1:dto.CreateNodeRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function CreateSitemap(arg1:dto.CreateSitemapRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function DeleteNode(arg1:number):Promise<dto.Response_string_>;

export function DeleteSitemap(arg1:number):Promise<dto.Response_string_>;

export function DistributeKeywords(arg1:dto.DistributeKeywordsRequest):Promise<dto.Response_string_>;

export function DuplicateSitemap(arg1:dto.DuplicateSitemapRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function GetNode(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetNodes(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetNodesTree(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetSitemap(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function GetSitemapWithNodes(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapWithNodes_>;

export function GetSupportedImportFormats():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SupportedFormatsResponse_>;

export function ImportNodes(arg1:dto.ImportNodesRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ImportNodesResponse_>;

export function LinkNodeToArticle(arg1:dto.LinkNodeToArticleRequest):Promise<dto.Response_string_>;

export function LinkNodeToPage(arg1:dto.LinkNodeToPageRequest):Promise<dto.Response_string_>;

export function ListSitemaps(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function MoveNode(arg1:dto.MoveNodeRequest):Promise<dto.Response_string_>;

export function RemoveNodeKeyword(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function SetNodeKeywords(arg1:dto.SetNodeKeywordsRequest):Promise<dto.Response_string_>;

export function SetSitemapStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function UnlinkNodeContent(arg1:number):Promise<dto.Response_string_>;

export function UpdateNode(arg1:dto.UpdateNodeRequest):Promise<dto.Response_string_>;

export function UpdateNodeContentStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function UpdateNodePositions(arg1:dto.UpdateNodePositionsRequest):Promise<dto.Response_string_>;

export function UpdateSitemap(arg1:dto.UpdateSitemapRequest):Promise<dto.Response_string_>;
