// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAllHealth() {
  return window['go']['handlers']['SitesHandler']['CheckAllHealth']();
}

export function CheckHealth(arg1) {
  return window['go']['handlers']['SitesHandler']['CheckHealth'](arg1);
}

export function CreateSite(arg1) {
  return window['go']['handlers']['SitesHandler']['CreateSite'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['handlers']['SitesHandler']['DeleteSite'](arg1);
}

export function GetSite(arg1) {
  return window['go']['handlers']['SitesHandler']['GetSite'](arg1);
}

export function GetSiteWithPassword(arg1) {
  return window['go']['handlers']['SitesHandler']['GetSiteWithPassword'](arg1);
}

export function ListSites() {
  return window['go']['handlers']['SitesHandler']['ListSites']();
}

export function UpdateSite(arg1) {
  return window['go']['handlers']['SitesHandler']['UpdateSite'](arg1);
}

export function UpdateSitePassword(arg1, arg2) {
  return window['go']['handlers']['SitesHandler']['UpdateSitePassword'](arg1, arg2);
}
