// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddNodeKeyword(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function BatchChangePublishStatus(arg1:dto.BatchChangePublishStatusRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_BatchChangeStatusResponse_>;

export function BatchDeleteNodesWithWP(arg1:dto.BatchDeleteNodesWithWPRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_BatchDeleteNodesResponse_>;

export function CancelPageGeneration(arg1:string):Promise<dto.Response_string_>;

export function CancelSitemapGeneration():Promise<dto.Response_string_>;

export function ChangePublishStatus(arg1:dto.ChangePublishStatusRequest):Promise<dto.Response_string_>;

export function ClearHistory(arg1:number):Promise<dto.Response_string_>;

export function CreateNode(arg1:dto.CreateNodeRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function CreateSitemap(arg1:dto.CreateSitemapRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function DeleteNode(arg1:number):Promise<dto.Response_string_>;

export function DeleteNodeWithWP(arg1:dto.DeleteNodeWithWPRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_DeleteNodeResult_>;

export function DeleteSitemap(arg1:number):Promise<dto.Response_string_>;

export function DistributeKeywords(arg1:dto.DistributeKeywordsRequest):Promise<dto.Response_string_>;

export function DuplicateSitemap(arg1:dto.DuplicateSitemapRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function GenerateSitemapStructure(arg1:dto.GenerateSitemapStructureRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_GenerateSitemapStructureResponse_>;

export function GetDefaultPagePrompt():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_DefaultPromptResponse_>;

export function GetHistoryState(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_HistoryState_>;

export function GetNode(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetNodes(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetNodesTree(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SitemapNode_>;

export function GetPageGenerationTask(arg1:string):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_GenerationTaskResponse_>;

export function GetSitemap(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function GetSitemapWithNodes(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SitemapWithNodes_>;

export function GetSupportedImportFormats():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SupportedFormatsResponse_>;

export function ImportNodes(arg1:dto.ImportNodesRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ImportNodesResponse_>;

export function LinkNodeToArticle(arg1:dto.LinkNodeToArticleRequest):Promise<dto.Response_string_>;

export function LinkNodeToPage(arg1:dto.LinkNodeToPageRequest):Promise<dto.Response_string_>;

export function ListActivePageGenerationTasks():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_GenerationTaskResponse_>;

export function ListSitemaps(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Sitemap_>;

export function MoveNode(arg1:dto.MoveNodeRequest):Promise<dto.Response_string_>;

export function Redo(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_HistoryState_>;

export function RemoveNodeKeyword(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function ResetNode(arg1:number):Promise<dto.Response_string_>;

export function ScanIntoSitemap(arg1:dto.ScanIntoSitemapRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ScanSiteResponse_>;

export function ScanSite(arg1:dto.ScanSiteRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_ScanSiteResponse_>;

export function SetNodeKeywords(arg1:dto.SetNodeKeywordsRequest):Promise<dto.Response_string_>;

export function SetSitemapStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function StartPageGeneration(arg1:dto.StartPageGenerationRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_GenerationTaskResponse_>;

export function SyncNodesFromWP(arg1:dto.SyncNodesRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SyncNodesResponse_>;

export function Undo(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_HistoryState_>;

export function UnlinkNodeContent(arg1:number):Promise<dto.Response_string_>;

export function UpdateNode(arg1:dto.UpdateNodeRequest):Promise<dto.Response_string_>;

export function UpdateNodeDesignStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function UpdateNodeGenerationStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function UpdateNodePositions(arg1:dto.UpdateNodePositionsRequest):Promise<dto.Response_string_>;

export function UpdateNodePublishStatus(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function UpdateNodesToWP(arg1:dto.UpdateNodesToWPRequest):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SyncNodesResponse_>;

export function UpdateSitemap(arg1:dto.UpdateSitemapRequest):Promise<dto.Response_string_>;
