// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNodeKeyword(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['AddNodeKeyword'](arg1, arg2);
}

export function CreateNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['CreateNode'](arg1);
}

export function CreateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['CreateSitemap'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DeleteNode'](arg1);
}

export function DeleteSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DeleteSitemap'](arg1);
}

export function DistributeKeywords(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DistributeKeywords'](arg1);
}

export function DuplicateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['DuplicateSitemap'](arg1);
}

export function GetNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNode'](arg1);
}

export function GetNodes(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNodes'](arg1);
}

export function GetNodesTree(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetNodesTree'](arg1);
}

export function GetSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetSitemap'](arg1);
}

export function GetSitemapWithNodes(arg1) {
  return window['go']['handlers']['SitemapsHandler']['GetSitemapWithNodes'](arg1);
}

export function LinkNodeToArticle(arg1) {
  return window['go']['handlers']['SitemapsHandler']['LinkNodeToArticle'](arg1);
}

export function LinkNodeToPage(arg1) {
  return window['go']['handlers']['SitemapsHandler']['LinkNodeToPage'](arg1);
}

export function ListSitemaps(arg1) {
  return window['go']['handlers']['SitemapsHandler']['ListSitemaps'](arg1);
}

export function MoveNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['MoveNode'](arg1);
}

export function RemoveNodeKeyword(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['RemoveNodeKeyword'](arg1, arg2);
}

export function SetNodeKeywords(arg1) {
  return window['go']['handlers']['SitemapsHandler']['SetNodeKeywords'](arg1);
}

export function SetSitemapStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['SetSitemapStatus'](arg1, arg2);
}

export function UnlinkNodeContent(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UnlinkNodeContent'](arg1);
}

export function UpdateNode(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNode'](arg1);
}

export function UpdateNodeContentStatus(arg1, arg2) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodeContentStatus'](arg1, arg2);
}

export function UpdateNodePositions(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateNodePositions'](arg1);
}

export function UpdateSitemap(arg1) {
  return window['go']['handlers']['SitemapsHandler']['UpdateSitemap'](arg1);
}
