// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetDashboardSummary():Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_DashboardSummary_>;

export function GetGlobalStatistics(arg1:string,arg2:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SiteStats_>;

export function GetSiteStatistics(arg1:number,arg2:string,arg3:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_SiteStats_>;

export function GetTotalStatistics(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_SiteStats_>;
