// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardSummary() {
  return window['go']['handlers']['StatsHandler']['GetDashboardSummary']();
}

export function GetSiteStatistics(arg1, arg2, arg3) {
  return window['go']['handlers']['StatsHandler']['GetSiteStatistics'](arg1, arg2, arg3);
}

export function GetTotalStatistics(arg1) {
  return window['go']['handlers']['StatsHandler']['GetTotalStatistics'](arg1);
}
