// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignToSite(arg1, arg2) {
  return window['go']['handlers']['TopicsHandler']['AssignToSite'](arg1, arg2);
}

export function CreateAndAssignToSite(arg1, arg2) {
  return window['go']['handlers']['TopicsHandler']['CreateAndAssignToSite'](arg1, arg2);
}

export function CreateTopic(arg1) {
  return window['go']['handlers']['TopicsHandler']['CreateTopic'](arg1);
}

export function CreateTopics(arg1) {
  return window['go']['handlers']['TopicsHandler']['CreateTopics'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['handlers']['TopicsHandler']['DeleteTopic'](arg1);
}

export function GenerateVariations(arg1, arg2, arg3) {
  return window['go']['handlers']['TopicsHandler']['GenerateVariations'](arg1, arg2, arg3);
}

export function GetJobRemainingTopics(arg1) {
  return window['go']['handlers']['TopicsHandler']['GetJobRemainingTopics'](arg1);
}

export function GetNextTopicForJob(arg1) {
  return window['go']['handlers']['TopicsHandler']['GetNextTopicForJob'](arg1);
}

export function GetOrGenerateVariation(arg1, arg2, arg3) {
  return window['go']['handlers']['TopicsHandler']['GetOrGenerateVariation'](arg1, arg2, arg3);
}

export function GetSelectableSiteTopics(arg1, arg2) {
  return window['go']['handlers']['TopicsHandler']['GetSelectableSiteTopics'](arg1, arg2);
}

export function GetSelectableSiteTopicsForJob(arg1, arg2, arg3) {
  return window['go']['handlers']['TopicsHandler']['GetSelectableSiteTopicsForJob'](arg1, arg2, arg3);
}

export function GetSiteTopics(arg1) {
  return window['go']['handlers']['TopicsHandler']['GetSiteTopics'](arg1);
}

export function GetTopic(arg1) {
  return window['go']['handlers']['TopicsHandler']['GetTopic'](arg1);
}

export function GetUnusedSiteTopics(arg1) {
  return window['go']['handlers']['TopicsHandler']['GetUnusedSiteTopics'](arg1);
}

export function ListTopics() {
  return window['go']['handlers']['TopicsHandler']['ListTopics']();
}

export function MarkTopicUsed(arg1, arg2) {
  return window['go']['handlers']['TopicsHandler']['MarkTopicUsed'](arg1, arg2);
}

export function UnassignFromSite(arg1, arg2) {
  return window['go']['handlers']['TopicsHandler']['UnassignFromSite'](arg1, arg2);
}

export function UpdateTopic(arg1) {
  return window['go']['handlers']['TopicsHandler']['UpdateTopic'](arg1);
}
