// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AssignToSite(arg1:number,arg2:Array<number>):Promise<dto.Response_string_>;

export function CreateTopic(arg1:dto.Topic):Promise<dto.Response_string_>;

export function CreateTopics(arg1:Array<dto.Topic>):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_BatchResult_>;

export function DeleteTopic(arg1:number):Promise<dto.Response_string_>;

export function GenerateVariations(arg1:number,arg2:number,arg3:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Topic_>;

export function GetJobRemainingTopics(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_JobTopicsStatus_>;

export function GetNextTopicForJob(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Topic_>;

export function GetOrGenerateVariation(arg1:number,arg2:number,arg3:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Topic_>;

export function GetSelectableSiteTopics(arg1:number,arg2:string):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Topic_>;

export function GetSiteTopics(arg1:number):Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Topic_>;

export function GetTopic(arg1:number):Promise<dto.Response_github_com_davidmovas_postulator_internal_dto_Topic_>;

export function ListTopics():Promise<dto.Response___github_com_davidmovas_postulator_internal_dto_Topic_>;

export function MarkTopicUsed(arg1:number,arg2:number):Promise<dto.Response_string_>;

export function UnassignFromSite(arg1:number,arg2:Array<number>):Promise<dto.Response_string_>;

export function UpdateTopic(arg1:dto.Topic):Promise<dto.Response_string_>;
