export const agent = {
    title: "Agent",
    subtitle: "The agent can do everything this app can. Every write stops and asks, in plain words.",
    attach: "Attach a spreadsheet",
    send: "Send",
    cancelTurn: "Stop",
    thinking: "Working",
    confirmTitle: "Approve this action",
    approve: "Approve",
    reject: "Reject",
    untitled: "New conversation",
    assistant: "Assistant",
    composer: {
        placeholder: "Ask the agent to change something…",
        firstPlaceholder: "Ask something. Your first message starts a conversation on this site.",
        noModel: "No chat model is set. Point the chat role at a model in the settings first.",
    },
    status: {
        working: "Working",
        workingFor: (elapsed: string) => `Working · ${elapsed}`,
        awaiting: "Awaiting your confirmation",
        stopping: "Stopping",
        stopped: "Stopped",
        failed: "The turn failed",
        lost: "The answer was lost",
        retry: "Ask again",
    },
    dock: {
        label: "Dock width",
        narrow: "Narrow",
        wide: "Wide",
        resize: "Drag to resize the dock",
    },
    header: {
        rename: "Rename",
        renameTitle: "Conversation title",
        noSite: "No site",
        everywhere: "Everywhere",
        modeLabel: "Mode",
        modeConfirm: "Confirm",
        modeAutonomous: "Autonomous",
        spend: (usd: string, calls: number) => `${usd} · ${calls === 1 ? "1 model call" : `${calls} model calls`}`,
        cached: (percent: number) => `${percent}% cached`,
        spendTooltip:
            "What this conversation has cost: one row per model call, and how much of the input the provider served from its cache.",
        noSpend: "Nothing spent yet",
        modelUnset: "Chat model not set",
        tools: (count: number) => (count === 1 ? "1 tool" : `${count} tools`),
        openFull: "Open as a page",
        backToDock: "Back to the dock",
        switchConversation: "Switch conversation",
        newConversation: "New conversation",
        recent: "Recent on this site",
        more: "All conversations",
        renameAction: "Rename this conversation",
        renameBody: "An untitled conversation takes its first message as its title.",
        renameSave: "Rename",
    },
    autonomousTitle: "Autonomous. Writes happen without asking.",
    autonomousBody:
        "Every tool runs as soon as the agent calls it, deletions and imports included. Switch back to confirm mode to be asked first.",
    autonomousDialog: {
        title: "Run without asking?",
        body: "In autonomous mode the agent writes to the graph, the pages, the templates and the site as soon as it decides to. You will see what it did, not approve it first.",
        confirm: "Run without asking",
        cancel: "Keep asking me",
    },
    transcript: {
        jumpToLatest: "Jump to the latest",
        loadEarlier: "Load earlier messages",
        copyCode: "Copy",
        codeCopied: "Copied",
        plainCode: "code",
        tool: {
            running: "running",
            ok: "done",
            error: "failed",
            denied: "refused",
            cut: "shortened",
            showResult: "Show what it answered",
            hideResult: "Hide",
            duration: (ms: number) => (ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} s`),
            cutSummary: (kb: number) => `${kb} KB, shortened to fit`,
            deniedDetail: "This conversation is not allowed to use that tool. Nothing was read or written.",
            failedDetail: "The agent was told why and can try again with different arguments.",
            cutRows: (count: number, path: string) =>
                count === 1 ? `1 row dropped from ${path}` : `${count} rows dropped from ${path}`,
            cutText: (count: number) => (count === 1 ? "1 long value shortened" : `${count} long values shortened`),
            cutPreview: "Too long to shorten, so the agent was given the opening of it only.",
            cutAsk: "Ask for a narrower slice if the agent needs the rest.",
        },
    },
    states: {
        stoppedTitle: "Turn stopped",
        stoppedBody: "Nothing more was written.",
        errorTitle: "The turn failed",
        budgetTitle: "The turn used up its tool call budget",
        budgetBody: "It made every tool call one turn is allowed and still had not finished. Ask something narrower, or ask it to carry on from where it stopped.",
        lostTitle: "The answer was lost",
        lostBody: "The turn ended without writing an answer. Ask again.",
        retry: "Ask again",
        start: "Ask something to begin.",
        startBody: "Try: how many pages carry no entity, or: plan the missing pages under an entity.",
        loading: "Loading the conversation",
    },
    card: {
        kickerWrite: "Needs your approval",
        kickerDangerous: "Dangerous. Needs your approval",
        riskWrite: "Write",
        riskDangerous: "Dangerous",
        dangerousWarn: "This cannot be undone from Postulator.",
        approveKeys: ["Ctrl", "Enter"] as readonly string[],
        rejectKeys: ["Ctrl", "Shift", "Enter"] as readonly string[],
        listApproveKeys: ["A"] as readonly string[],
        listRejectKeys: ["R"] as readonly string[],
        approving: "Approving",
        rejecting: "Rejecting",
        executed: "Approved and done",
        executedWith: (summary: string) => `Approved and done: ${summary}`,
        undelivered: "Approved and done, but the agent was never told",
        approved: "Approved, running",
        rejected: "Rejected",
        settled: "Resolved",
        failed: (reason: string) => `Failed: ${reason}`,
        requested: (when: string) => `Asked ${when}`,
        unknownRef: "no longer here",
    },
    inbox: {
        title: "Inbox",
        filter: "Show",
        waiting: (count: number) =>
            count === 1 ? "1 action is waiting for your decision" : `${count} actions are waiting for your decision`,
        waitingBody: "Read-only tools run at once. Every write and every deletion waits here.",
        rejectAll: "Reject all",
        rejectAllTitle: "Reject every pending action?",
        rejectAllBody: (count: number) =>
            `${count === 1 ? "The one action" : `All ${count} actions`} shown here will be rejected. The agent learns that on its next turn.`,
        rejectAllConfirm: "Reject them",
        cancel: "Cancel",
        keys: "j / k move · a approve · r reject · Enter opens the conversation",
        tabs: {
            pending: "Waiting",
            executed: "Done",
            rejected: "Rejected",
            failed: "Failed",
        },
        openConversation: "Open the conversation",
        deletedConversation: "A conversation that was deleted",
        nothingDone: "Nothing has been approved yet.",
        nothingRejected: "Nothing has been rejected.",
        nothingFailed: "No approved action has failed.",
    },
    screen: {
        conversations: "Conversations",
        search: "Search conversations",
        noMatch: "No conversation matches.",
        groupEverywhere: "Everywhere",
        deleteTitle: "Delete this conversation?",
        deleteBody: "Its messages, its pending actions and its history go with it. A turn in flight is stopped.",
        deleteConfirm: "Delete it",
        cancel: "Cancel",
        delete: "Delete",
        newTitle: "New conversation",
        newSite: "Site",
        newEverywhere: "No site. The agent can only read the list of sites and create one.",
        newStart: "Start",
        pendingCount: (count: number) => (count === 1 ? "1 waiting" : `${count} waiting`),
        awaiting: (count: number) => (count === 1 ? "1 awaiting approval" : `${count} awaiting approval`),
    },
    tools: {
        title: "What the agent can do",
        subtitle: (count: number) => `${count} tools, each one a thing this app can do.`,
        search: "Search tools",
        noMatch: "No tool matches.",
        read: "Read",
        write: "Write",
        dangerous: "Dangerous",
        readBody: "Runs at once, changes nothing.",
        writeBody: "Asks first in confirm mode.",
        dangerousBody: "Asks first in confirm mode and reads differently, because it cannot be undone.",
    },
    families: {
        sites: "Sites",
        graph: "Graph",
        pages: "Pages",
        templates: "Templates",
        policies: "Link policies",
        runs: "Runs",
        sync: "Sync",
        reports: "Reports",
        imports: "Import",
        models: "Models",
        content: "Content",
        schedules: "Schedules",
        other: "Other",
    } as Readonly<Record<string, string>>,
    describe: {
        yes: "yes",
        no: "no",
        hidden: "kept hidden",
        more: (count: number) => `and ${count} more`,
        field: (label: string, value: string) => `${label}: ${value}`,
        sites: {
            create: (name: string) => `Register site "${name}"`,
            update: "Update site",
            delete: "Delete site",
            deleteBody: "Its pages, entities, runs, schedules and conversations go with it.",
            address: (url: string) => `Address ${url}`,
            user: (name: string) => `WordPress user ${name}`,
            password: "New application password, kept hidden",
            insecure: "Insecure TLS allowed",
            secure: "Insecure TLS refused",
            status: (status: string) => `Status ${status}`,
            renamed: (name: string) => `Renamed to "${name}"`,
            defaultTemplate: "Default template",
            defaultPolicy: "Default link policy",
        },
        graph: {
            create: (name: string) => `Create entity "${name}"`,
            createMany: (count: number) => `Create ${count} entities in one write`,
            createManyBody: "The whole list is written together, or none of it is.",
            root: (name: string) => `"${name}" · a root of the tree`,
            child: (name: string, parent: string) => `"${name}" · under "${parent}"`,
            update: "Update entity",
            delete: "Delete entity",
            deleteBody: "Its pages keep their content and lose their entity. Its edges go.",
            kind: (kind: string) => `Kind ${kind}`,
            intent: (intent: string) => `Intent ${intent}`,
            primary: (keyword: string) => `Primary keyword "${keyword}"`,
            secondary: (keywords: string) => `Also targets ${keywords}`,
            renamed: (name: string) => `Renamed to "${name}"`,
            anchorsCount: (count: number) => (count === 1 ? "1 anchor" : `${count} anchors`),
            anchor: (text: string, weight: string, source: string) => `"${text}" · ${weight} · ${source}`,
            setAnchors: "Set the anchors of",
            connect: "Connect",
            under: "under",
            with: "with",
            weight: (weight: string) => `Weight ${weight}`,
            approve: "Approve the edge",
            reject: "Reject the edge",
            deleteEdge: "Delete the edge",
            recompute: "Recompute the entity scores",
            recomputeBody: "Every score is recalculated from the approved edges. Nothing else changes.",
            proposeFromPages: "Propose entities and edges from the pages",
            proposeBody: "One model call per forty unmapped pages. Nothing is approved on its own.",
            proposeRelated: "Propose related edges",
            proposeAround: "Only pairs that involve",
        },
        pages: {
            create: (path: string) => `Plan page ${path}`,
            update: "Update page",
            delete: "Delete page",
            deleteBody: "The row leaves the map. The page on WordPress is not touched.",
            map: "Map",
            to: "to",
            unmap: "Take the entity off",
            canonical: "Make",
            canonicalOf: "the canonical page of",
            replaceLinks: "Replace the links of",
            linksCount: (count: number) => (count === 1 ? "1 link" : `${count} links`),
            link: (anchor: string) => `"${anchor}" →`,
            title: (title: string) => `Title "${title}"`,
            h1: (h1: string) => `H1 "${h1}"`,
            path: (path: string) => `Path ${path}`,
            wpType: (kind: string) => `WordPress type ${kind}`,
            status: (status: string) => `Status ${status}`,
            metaTitle: (title: string) => `Meta title "${title}"`,
            metaDescription: (text: string) => `Meta description "${text}"`,
            canonicalUrl: (url: string) => `Canonical ${url}`,
            entity: "Entity",
            template: "Template",
        },
        templates: {
            create: (name: string) => `Create template "${name}"`,
            update: "Update template",
            delete: "Delete template",
            deleteBody: "Pages that used it fall back to the site default. Its overrides go.",
            override: "Override",
            forSite: "for the site",
            forPage: "for the page",
            deleteOverride: "Remove a template override",
            pageKind: (kind: string) => `Page kind ${kind}`,
            scopeSite: "Only on the site",
            scopeGlobal: "Available on every site",
            renamed: (name: string) => `Renamed to "${name}"`,
            replaces: "Replaces the whole specification",
            unreadableSpec: "The specification could not be read.",
            nothingChanges: "Nothing in the specification changes.",
        },
        policies: {
            create: (name: string) => `Create link policy "${name}"`,
            update: "Update link policy",
            delete: "Delete link policy",
            renamed: (name: string) => `Renamed to "${name}"`,
            maxLinks: (count: number) => `At most ${count} links per page`,
            perTarget: (count: number) => `At most ${count} per target`,
            upDepth: (levels: number) => `Links up ${levels} ${levels === 1 ? "level" : "levels"}`,
            down: "Links down to the children",
            noDown: "No links down",
            siblings: (weight: string) => `Sideways from weight ${weight}`,
            childrenSection: "A children section at the end",
            noChildrenSection: "No children section",
            forbidExternal: "External links forbidden",
            allowExternal: "External links allowed",
            forbidSelf: "Self links forbidden",
            allowSelf: "Self links allowed",
            anchors: (strategy: string) => `Anchors: ${strategy}`,
        },
        runs: {
            start: (kind: string, count: number) => `Start a ${kind} run over ${count === 1 ? "1 page" : `${count} pages`}`,
            pages: "Pages",
            template: "Template",
            templateDefault: "Template: each page's own",
            steps: (steps: string) => `Steps ${steps}`,
            stepsDefault: "Steps: the template recipe",
            publishes: "Publishes the pages live on WordPress",
            drafts: "Writes drafts, nothing goes live",
            budget: (usd: string) => `Budget ${usd}`,
            tokens: (count: string) => `${count} tokens at most`,
            noBudget: "No budget cap",
            pause: "Pause the run",
            resume: "Resume the run",
            cancel: "Cancel the run",
            cancelBody: "Items already published stay published.",
            reason: (reason: string) => `Reason: ${reason}`,
            retry: "Retry the current step of the item",
        },
        sync: {
            site: "Pull the site's live content into the page map",
            body: "Rows are updated from WordPress. Nothing on WordPress changes.",
        },
        imports: {
            apply: (file: string) => `Import ${file} into the site`,
            applyBody: "One transaction: every row lands or none does.",
            file: (path: string) => `File ${path}`,
            columns: (count: number) => (count === 1 ? "1 column mapped" : `${count} columns mapped`),
            column: (field: string, column: string) => `${field} ← ${column}`,
            option: (name: string, value: string) => `${name} "${value}"`,
            saveAs: (name: string) => `Saved as the mapping "${name}"`,
            export: (path: string) => `Export the site to ${path}`,
            saveMapping: (name: string) => `Save the column mapping "${name}"`,
            deleteMapping: "Delete the column mapping",
        },
        models: {
            upsert: (ref: string) => `Add or update the model ${ref}`,
            disable: (ref: string) => `Disable the model ${ref}`,
            setProfile: (role: string, ref: string) => `Point the ${role} role at ${ref}`,
            setKey: (provider: string) => `Store the ${provider} API key`,
            setKeyBody: "The key is stored encrypted and never shown again.",
            test: (ref: string) => `Test ${ref}`,
            testBody: "One small paid call to the provider.",
            context: (count: string) => `Context ${count} tokens`,
            output: (count: string) => `Output up to ${count} tokens`,
            prices: (input: string, output: string) => `${input} in, ${output} out per million`,
            limits: (rpm: number, tpm: string) => `${rpm} requests and ${tpm} tokens per minute`,
            structured: "Structured output",
            images: "Images",
            reasoning: "Reasoning",
        },
        content: {
            judge: "Judge the live page",
            body: "One priced model call over what WordPress serves right now.",
        },
        schedules: {
            create: (name: string) => `Create schedule "${name}"`,
            update: "Update schedule",
            delete: "Delete schedule",
            enable: "Enable the schedule",
            disable: "Disable the schedule",
            runNow: "Run the schedule now",
            renamed: (name: string) => `Renamed to "${name}"`,
            cron: (cron: string) => `On the cron ${cron}`,
            every: (minutes: number) => `Every ${minutes} ${minutes === 1 ? "minute" : "minutes"}`,
            entity: "Only the pages of",
            status: (status: string) => `Only ${status} pages`,
            limit: (count: number) => `At most ${count} pages a run`,
            template: "Template",
            enabled: "Enabled at once",
            paused: "Created paused",
        },
    },
    askAbout: "Ask the agent about this",
    ask: {
        entity: (name: string, id: string) => `Entity "${name}" (id ${id}). `,
        page: (path: string, id: string) => `Page ${path} (id ${id}). `,
        template: (name: string, id: string) => `Template "${name}" (id ${id}). `,
        newTemplate: "Create a template for this site. ",
        runItem: (path: string, runId: string, itemId: string) =>
            `Run item for ${path} (run ${runId}, item ${itemId}). `,
    },
};
