export const app = {
    name: "Postulator",
    tagline: "An entity graph turned into graph-compliant WordPress pages.",
    loading: "Loading",
    retry: "Try again",
    dismiss: "Dismiss",
    refreshed: "Refreshed",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    loadMore: "Load more",
    loadingMore: "Loading more",
    openExternal: "Open in Tor Browser",
    torMissing: "Tor Browser is not installed, so the link was not opened.",
    torSetUp: "Set up Tor Browser",
    more: "More",
};

export const lock = {
    title: "Postulator is locked",
    prompt: "Enter the master password to unlock the workspace.",
    password: "Master password",
    unlock: "Unlock",
    unlocking: "Unlocking. Deriving the key takes a few seconds.",
    wrong: "That password did not unlock the workspace.",
    firstRun: "No master password is set. Everything is protected by Windows DPAPI alone.",
    setPassword: "Set a master password",
    unrecoverable: "The master key cannot be read. Restore a backup to recover this workspace.",
    lockNow: "Lock now",
};

export const nav = {
    overview: "Overview",
    graph: "Graph",
    pages: "Pages",
    links: "Linking",
    runs: "Runs",
    templates: "Templates",
    schedules: "Schedules",
    importExport: "Import",
    reports: "Reports",
    agent: "Agent",
    settings: "Settings",
    sites: "Sites",
    inbox: "Inbox",
};

export const shell = {
    sections: "Sections",
    siteSwitcher: "Switch site",
    chooseSite: "Choose a site",
    allSites: "All sites",
    minimise: "Minimise",
    maximise: "Maximise",
    restore: "Restore",
    close: "Close",
    noSiteSelected: "No site selected",
    agentDock: "Agent",
    collapseDock: "Collapse the agent dock",
    expandDock: "Expand the agent dock",
    activeRuns: "Active runs",
    spend: "Spent",
    pluginInstalled: "Plugin installed",
    pluginMissing: "Plugin missing",
    locked: "Locked",
    unlocked: "Unlocked",
    unprotected: "No master password",
};

export const empty = {
    sites: "No sites yet. Add the WordPress site you want Postulator to work on.",
    pages: "No pages in the map. Import a sitemap or let the agent plan the first pages.",
    pageTree: "The page tree is empty. Sync the site or import a sheet to fill it.",
    pageLinks: "This page links nowhere yet. A generate run writes its internal links.",
    entities: "The entity graph is empty. Import a sheet or ask the agent to propose entities from the pages.",
    proposedEdges: "No proposed edges are waiting. Run a proposal to suggest relationships.",
    edges: "No edges between these entities yet. Add one or approve a proposal.",
    runs: "No runs yet. Start a generate run from the page map.",
    runItems: "This run has no items. It was started against an empty selection.",
    runEvents: "No steps have been recorded yet for this run.",
    artifacts: "This item produced no artifacts yet.",
    templates: "No templates yet. Create one or let the agent draft it for you.",
    policies: "No link policies yet. The built-in defaults apply until you add one.",
    overrides: "No overrides. Every page uses the template as written.",
    schedules: "No schedules yet. Add one to generate or sync on a timer.",
    mappings: "No saved column mappings for this site yet.",
    previewPages: "The sheet produced no pages. Check the column mapping.",
    previewEntities: "The sheet produced no entities. Check the column mapping.",
    previewEdges: "The sheet produced no relationships between entities.",
    importFindings: "Nothing to report. Every row read cleanly.",
    cannibalization: "No two pages compete for the same entity.",
    orphans: "No orphan pages. Every page is reachable from the graph.",
    topEntities: "No entity has a score yet. Recompute the scores after approving edges.",
    conversations: "No conversations yet. Ask the agent for something and it starts one.",
    messages: "Nothing said yet in this conversation.",
    pendingActions: "Nothing is waiting for approval.",
    tools: "The agent has no tools registered.",
    models: "No models in the catalog. Add one or restore the seeded catalog.",
    profiles: "No role profiles set. Every role falls back to the global model.",
    providerKeys: "No provider key is stored yet.",
    readiness: "Everything on the checklist is done. Start a generate run.",
    usage: "Nothing has been spent yet.",
    depth: "No pages are deep enough to chart.",
};

export const toasts = {
    saved: "Saved",
    deleted: "Deleted",
    started: "Started",
    copied: "Copied",
};
