export const graph = {
    title: "Graph",
    kinds: { hub: "Hub", product: "Product", topic: "Topic", category: "Category", custom: "Custom" },
    views: { label: "View", map: "Map", outline: "Outline" },
    label: "Entity graph",
    loading: "Loading the graph",
    total: (total: number) => (total === 1 ? "1 entity" : `${total} entities`),
    search: {
        label: "Find an entity",
        placeholder: "Find an entity",
        noHits: "Nothing matches",
        field: { name: "name", primaryKeyword: "keyword", secondaryKeyword: "secondary keyword" },
    },
    lens: {
        all: "All",
        noPage: "No page",
        proposed: "Proposed",
        orphan: "Orphans",
        ai: "From AI",
        kinds: "Kinds",
        anyKind: "Every kind",
        isolate: "Isolate",
        isolateHint: "Hide everything the lens does not match and keep the path to each match.",
        states: "Page state",
        stateShort: {
            mismatch: "Diverged",
            working: "In a run",
            published: "Live",
            exists: "Draft",
            planned: "Planned",
            archived: "Gone",
            noPage: "No page",
        },
        state: {
            mismatch: "The site does not hold what was planned",
            working: "A run is working on it now",
            published: "Live on the site",
            exists: "On the site, not published",
            planned: "Planned, never written",
            archived: "Gone from the site",
            noPage: "No page of its own",
        },
        proof: "Link proof",
        proofHint: "Colour every entity by whether its page carries the links the graph asks for.",
        proofLoading: "Auditing the links",
        hint: {
            all: "Every entity of the site.",
            noPage: "Entities without a canonical page. Nothing can link to them until they get one.",
            proposed: "Entities touched by an edge that still waits for a decision.",
            orphan: "Entities that are not hubs and have no approved parent.",
            ai: "Entities the model proposed. Review their names, keywords and anchors.",
        },
    },
    controls: {
        zoomIn: "Zoom in",
        zoomOut: "Zoom out",
        fit: "Fit the whole map (0)",
        expandAll: "Expand every subtree",
        collapseToRoots: "Collapse to the roots",
        showRelated: "Show every related link",
        hideRelated: "Show related links for the selection only",
        minimap: "Minimap",
        zoom: (percent: number) => `${percent}%`,
    },
    legend: {
        title: "Legend",
        show: "Show the legend",
        hide: "Hide the legend",
        kinds: "Kinds",
        nodes: "Nodes",
        edges: "Edges",
        badges: "Badges",
        kind: (kind: string) => kind,
        plain: "An entity with a page of its own",
        noPage: "No canonical page, so nothing can link to it",
        proposedPlacement: "Sits under a parent that still waits for a decision",
        selected: "Selected",
        neighbour: "Linked to the selection",
        collapsed: "A collapsed subtree and how many it hides",
        parent: "Parent, approved",
        parentProposed: "Parent, proposed",
        related: "Related, approved",
        relatedProposed: "Related, proposed",
        noPageBadge: "It has no page",
        extraParent: "It has a second parent",
        proposedBadge: "Edges waiting on a decision",
        order: "Children are ordered by score, strongest first.",
        states: "Page state",
        stateShort: {
            mismatch: "Diverged",
            working: "In a run",
            published: "Live",
            exists: "Draft",
            planned: "Planned",
            archived: "Gone",
            noPage: "No page",
        },
        state: {
            mismatch: "The site does not hold what was planned",
            working: "A run is working on it now",
            published: "Live on the site",
            exists: "On the site, not published",
            planned: "Planned, never written",
            archived: "Gone from the site",
            noPage: "No page of its own",
        },
        proof: "Link proof",
        proofOk: "Every link the graph asks for is in place",
        proofWarn: "An optional link is missing",
        proofDanger: "A required link is missing, or a target has no page",
        proofMuted: "Not audited: no page or no template",
    },
    card: {
        noPage: "No page yet",
        proposedPlacement: "Under a proposed parent",
        proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
        extraParent: "Has a second parent",
        orphan: "No approved parent",
    },
    actions: {
        create: "New entity",
        createKey: "New entity (N)",
        connectKey: "Connect the selected entity to another (E)",
        connectNeedsSelection: "Select an entity first",
    },
    node: {
        more: (shown: number, hidden: number) => `${shown} shown, ${hidden} more`,
        showMore: (count: number) => `Show ${count} more`,
        showAll: "Show all",
        noPage: "no page",
        proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
        parents: (count: number) => `${count} parents`,
    },
    empty: {
        title: "The graph is empty",
        body: "Nothing gets linked until entities exist and their edges are approved.",
        propose: "Propose from pages",
        add: "Add an entity",
        import: "Import a sheet",
    },
    summary: {
        title: "This site",
        hint: "Pick an entity on the map to read and edit it.",
        byKind: "By kind",
        attention: "Needs attention",
        noPage: (count: number) => (count === 1 ? "1 entity has no page" : `${count} entities have no page`),
        orphan: (count: number) => (count === 1 ? "1 orphan" : `${count} orphans`),
        proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
        multiParent: (count: number) => (count === 1 ? "1 entity with two parents" : `${count} entities with several parents`),
        clean: "Every entity has a page, a parent and no edge waiting.",
        top: "Highest scores",
    },
    inspector: {
        title: "Entity",
        close: "Close the inspector",
        kind: "Kind",
        intent: "Intent",
        primaryKeyword: "Primary keyword",
        secondaryKeywords: "Secondary keywords",
        anchors: "Anchors",
        anchorsHint: "The link texts another page may use to point here.",
        noAnchors: "No anchors. The entity name is used instead.",
        score: "Score",
        rank: (rank: number, total: number) => `rank ${rank} of ${total}`,
        source: "Source",
        page: "Canonical page",
        openPage: "Open the canonical page",
        noPage: "No canonical page",
        noPageBody: "Nothing can link to this entity until a page is canonical for it.",
        relations: "Relations",
        parents: "Parents",
        children: "Children",
        related: "Related",
        proposedParent: "proposed parent",
        showInMap: "Show in the map",
        moreChildren: (count: number) => `${count} more in the map`,
        noRelations: "No edges yet.",
        created: "Created",
        links: "Links",
        linksOpen: "Open in Links",
        linksRow: (satisfied: number, targets: number) => `${satisfied} of ${targets} in place`,
        linksMissing: (missing: number, required: number) =>
            required > 0 ? `${missing} missing, ${required} required` : `${missing} missing`,
        linksBlocked: (count: number) => `${count} blocked`,
        linksOff: "Turn on the link proof to see how its pages link.",
        linksNone: "No audited page",
    },
    form: {
        name: "Name",
        kind: "Kind",
        intent: "Intent",
        intentHint: "What a reader wants from this entity's page, in one sentence.",
        primaryKeyword: "Primary keyword",
        secondaryKeywords: "Secondary keywords",
        keywordsHint: "Enter adds one. Four is plenty.",
        remove: "Remove",
        actions: "Actions",
    save: "Save",
        discard: "Discard",
    },
    anchorsForm: {
        text: "Anchor text",
        weight: "Weight",
        add: "Add an anchor",
        remove: "Remove the anchor",
        save: "Save the anchors",
        hint: "A weight closer to 1 is preferred when a page links here.",
        duplicate: "That anchor is already listed.",
    },
    pageForm: {
        open: "Open the page",
        drift: "edited in WordPress",
        mapped: "Pages mapped to this entity",
        makeCanonical: "Make it canonical",
        none: "No page is mapped to this entity yet.",
        find: "Find an unmapped page by path",
        noMatch: "No unmapped page matches that path.",
        partial: "More unmapped pages exist. Narrow the path to find one.",
        map: "Map it and make it canonical",
        plan: "Plan a page",
    },
    create: {
        title: "New entity",
        under: (name: string) => `New entity under ${name}`,
        parent: "Parent",
        noParent: "No parent. It becomes a root.",
        anchors: "Anchors",
        anchorsHint: "Enter adds one. The name is used when this is empty.",
        submit: "Create the entity",
        cancel: "Cancel",
        created: (name: string) => `${name} created`,
        attachFailed: (name: string) => `${name} was created but could not be attached to its parent`,
    },
    connect: {
        start: "Connect",
        stop: "Stop connecting",
        picking: (name: string) => `Connecting ${name}. Pick the other entity on the map or in the outline.`,
        title: (from: string, to: string) => `Connect ${from} and ${to}`,
        close: "Close",
        parentOf: (child: string, parent: string) => `${parent} becomes the parent of ${child}`,
        related: "Related, no direction",
        weight: "Weight",
        weightHint: "How close they are, from 0 to 1. A sibling below the policy threshold is not linked.",
        submit: "Add the edge",
        cycle: "That parent edge would close a loop",
        cycleBody: "Parent edges must form a tree. Make it a related edge instead, or pick another parent.",
        makeRelated: "Make it related instead",
        self: "An entity cannot connect to itself.",
        added: "Edge added",
    },
    remove: {
        title: (name: string) => `Delete ${name}?`,
        alone:
            "The entity goes, with its anchors. No edge touches it. Every page mapped to it stays in the map and on the site; it loses its mapping, so nothing plans its links any more.",
        withEdges: (edges: number) =>
            `The entity goes, with its anchors, and so ${edges === 1 ? "does the 1 edge" : `do the ${edges} edges`} that touch it. Every page mapped to it stays in the map and on the site; it loses its mapping, so nothing plans its links any more.`,
        confirm: "Delete the entity",
        cancel: "Keep it",
        deleted: (name: string) => `${name} deleted`,
    },
    move: {
        title: (child: string, parent: string) => `Move ${child} under ${parent}?`,
        fromParent: (previous: string) => `Adds the parent edge and removes the one to ${previous}.`,
        fromRoot: "Adds the parent edge. The entity was a root.",
        keepBoth: "Keep the current parent too",
        confirm: "Move it",
        cancel: "Cancel",
        moved: (child: string, parent: string) => `${child} moved under ${parent}`,
        dropHint: "Drop on the new parent. Esc cancels.",
    },
    menu: {
        label: "Entity actions",
        addChild: "Add a child",
        connect: "Connect…",
        fold: "Fold the subtree",
        unfold: "Unfold the subtree",
        center: "Center on it",
        delete: "Delete…",
    },
    edges: {
        approve: "Approve",
        reject: "Reject",
        remove: "Remove the edge",
        reason: "Why",
    },
    ai: {
        menu: "Model",
        menuLabel: "Ask the model",
        fromPages: "Propose entities from the pages",
        fromKeywords: "Propose entities from keywords",
        related: "Propose related edges",
        relatedFor: (name: string) => `Propose related edges for ${name}`,
        recompute: "Recompute the scores",
        fromPagesTitle: "Propose entities from the pages",
        fromPagesBody: (unmapped: number, calls: number) =>
            unmapped === 0
                ? "Every page is already mapped to an entity. There is nothing to propose from."
                : `${unmapped === 1 ? "1 page has" : `${unmapped} pages have`} no entity. The model reads them in batches of 40, so this is ${calls === 1 ? "1 model call" : `about ${calls} model calls`}, one after another, and the window waits for all of them. Each batch is saved as it lands; cancelling keeps what was already proposed.`,
        relatedTitle: "Propose related edges",
        relatedBody: (total: number) =>
            `The model reads all ${total} entities in one call and suggests which pairs belong together. Every suggestion arrives as a proposed edge with a reason, for you to approve or reject.`,
        relatedForBody: (name: string) => `The model reads every entity and suggests which ones belong beside ${name}. Every suggestion arrives as a proposed edge with a reason, for you to approve or reject.`,
        scope: "Scope",
        wholeSite: "The whole site",
        onlySelection: (name: string) => `Only pairs with ${name}`,
        start: "Start",
        cancel: "Cancel",
        counting: "Counting the pages that have no entity…",
        running: "Working",
        elapsed: (seconds: number) => `${seconds}s`,
        stop: "Stop and keep what landed",
        cancelled: "Stopped. Whatever had landed is kept.",
        fromPagesDone: (entities: number, edges: number, skipped: number) =>
            `${entities} ${entities === 1 ? "entity" : "entities"} and ${edges} ${edges === 1 ? "edge" : "edges"} proposed${skipped > 0 ? `, ${skipped} skipped` : ""}`,
        relatedDone: (edges: number, skipped: number) =>
            `${edges} related ${edges === 1 ? "edge" : "edges"} proposed${skipped > 0 ? `, ${skipped} skipped` : ""}`,
        tokens: (tokens: number) => `${tokens} tokens`,
        nothingProposed: "The model proposed nothing new.",
        recomputed: (changed: number) => (changed === 0 ? "Scores are unchanged." : `${changed} ${changed === 1 ? "score" : "scores"} changed.`),
        close: "Close",
        review: "Review the proposals",
        entitiesTitle: "Propose entities",
        entitiesBody: "The model proposes an entity per page or per keyword. Nothing is written until you keep the ones you want.",
        sourcePages: "From pages",
        sourceKeywords: "From keywords",
        pickPages: "Pages",
        pickedPages: (count: number) => (count === 1 ? "1 page picked" : `${count} pages picked`),
        pickScope: "Which pages",
        pickScopes: { unmapped: "Without an entity", all: "All" },
        mapped: "This page already carries an entity.",
        root: "The root of the site takes no entity.",
        keywords: "Keywords",
        keywordsHint: "One keyword per line. Paste a list from a sheet or a research tool.",
        keywordsCount: (count: number) => (count === 1 ? "1 keyword" : `${count} keywords`),
        parentLabel: "Under",
        parentNone: "No parent",
        preview: (count: number) => (count === 0 ? "Preview" : `Preview ${count}`),
        previewing: "Asking the model",
        reviewTitle: (count: number) => (count === 1 ? "1 proposed entity" : `${count} proposed entities`),
        reviewBody: "Untick what you do not want. Edges arrive as proposals to approve afterwards.",
        columnKeep: "Keep",
        columnName: "Entity",
        columnKind: "Kind",
        columnKeyword: "Primary keyword",
        columnPlace: "Page or parent",
        existing: "already exists",
        create: (count: number) => (count === 0 ? "Create" : count === 1 ? "Create 1 entity" : `Create ${count} entities`),
        creating: "Writing",
        back: "Back",
        keepAll: "Keep all",
        keepNone: "Keep none",
        applied: (entities: number, mapped: number, edges: number, skipped: number) =>
            `${entities} ${entities === 1 ? "entity" : "entities"} created, ${mapped} ${mapped === 1 ? "page" : "pages"} mapped, ${edges} ${edges === 1 ? "edge" : "edges"} proposed${skipped > 0 ? `, ${skipped} skipped` : ""}.`,
        reviewEdges: "Review the edges",
    },
    queue: {
        open: "Review",
        title: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
        close: "Close the review",
        emptyTitle: "Nothing to review",
        columns: { from: "From", kind: "Edge", to: "To", confidence: "Confidence", reason: "Why", decision: "Decision" },
        keys: "A approve · R reject · ↑ ↓ move · Enter show",
        parent: "parent",
        related: "related",
        noReason: "No reason recorded",
        threshold: "Threshold",
        resize: "Drag to make the review taller",
        approveFrom: "Confidence ≥",
        rejectUnder: "Confidence <",
        approveAbove: (count: number) => `Approve ${count}`,
        rejectBelow: (count: number) => `Reject ${count}`,
        bulkApproveTitle: (count: number, threshold: number) =>
            `Approve ${count} ${count === 1 ? "edge" : "edges"} at or above ${threshold.toFixed(2)}?`,
        bulkRejectTitle: (count: number, threshold: number) =>
            `Reject ${count} ${count === 1 ? "edge" : "edges"} below ${threshold.toFixed(2)}?`,
        bulkBody: "Each decision is made one at a time. A rejected edge can be proposed again, and an approved one can be removed later.",
        progress: (done: number, total: number) => `${done} of ${total}`,
        confirm: "Go",
        cancel: "Cancel",
        bulkDone: (count: number, decision: "approve" | "reject") => `${count} ${decision === "approve" ? "approved" : "rejected"}`,
        bulkStopped: (done: number, total: number, message: string) => `Stopped after ${done} of ${total}: ${message}`,
    },
    score: {
        none: "—",
        notComputed: "No entity has been scored yet.",
        notComputedHint: "The ranking is worked out from the approved edges, on demand.",
        compute: "Compute the scores",
    },
    outline: {
        columns: { name: "Entity", kind: "Kind", score: "Score", page: "Page", attention: "Attention" },
        page: "page",
        noPage: "no page",
        fold: "Fold",
        unfold: "Unfold",
        children: (count: number) => `${count} below`,
    },
};
