export const imports = {
    dropped: {
        ask: (path: string) => `Import the sheet at ${path} into this site. `,
        rejected: "Only a .csv or .xlsx sheet can be dropped here.",
        hint: "Drop a .csv or .xlsx sheet",
    },
    title: "Import",
    tabs: {
        label: "Import or export",
        import: "Import",
        export: "Export",
    },
    steps: {
        label: "Import steps",
        file: "File",
        columns: "Columns",
        preview: "Preview",
        apply: "Apply",
    },
    back: "Back",
    next: "Next",
    file: {
        title: "Choose a spreadsheet",
        body: "One row per page. CSV and XLSX are both read.",
        choose: "Choose file…",
        change: "Choose another file",
        dialogTitle: "Choose a sheet to import",
        spreadsheets: "Spreadsheets",
        workbooks: "Excel workbooks",
        reading: "Reading the sheet",
        rows: (count: number) => (count === 1 ? "1 row" : `${count} rows`),
        columns: (count: number) => (count === 1 ? "1 column" : `${count} columns`),
        recent: "Recent files",
        forget: "Forget this file",
        gone: "The file could not be read. Choose it again.",
    },
    mappings: {
        title: "Saved mappings",
        use: "Use",
        inUse: "In use",
        delete: "Delete mapping",
        deleted: "Mapping deleted",
        saved: "Mapping saved",
        saveAs: "Save this mapping as",
        namePlaceholder: "Sitemap export",
        save: "Save mapping",
        updated: (when: string) => `saved ${when}`,
        fields: (count: number) => (count === 1 ? "1 field" : `${count} fields`),
    },
    columns: {
        title: "Match the columns",
        header: "Column",
        sample: "Sample values",
        target: "Target field",
        ignore: "Ignored",
        detected: "Matched automatically",
        unmapped: (count: number) =>
            count === 1 ? "1 column has no target and will be ignored." : `${count} columns have no target and will be ignored.`,
        needsTarget: "Map a column to Path or to Entity before going on.",
        options: "Reading options",
        pathPrefixStrip: "Strip from the start of every path",
        keywordSeparator: "Keywords separated by",
        anchorSeparator: "Anchors separated by",
        listSeparator: "Other lists separated by",
        empty: "The sheet has no readable header row.",
    },
    preview: {
        title: "What the sheet will do",
        pages: "Pages",
        entities: "Entities",
        edges: "Relationships",
        rows: "Rows",
        conflicts: "Competing pages",
        warnings: "Warnings",
        errors: "Errors",
        skipped: (count: number) => `${count} skipped`,
        counted: (action: string, count: number) => `${count} ${action}`,
        blocked: "Fix the errors in the sheet before applying it.",
        row: (row: number) => `row ${row}`,
        columnPath: "Page path",
        columnTitle: "Title",
        columnEntity: "Entity",
        columnKind: "Kind",
        columnAction: "Action",
        columnName: "Name",
        columnKeyword: "Primary keyword",
        columnFrom: "From",
        columnTo: "To",
        columnRelation: "Relation",
        columnReason: "Reason",
    },
    apply: {
        title: "Apply the sheet",
        start: "Apply",
        working: (rows: number) => `Writing ${rows} rows. Leave this screen open.`,
        done: "Applied",
        entitiesCreated: "Entities created",
        entitiesUpdated: "Entities updated",
        edgesCreated: "Relationships created",
        pagesCreated: "Pages created",
        pagesUpdated: "Pages updated",
        skipped: "Rows skipped",
        openGraph: "Open the graph",
        openPages: "Open the pages",
        again: "Import another sheet",
    },
    export: {
        title: "Write this site to a sheet",
        body: "Every page and every entity goes into one workbook, ready to edit and import back.",
        destination: "Destination file",
        choose: "Choose…",
        dialogTitle: "Where to write the sheet",
        start: "Export",
        working: "Writing the sheet",
        done: (pages: number, entities: number) => `${pages} pages and ${entities} entities written to`,
        noDestination: "Choose a destination file first",
    },
    fields: {
        none: "Not imported",
        path: "Page path",
        title: "Title",
        h1: "Heading",
        primary_keyword: "Primary keyword",
        keywords: "Keywords",
        anchors: "Anchor texts",
        entity: "Entity",
        entity_kind: "Entity kind",
        parent_entity: "Parent entity",
        related: "Related entities",
        page_kind: "Page kind",
        meta_title: "Meta title",
        meta_description: "Meta description",
        wp_type: "WordPress type",
    },
    findings: {
        bad_path: "The path cannot be used",
        no_target: "The row names neither a page nor an entity",
        duplicate_path: "Another row already claims this path",
        intermediate_path: "A parent page had to be invented for this path",
        unknown_parent: "The parent entity is not in the sheet or the graph",
        unknown_related: "A related entity is not in the sheet or the graph",
        self_edge: "The row relates an entity to itself",
        cycle: "The parents form a loop",
        cannibalization: "Two pages compete for the same keyword or entity",
        unknown_entity_kind: "The entity kind is not one Postulator knows",
        unknown_page_kind: "The page kind is not one Postulator knows",
        unknown_wp_type: "The WordPress type is not one Postulator knows",
    },
    actions: {
        create: "new",
        update: "updated",
        skip: "skipped",
    },
    edgeKinds: {
        parent: "Parent",
        related: "Related",
    },
    reasons: {
        same_primary_keyword: "Same primary keyword",
        same_entity_canonical: "Both claim the same entity",
        path_conflict: "Same path",
    },
};
