export const errorMessages = {
    NOT_FOUND: "That record no longer exists here. The view has been refreshed.",
    CONFLICT: "Something else changed this first. The view has been refreshed.",
    INVALID: "Check the highlighted fields and try again.",
    UNAUTHORIZED: "WordPress refused the credentials for this site.",
    RATE_LIMITED: "The model provider is rate limiting. Retrying shortly.",
    BUDGET_EXCEEDED: "The run stopped at its budget cap. Raise the cap or send fewer pages.",
    EXTERNAL: "An external service failed. Nothing here was changed.",
    INTERNAL: "Something went wrong inside Postulator. The details are in errors.log.",
    CANCELLED: "Cancelled.",
    NEEDS_HUMAN: "This needs your decision before it can continue.",
    LOCKED: "Postulator is locked. Unlock it to continue.",
} as const;

export const copy = {
    app: {
        name: "Postulator",
        tagline: "An entity graph turned into graph-compliant WordPress pages.",
        loading: "Loading",
        retry: "Try again",
        dismiss: "Dismiss",
        refreshed: "Refreshed",
        save: "Save",
        cancel: "Cancel",
        loadMore: "Load more",
        openExternal: "Open in your browser",
    },
    lock: {
        title: "Postulator is locked",
        prompt: "Enter the master password to unlock the workspace.",
        password: "Master password",
        unlock: "Unlock",
        unlocking: "Unlocking. Deriving the key takes a few seconds.",
        wrong: "That password did not unlock the workspace.",
        firstRun: "No master password is set. Everything is protected by Windows DPAPI alone.",
        setPassword: "Set a master password",
        unrecoverable: "The master key cannot be read. Restore a backup to recover this workspace.",
        lockNow: "Lock now",
    },
    nav: {
        overview: "Overview",
        graph: "Graph",
        pages: "Pages",
        runs: "Runs",
        templates: "Templates",
        schedules: "Schedules",
        importExport: "Import",
        reports: "Reports",
        agent: "Agent",
        settings: "Settings",
        sites: "Sites",
        inbox: "Inbox",
    },
    shell: {
        sections: "Sections",
        siteSwitcher: "Switch site",
        noSiteSelected: "No site selected",
        search: "Search",
        agentDock: "Agent",
        collapseDock: "Collapse the agent dock",
        expandDock: "Expand the agent dock",
        activeRuns: "Active runs",
        spend: "Spent",
        pluginInstalled: "Plugin installed",
        pluginMissing: "Plugin missing",
        locked: "Locked",
        unlocked: "Unlocked",
        unprotected: "No master password",
    },
    notBuilt: {
        title: "Not built yet",
        body: "This screen is scheduled and nothing stands in for it here.",
        wave: (wave: string) => `It arrives with ${wave}.`,
    },
    empty: {
        sites: "No sites yet. Add the WordPress site you want Postulator to work on.",
        pages: "No pages in the map. Import a sitemap or let the agent plan the first pages.",
        pageTree: "The page tree is empty. Sync the site or import a sheet to fill it.",
        pageLinks: "This page links nowhere yet. A generate run writes its internal links.",
        entities: "The entity graph is empty. Import a sheet or ask the agent to propose entities from the pages.",
        proposedEdges: "No proposed edges are waiting. Run a proposal to suggest relationships.",
        edges: "No edges between these entities yet. Add one or approve a proposal.",
        runs: "No runs yet. Start a generate run from the page map.",
        runItems: "This run has no items. It was started against an empty selection.",
        runEvents: "No steps have been recorded yet for this run.",
        artifacts: "This item produced no artifacts yet.",
        templates: "No templates yet. Create one or let the agent draft it for you.",
        policies: "No link policies yet. The built-in defaults apply until you add one.",
        overrides: "No overrides. Every page uses the template as written.",
        schedules: "No schedules yet. Add one to generate or sync on a timer.",
        mappings: "No saved column mappings for this site yet.",
        previewPages: "The sheet produced no pages. Check the column mapping.",
        previewEntities: "The sheet produced no entities. Check the column mapping.",
        previewEdges: "The sheet produced no relationships between entities.",
        importFindings: "Nothing to report. Every row read cleanly.",
        cannibalization: "No two pages compete for the same entity.",
        orphans: "No orphan pages. Every page is reachable from the graph.",
        topEntities: "No entity has a score yet. Recompute the scores after approving edges.",
        conversations: "No conversations yet. Ask the agent for something and it starts one.",
        messages: "Nothing said yet in this conversation.",
        pendingActions: "Nothing is waiting for approval.",
        tools: "The agent has no tools registered.",
        models: "No models in the catalog. Add one or restore the seeded catalog.",
        profiles: "No role profiles set. Every role falls back to the global model.",
        providerKeys: "No provider key is stored yet.",
        settings: "No settings in this group.",
        readiness: "Everything on the checklist is done. Start a generate run.",
        usage: "Nothing has been spent yet.",
        depth: "No pages are deep enough to chart.",
    },
    readiness: {
        providerKey: "Store an API key for at least one model provider.",
        profiles: "Point each model role at a model.",
        site: "Add the WordPress site you are working on.",
        plugin: "Install the companion plugin on the site.",
        sync: "Sync the site so Postulator knows what is already published.",
        graph: "Create entities and approve the edges between them.",
        canonicals: "Give every entity a canonical page so it can be linked to.",
        template: "Pick the template a generate run should use.",
    },
    onboarding: {
        title: "Getting ready",
        subtitle: "A generate run writes pages that prove the graph. Every line below has to be true first.",
        panel: "Readiness",
        progress: (done: number, total: number) => `${done} / ${total} done`,
        remaining: (left: number) => (left === 1 ? "1 step left" : `${left} steps left`),
        ready: "Ready to generate",
        blocked: "Add a site before this one can be answered.",
        forSite: (name: string) => `Checked against ${name}.`,
        noSite: "Checked against your model settings only — there is no site yet.",
        recheck: "Check again",
        names: {
            providerKey: "Provider key",
            profiles: "Model roles",
            site: "Site",
            plugin: "Companion plugin",
            sync: "First sync",
            graph: "Entities and edges",
            canonicals: "Canonical pages",
            template: "Template",
        },
        actions: {
            providerKey: "Open model settings",
            profiles: "Assign the roles",
            site: "Add a site",
            plugin: "Open the site",
            sync: "Open the page map",
            graph: "Open the graph",
            canonicals: "Open the page map",
            template: "Open templates",
        },
        done: {
            providerKey: (count: number) => (count === 1 ? "1 provider has a key." : `${count} providers have a key.`),
            profiles: "Writer, editor, linker and judge all point at a model.",
            plugin: (version: string) => (version === "" ? "Installed." : `Installed, version ${version}.`),
            sync: (count: number) => `${count} pages in the map.`,
            syncAt: (when: string) => `Last synced ${when}.`,
            graph: "Entities exist and at least one edge is approved.",
            canonicals: "Every entity points at a canonical page.",
            template: "A template is available to a generate run.",
        },
        todo: {
            profiles: (roles: string) => `Still unassigned: ${roles}.`,
            graphNoEntities: "No entities yet.",
            graphNoEdges: "Entities exist, but no edge is approved yet.",
            canonicals: "At least one entity has no canonical page, so nothing can link to it.",
        },
    },
    sites: {
        title: "Sites",
        subtitle: "Every graph, page map and run below belongs to exactly one WordPress site.",
        add: "Add site",
        addTitle: "Add a site",
        editTitle: "Edit site",
        open: "Open this site",
        edit: "Edit",
        anyStatus: "Any status",
        columns: {
            name: "Name",
            baseUrl: "Base URL",
            status: "Status",
            plugin: "Plugin",
            created: "Added",
        },
        field: {
            name: "Name",
            nameHint: "What you call this site inside Postulator.",
            baseUrl: "Base URL",
            baseUrlHint: "The WordPress home URL, for example https://example.com.",
            username: "WordPress user",
            usernameHint: "The account the application password belongs to.",
            password: "Application password",
            passwordHint: "Generated under Users → Profile in WordPress, not the login password.",
            passwordKeep: "Leave empty to keep the stored password.",
            allowInsecure: "Allow plain http",
            allowInsecureHint: "Credentials travel unencrypted. Only for a local install.",
        },
        insecureWarning: "This site is reached over plain http, so the application password crosses the network unencrypted.",
        test: "Test connection",
        testing: "Testing",
        reach: {
            ok: "The site answered and the credentials work.",
            upgradeRequired: "The site answered on http and asked for https.",
            unauthorized: "The site answered but refused these credentials.",
            unreachable: "The site did not answer.",
        },
        useSuggested: (url: string) => `Use ${url}`,
        detected: (name: string) => `Reported name: ${name}`,
        woo: "WooCommerce detected",
        deleteTitle: "Delete this site",
        deleteBody: (name: string) =>
            `${name} goes, and with it its page map, entities and edges, runs and their artifacts, site templates and link policies, schedules, saved import mappings and agent conversations. Nothing on WordPress is touched.`,
        deleteConfirm: "Delete the site",
        pickSite: "Pick a site on the left to see its plugin state and credentials.",
        plugin: {
            title: "Companion plugin",
            installed: (version: string) => (version === "" ? "Installed" : `Installed, version ${version}`),
            missingTitle: (name: string) => `The companion plugin is not installed on ${name}`,
            missingBody: "Postulator falls back to the plain WordPress REST API. In that mode:",
            losses: [
                "Products and product categories stay invisible to a sync.",
                "SEO meta is read-only — title and description cannot be written back.",
                "relink_neighbors is skipped on every item, so neighbour links are never repaired.",
            ],
            recheck: "Check again",
            download: "Save the plugin zip",
            saved: (path: string) => `Companion plugin written to ${path}`,
            capabilities: "Capabilities",
            seo: "SEO plugin",
            noSeo: "none detected",
            noCapabilities: "none reported",
        },
    },
    runs: {
        title: "Runs",
        subtitle: "Every run writes pages for one site and stops itself at its budget.",
        reconnecting: "Reconnecting to the run log",
        reconnectingBody:
            "Live events are never buffered, so a reload loses the stream while the run carries on. The log below is being refilled from the run itself.",
        logFailed: "The run log could not be read",
        status: {
            pending: "Pending",
            running: "Running",
            waiting: "Waiting",
            paused: "Paused",
            completed: "Completed",
            failed: "Failed",
            cancelled: "Cancelled",
        },
        pauseReason: {
            budget_exceeded: "Paused at the budget cap.",
            awaiting_confirmation: "Paused until you approve the pending action.",
            needs_human: "Paused for a human decision.",
            user: "Paused by you.",
        },
        pauseReasonShort: {
            budget_exceeded: "budget cap",
            awaiting_confirmation: "awaiting approval",
            needs_human: "needs human",
            user: "paused by you",
        },
        unknownPauseReason: "Paused for a reason this build does not recognise.",
        budgetPausedTitle: "This run stopped at its budget cap",
        budgetPausedBody:
            "A run carries the cap it was started with and there is no binding that raises it. Resuming lets the run continue until its next model call and then it pauses again. To finish the work, cancel this run and start a new one over the same pages with a higher cap.",
        pause: "Pause",
        resume: "Resume",
        cancel: "Cancel run",
        cancelTitle: "Cancel this run",
        cancelBody:
            "Every pending, running and waiting item stops. Pages already published stay published; nothing on WordPress is undone.",
        cancelConfirm: "Cancel the run",
        keepRunning: "Keep it running",
        retryStep: "Retry this step",
        retryBusy: "The item has not stopped, so there is nothing to retry.",
        retryBlocked: {
            inputs_expired: "Inputs expired — re-run the page",
        },
        retryBlockedBody:
            "The artifacts this step needs were purged after the page published, and no step regenerates them. Start a fresh run over this page instead.",
        unknownRetryBlock: "Retry is refused for a reason this build does not recognise.",
        rerunPage: "Start a run over this page",
        columns: {
            kind: "Kind",
            status: "Status",
            progress: "Items",
            spend: "Spent",
            started: "Started",
            finished: "Finished",
            created: "Created",
            path: "Path",
            step: "Step",
            attempts: "Try",
            error: "Error",
            updated: "Updated",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            status: "Status",
            anyStatus: "Any status",
            kind: "Kind",
            anyKind: "Any kind",
            itemStatus: "Items",
            anyItemStatus: "All items",
        },
        loading: "Loading the run list",
        loadingItems: "Loading the run items",
        loadMore: "Load more",
        noMatch: "No run matches these filters",
        noMatchBody: "Widen the filters or reset them to see every run of this site.",
        noItemMatch: "No item of this run has that status.",
        openRun: "Open this run",
        backToRuns: "Runs",
        notFound: "This run is no longer here.",
        detail: {
            header: (kind: string) => `${kind} run`,
            startedBy: (actor: string) => `started by ${actor}`,
            publishMode: (mode: string) => `publish mode: ${mode}`,
            deadline: "Deadline",
            template: (id: string, version: number) => `template ${id} v${version}`,
            noTemplate: "no template recorded",
            targets: (count: number) => (count === 1 ? "1 target page" : `${count} target pages`),
            items: (done: number, total: number) => `${done} / ${total} items`,
            done: "completed",
            failed: "failed",
            needsHuman: "need a human",
            running: "running",
            pending: "pending",
            spent: "Spent",
            spentOf: (spent: string, cap: string) => `${spent} of ${cap}`,
            noCap: "No cap was set for this run",
            noCapBody:
                "A run with no dollar cap never stops itself on spend. Cancel it if the bill matters, and give the next run a cap.",
            hardStop: "A run pauses itself at the cap; it never overruns it.",
            tokens: "Tokens",
            tokensBody: "Tokens are reported, not capped — the run stops on dollars.",
            calls: (count: number) => (count === 1 ? "1 model call" : `${count} model calls`),
            liveStats: "Counted from the run log while the run is live.",
            rowStats: "Counted from the finished run.",
            failure: "The run failed",
        },
        events: {
            title: "Events",
            live: "live",
            catchingUp: "catching up",
            settled: "log complete",
            filterItem: "This item only",
            filterAll: "Whole run",
            names: {
                "run.queued": "Run queued",
                "run.started": "Run started",
                "run.paused": "Run paused",
                "run.resumed": "Run resumed",
                "run.cancelled": "Run cancelled",
                "run.completed": "Run completed",
                "run.failed": "Run failed",
                "run.budget_exceeded": "Budget cap reached",
                "item.started": "Item started",
                "item.done": "Item done",
                "item.failed": "Item failed",
                "item.needs_human": "Item needs a human",
                "step.started": "Step started",
                "step.done": "Step done",
                "step.failed": "Step failed",
                "step.retrying": "Step retrying",
                "llm.usage": "Model call",
            },
            attempt: (attempt: number) => `attempt ${attempt}`,
            retryIn: (delay: string) => `retrying in ${delay}`,
            seq: (seq: number) => `#${seq}`,
        },
        step: {
            position: (at: number, total: number, name: string) => `step ${at} of ${total} — ${name}`,
            unknownRecipe: (name: string) => `step ${name}`,
            noStep: "no step recorded yet",
            waitingUntil: (left: string) => `waiting ${left}`,
            retrying: (attempt: number, left: string) => `retrying, attempt ${attempt} in ${left}`,
            recipe: (first: string, last: string, total: number) => `${total} steps · ${first} → ${last}`,
            noPercent: "There is no progress inside a step — only which step the item is on.",
        },
        start: {
            open: "Start run",
            title: "Start a run",
            body: "A run writes pages for the selected targets and stops itself at the dollar cap you set here.",
            pages: "Target pages",
            pagesHint: "Every selected page becomes one item of the run.",
            selected: (count: number) => (count === 1 ? "1 page selected" : `${count} pages selected`),
            noPages: "Select at least one page.",
            search: "Path prefix",
            publishMode: "Publish mode",
            kind: "Kind",
            template: "Template",
            templateAuto: "Resolved per page",
            templateHint: "Left automatic, each page uses the template its own overrides resolve to.",
            cap: "Dollar cap",
            capHint: "The run pauses itself once spend passes this. Zero means no cap at all.",
            capZero: "With no cap this run will not stop itself on spend.",
            estimate: "Price this run",
            estimating: "Pricing",
            estimated: (usd: string, tokens: string) => `${usd} · about ${tokens} tokens`,
            estimateHint: "Priced without enqueuing anything.",
            estimateFirst: "Price the run before starting it.",
            overCap: "The estimate is above the cap, so this run will pause before it finishes.",
            confirm: "Start the run",
            cancel: "Cancel",
            started: "Run started",
        },
        review: {
            title: "Review",
            close: "Close",
            item: (path: string) => path,
            attempt: (attempts: number) => (attempts === 1 ? "attempt 1" : `${attempts} attempts`),
            noArtifacts: "Nothing to review yet",
            noArtifactsBody:
                "This item has produced no artifact so far. Each step writes its own, and they appear as the run reaches them.",
            loading: "Loading the artifacts of this item",
            unreadable: "This artifact could not be read",
            unreadableBody: "It is not in the shape this build expects, so nothing is shown rather than something wrong.",
            purged: "Removed by the retention sweep",
            purgedBody: (days: number) =>
                `Bodies, drafts and images are dropped ${days} days after the page publishes. The row stays, and the compliance findings and the judge score below are untouched.`,
            purgedBodyUnknown:
                "Bodies, drafts and images are dropped once the retention window passes on a published page. The row stays, and the compliance findings and the judge score below are untouched.",
            noDiff: "There is no comparison with the live page — raw WordPress content is not exposed by any binding.",
            kinds: {
                link_context: "Targets",
                draft: "Draft",
                body_html: "Body",
                meta: "Meta",
                images: "Images",
                validation_report: "Links & compliance",
                judge_report: "Judge",
                publish_result: "Publish",
                relink_result: "Neighbours",
                sync_result: "Sync",
                final_report: "Report",
            },
            body: {
                preview: "Sandboxed preview",
                isolated: "Rendered in an isolated frame with no scripts and no access to this window.",
                empty: "The body artifact is empty.",
            },
            links: {
                owed: "Owed to the graph",
                owedEmpty: "The graph asked this page for no links.",
                satisfied: "satisfied",
                missing: "missing",
                required: "required",
                optional: "optional",
                relation: { up: "up", down: "down", sibling: "sideways" },
                actual: "Links on the page",
                actualEmpty: "No link was recorded on this page.",
                classes: {
                    graph: "graph",
                    self: "self",
                    external: "external",
                    unknown_internal: "unknown internal",
                },
                classesNote:
                    "Graph links come from the placements the run made; the rest are the links compliance flagged, so a clean non-graph link leaves no record.",
                findings: "Findings",
                errors: (count: number) => (count === 1 ? "1 error — the item fails" : `${count} errors — the item fails`),
                warnings: (count: number) => (count === 1 ? "1 warning" : `${count} warnings`),
                clean: "No compliance finding on this page.",
                warningsDoNotFail: "A warning does not fail the item; an error does.",
                score: (score: number) => `score ${score.toFixed(2)}`,
            },
            judge: {
                score: "Score",
                outOf: "out of 1.00",
                issues: "Issues",
                suggestions: "Suggestions",
                none: "The judge raised nothing.",
                rejudge: "Judge this page again",
                rejudging: "Judging",
                rejudgeHint: "This calls the judge model and spends tokens. It never runs on its own.",
                rejudged: (tokens: number) => `Judged again for ${tokens} tokens.`,
                unavailable: "The judge did not return a score for this item.",
            },
            publish: {
                result: "Result",
                created: "created",
                updated: "updated",
                status: "WordPress status",
                wpId: "WordPress id",
                hash: "Content hash",
                seoApplied: "SEO fields written",
                skipped: "Skipped",
                liveUrl: "Live URL",
                none: "This item has not published.",
            },
            draft: { sections: "Sections", summary: "Summary" },
            meta: { characters: (count: number) => `${count} characters` },
            images: { featured: "Featured image", skipped: "Skipped", none: "No image was placed." },
            relink: {
                linked: "linked",
                conflicts: "conflicts",
                skipped: "skipped",
                neighbours: "Neighbours",
                none: "No neighbour was touched.",
            },
            sync: { none: "Nothing was read back for this item." },
            report: {
                score: "Final score",
                errors: "errors",
                warnings: "warnings",
                none: "This item produced no final report.",
            },
        },
    },
    agent: {
        send: "Send",
        cancelTurn: "Stop",
        thinking: "Working",
        confirmTitle: "Approve this action",
        approve: "Approve",
        reject: "Reject",
        autonomous: "Autonomous mode runs write and dangerous tools without asking.",
        confirmMode: "Confirm mode asks before every write.",
        turnStalled: "The turn stopped reporting. The saved messages are shown instead.",
    },
    pages: {
        views: { table: "Table", tree: "Tree" },
        columns: {
            path: "Path",
            title: "Title",
            wpType: "WP type",
            status: "Status",
            entity: "Entity",
            drift: "Drift",
            synced: "Synced",
            created: "Created",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            pathPrefix: "Path prefix",
            pathPrefixHint: "Matches the start of a path, such as /collections/.",
            status: "Status",
            anyStatus: "Any status",
            entity: "Entity",
            anyEntity: "Any entity",
            unmapped: "No entity attached",
            noEntities: "This site has no entities yet.",
            partialEntities: "More entities exist than were loaded, so some rows read as mapped without a name.",
        },
        siteTotal: (total: number) => `${total} pages`,
        loadMore: "Load more",
        loading: "Loading the page map",
        noMatch: "No page matches these filters",
        noMatchBody: "Widen the filters or reset them to see the whole map.",
        plan: "Plan a page",
        untitled: "Untitled",
        mapped: "mapped",
        unmapped: "no entity",
        empty: { title: "The page map is empty" },
        drift: {
            badge: "drift",
            title: "Someone edited this page in WordPress",
            body: "WordPress reports a change made after Postulator last wrote this page. What changed cannot be shown: raw WordPress content never crosses into the app, so there is nothing here to compare against.",
            decision:
                "A publish run started with refuseDrift pauses this page for a human instead of overwriting the edit. Without it the run overwrites the page and records a drift finding on the publish result.",
            lastWritten: "Last synced",
            wpModified: "WordPress modified",
        },
        tree: {
            title: "Page tree",
            noFilters: "The tree takes a site and nothing else, so the filters apply to the table only.",
            unbounded:
                "The tree call returns every page on the site in one uncursored response. There is no limit and no cursor.",
            guard: (total: number) =>
                `This site has ${total} pages, and loading them all in one response would block the window.`,
            unknownSize: "The size of this site is not known, so the tree was not fetched automatically.",
            useTable: "Use the table instead",
            loadAnyway: "Load the whole tree anyway",
            load: "Load the tree",
            nodes: (count: number) => `${count} pages in the tree`,
            children: (count: number) => `${count} below`,
            expandAll: "Expand all",
            collapseAll: "Collapse all",
            showMore: (hidden: number) => `Show ${hidden} more`,
        },
        detail: {
            close: "Close",
            notFound: "This page is no longer in the map.",
            entity: "Entity",
            entityMissing: "The entity this page points at could not be read.",
            entityMeta: (kind: string, score: number) => `${kind} · score ${score.toFixed(2)}`,
            noEntity: "Not mapped to an entity",
            noEntityBody: "A page outside the graph is never a link target, so generation cannot link to it.",
            noEntityOption: "No entity",
            map: "Map",
            change: "Change",
            unmap: "Unmap",
            canonical: "canonical",
            canonicalTitle: "Canonical pages are what the graph links to",
            canonicalBody:
                "An entity with no canonical page is never a link target, so generation cannot link to it. Mapping a page to an entity does not make it canonical.",
            makeCanonical: "Make this the canonical page",
            canonicalIsHere: "This page is the canonical page for its entity.",
            canonicalElsewhere: "Another page is canonical for this entity.",
            canonicalMissing: "This entity has no canonical page, so nothing can link to it.",
            openCanonical: "Open the canonical page",
            meta: "Meta",
            path: "Path",
            pathHint: "Normalised on save: lower case, a leading and a trailing slash, no query and no fragment.",
            title: "Title",
            h1: "H1",
            metaTitle: "Meta title",
            metaDescription: "Meta description",
            canonicalUrl: "Canonical URL",
            wpType: "WP type",
            status: "Status",
            characters: (count: number) => `${count} characters`,
            save: "Save",
            revert: "Revert",
            links: "Outgoing links",
            linksSummary: (total: number, generated: number) => `${total} links · ${generated} written by a run`,
            report: "Last report",
            noReport: "No run has touched this page yet",
            noReportBody: "Send this page through a generate run and its report lands here.",
            openRun: "Open the run item",
            judge: (score: number) => `judge ${score.toFixed(0)}`,
            validation: (score: number) => `validation ${score.toFixed(0)}`,
            publishedAs: (status: string) => `published as ${status}`,
            liveUrl: "Live URL",
            deletePage: "Delete",
            deleteTitle: "Delete this page?",
            deleteBody: "The row leaves the page map. Nothing on the WordPress site is touched.",
            deleteConfirm: "Delete",
            cancel: "Cancel",
        },
        create: {
            title: "Plan a page",
            body: "A planned page is a row in the map. It does not exist on WordPress until a run publishes it.",
            confirm: "Plan it",
            cancel: "Cancel",
            noEntity: "No entity",
            entityHint: "A page with no entity is not part of the graph and is never a link target.",
        },
        conflict: {
            title: "This would cannibalise another page",
            body: "Two pages cannot compete for the same target, so nothing was written.",
            reason: {
                path_conflict: "already takes that path",
                same_entity_canonical: "is already the canonical page for that entity",
                same_primary_keyword: "already targets that primary keyword",
            },
            unknownReason: "conflicts with this page",
            descendantsTitle: "The path cannot change",
            descendants: (count: number) =>
                `${count} pages sit beneath this one, so its path is fixed. Move or delete them first.`,
        },
    },
    graph: {
        views: { map: "Map", outline: "Outline" },
        label: "Entity graph",
        loading: "Loading the graph",
        total: (total: number) => (total === 1 ? "1 entity" : `${total} entities`),
        search: {
            label: "Find an entity",
            placeholder: "Find an entity",
            noHits: "Nothing matches",
            field: { name: "name", primaryKeyword: "keyword", secondaryKeyword: "secondary keyword" },
        },
        lens: {
            all: "All",
            noPage: "No page",
            proposed: "Proposed",
            orphan: "Orphans",
            ai: "From AI",
            kinds: "Kinds",
            anyKind: "Every kind",
            isolate: "Isolate",
            isolateHint: "Hide everything the lens does not match and keep the path to each match.",
            hint: {
                all: "Every entity of the site.",
                noPage: "Entities without a canonical page. Nothing can link to them until they get one.",
                proposed: "Entities touched by an edge that still waits for a decision.",
                orphan: "Entities that are not hubs and have no approved parent.",
                ai: "Entities the model proposed. Review their names, keywords and anchors.",
            },
        },
        controls: {
            zoomIn: "Zoom in",
            zoomOut: "Zoom out",
            fit: "Fit the whole map",
            expandAll: "Expand every subtree",
            collapseToRoots: "Collapse to the roots",
            showRelated: "Show every related link",
            hideRelated: "Show related links for the selection only",
            legend: "Legend",
            minimap: "Minimap",
            zoom: (percent: number) => `${percent}%`,
        },
        legend: {
            title: "Legend",
            kinds: "Kinds",
            nodes: "Nodes",
            edges: "Edges",
            noPage: "No canonical page, cannot be linked to",
            proposedPlacement: "Placed under a proposed parent",
            collapsed: "Collapsed subtree with its count",
            selected: "Selected",
            parent: "Parent",
            related: "Related, approved",
            relatedProposed: "Related, proposed",
            extraParent: "A second parent",
            proposedBadge: "Proposed edges waiting on it",
            order: "Children are ordered by score, strongest first.",
        },
        node: {
            more: (shown: number, hidden: number) => `${shown} shown, ${hidden} more`,
            showMore: (count: number) => `Show ${count} more`,
            showAll: "Show all",
            noPage: "no page",
            proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
            parents: (count: number) => `${count} parents`,
        },
        empty: {
            title: "The graph is empty",
            body: "Nothing gets linked until entities exist and their edges are approved.",
            propose: "Propose from pages",
            add: "Add an entity",
            import: "Import a sheet",
        },
        summary: {
            title: "This site",
            hint: "Pick an entity on the map to read and edit it.",
            byKind: "By kind",
            attention: "Needs attention",
            noPage: (count: number) => (count === 1 ? "1 entity has no page" : `${count} entities have no page`),
            orphan: (count: number) => (count === 1 ? "1 orphan" : `${count} orphans`),
            proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
            multiParent: (count: number) => (count === 1 ? "1 entity with two parents" : `${count} entities with several parents`),
            clean: "Every entity has a page, a parent and no edge waiting.",
            top: "Highest scores",
            keys: "Keys",
            keyRows: [
                ["Arrows", "move through the map"],
                ["Space", "fold or unfold a subtree"],
                ["Ctrl F", "find an entity"],
                ["F", "fit the map"],
                ["Esc", "clear the selection"],
            ],
        },
        inspector: {
            title: "Entity",
            close: "Close the inspector",
            kind: "Kind",
            intent: "Intent",
            primaryKeyword: "Primary keyword",
            secondaryKeywords: "Secondary keywords",
            anchors: "Anchors",
            anchorsHint: "The link texts another page may use to point here.",
            noAnchors: "No anchors. The entity name is used instead.",
            score: "Score",
            rank: (rank: number, total: number) => `rank ${rank} of ${total}`,
            source: "Source",
            page: "Canonical page",
            openPage: "Open the canonical page",
            noPage: "No canonical page",
            noPageBody: "Nothing can link to this entity until a page is canonical for it.",
            relations: "Relations",
            parents: "Parents",
            children: "Children",
            related: "Related",
            proposedParent: "proposed parent",
            showInMap: "Show in the map",
            moreChildren: (count: number) => `${count} more in the map`,
            noRelations: "No edges yet.",
            created: "Created",
        },
        outline: {
            columns: { name: "Entity", kind: "Kind", score: "Score", page: "Page", attention: "Attention" },
            page: "page",
            noPage: "no page",
            fold: "Fold",
            unfold: "Unfold",
            children: (count: number) => `${count} below`,
        },
    },
    templates: {
        title: "Templates",
        subtitle:
            "A template says what a generated page contains. Ask the agent to write one; this is where you read it and change it.",
        loading: "Loading templates",
        tabs: {
            templates: "Templates",
            policies: "Link policies",
        },
        columns: {
            name: "Name",
            pageKind: "Page kind",
            sections: "Sections",
            words: "Words",
            version: "Version",
            created: "Created",
            links: "Max links",
            anchors: "Anchors",
            forbids: "Forbids",
        },
        groups: {
            global: "Available on every site",
            globalBody: "Changing one of these changes it for every site in this workspace.",
            site: "Only on this site",
            siteBody: "These belong to this site and no other site can use them.",
        },
        scope: {
            global: "Every site",
            site: "This site",
        },
        siteDefault: "Site default",
        siteDefaultHint: "Pages with no template of their own use this one. That choice is made on the site, not here.",
        sectionCount: (count: number) => (count === 1 ? "1 section" : `${count} sections`),
        wordRange: (min: number, max: number) => `${min}–${max}`,
        versionLabel: (version: number) => `v${version}`,
        newTemplate: "New template",
        nothingToCopy: "Nothing to copy from",
        nothingToCopyBody:
            "A new template starts as a copy of one that already exists. Ask the agent to write the first one.",
        askAgent: "Ask the agent",
        noMatch: "No template of that kind",
        noMatchBody: "Clear the page kind filter to see the rest.",
        anyPageKind: "Any page kind",
        create: {
            title: "New template",
            body: "A new template starts as a copy of one that already exists. Rename it, then change what you need.",
            confirm: "Create it",
            cancel: "Cancel",
            copyFrom: "Copy from",
            copyFromHint: "Every section, rule, model and step is copied. Nothing ties the two together afterwards.",
            name: "Name",
            pageKind: "Page kind",
            pageKindHint: "A short label such as hub, product or guide. It is how a page asks for this template.",
            scope: "Available to",
            scopeHint: "Either every site in this workspace, or this site alone.",
        },
        editor: {
            back: "All templates",
            save: "Save",
            revert: "Revert",
            unsaved: "Unsaved changes",
            deleteTemplate: "Delete",
            deleteTitle: "Delete this template?",
            deleteBody:
                "The template goes and its overrides go with it. Pages already generated from it are untouched.",
            deleteConfirm: "Delete",
            cancel: "Cancel",
            notFound: "This template no longer exists.",
            name: "Name",
            pageKind: "Page kind",
            identity: "Name and kind",
            tabs: {
                sections: "Sections",
                content: "Content",
                links: "Links",
                meta: "Meta and images",
                models: "Models",
                recipe: "Recipe",
            },
        },
        layer: {
            label: "Editing",
            global: "The template",
            site: "This site",
            globalHint: "What you change here reaches every site that uses this template.",
            siteHint:
                "What you change here stays on this site. Everything you leave alone keeps following the template.",
            fromGlobal: "From the template",
            fromSite: "Set by this site",
            fromPage: "Set by this page",
            follow: "Follow the template again",
            templateSays: (value: string) => `The template says ${value}.`,
            on: "on",
            off: "off",
            none: "nothing",
        },
        overrides: {
            title: "Where the values come from",
            base: "The template is the starting point. A site, and then a page, may change parts of it.",
            runOrder: "Template, then this site, then the page. The last one to set a value wins.",
            siteTitle: "What this site changes",
            siteNone: "This site changes nothing. Every value comes from the template.",
            sitePrefix: "This site",
            pagePrefix: "This page",
            clearSite: "Drop every change this site makes",
            clearSiteTitle: "Drop the changes this site makes?",
            clearSiteBody: "Every value goes back to what the template says. Pages keep their own changes.",
            clearConfirm: "Drop them",
            cancel: "Cancel",
            pagesTitle: "Pages that change it",
            pagesNone: "No page changes this template.",
            pageCount: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
            clearPage: "Drop the changes this page makes",
            clearPageTitle: "Drop the changes this page makes?",
            clearPageBody: "The page goes back to what the template and this site say.",
            viewResolved: "See what this page ends up with",
            resolvedTitle: "What this page ends up with",
            resolvedBody: "Every value below, and the layer that decided it.",
            unknownPage: "a page that no longer exists",
            resolveFailed: "This page cannot be resolved: it has no template and its site has no default.",
            close: "Close",
        },
        sentence: {
            sections: (count: number, headings: string) =>
                count === 1 ? `writes one section, ${headings}` : `writes its own ${count} sections: ${headings}`,
            sectionsNone: "removes every section",
            tone: (tone: string) => `changes the tone to “${tone}”`,
            toneNone: "drops the tone instruction",
            shorter: (min: number, max: number) => `shortens the page to ${min}–${max} words`,
            longer: (min: number, max: number) => `lengthens the page to ${min}–${max} words`,
            length: (min: number, max: number) => `sets the page length to ${min}–${max} words`,
            lengthMin: (min: number) => `asks for at least ${min} words`,
            lengthMax: (max: number) => `caps the page at ${max} words`,
            primaryInTitle: (on: boolean) =>
                on ? "requires the primary keyword in the title" : "stops requiring the primary keyword in the title",
            primaryInH1: (on: boolean) =>
                on ? "requires the primary keyword in the H1" : "stops requiring the primary keyword in the H1",
            primaryInFirstParagraph: (on: boolean) =>
                on
                    ? "requires the primary keyword in the first paragraph"
                    : "stops requiring the primary keyword in the first paragraph",
            maxDensity: (percent: string) => `caps keyword density at ${percent}`,
            upDepth: (levels: number) =>
                levels === 0
                    ? "stops linking up to parent pages"
                    : levels === 1
                      ? "links up one level to the parent page"
                      : `links up ${levels} levels of parent pages`,
            downLinks: (on: boolean) => (on ? "links down to child pages" : "stops linking down to child pages"),
            siblingMinWeight: (weight: string) => `only links siblings scoring ${weight} or higher`,
            maxLinks: (links: number) => `allows at most ${links} internal links`,
            maxPerTarget: (links: number) =>
                links === 1 ? "allows one link to any single page" : `allows up to ${links} links to the same page`,
            parentLinkWithinParagraphs: (paragraphs: number) =>
                paragraphs === 0
                    ? "stops insisting on an early parent link"
                    : paragraphs === 1
                      ? "puts the parent link in the first paragraph"
                      : `puts the parent link inside the first ${paragraphs} paragraphs`,
            childrenSection: (on: boolean) =>
                on ? "adds a section listing the child pages" : "drops the section listing the child pages",
            titlePattern: (pattern: string) => `uses the title pattern “${pattern}”`,
            titlePatternNone: "drops the title pattern",
            descriptionMax: (characters: number) => `caps the meta description at ${characters} characters`,
            featured: (on: boolean) => (on ? "adds a featured image" : "drops the featured image"),
            inline: (images: number) =>
                images === 0
                    ? "uses no inline images"
                    : images === 1
                      ? "asks for one inline image"
                      : `asks for ${images} inline images`,
            imageSource: (source: string) => `takes images from ${source}`,
            profile: (role: string, provider: string, model: string) => `uses ${provider} ${model} for the ${role}`,
            profileNone: (role: string) => `lets the ${role} fall back to the site model`,
            stepsOff: (steps: string) => `skips ${steps}`,
            stepsOn: (steps: string) => `also runs ${steps}`,
            recipe: "changes which steps run",
            other: (field: string) => `changes ${field}`,
        },
        sections: {
            title: "Sections",
            body: "A generated page is written section by section, in this order.",
            add: "Add a section",
            empty: "No sections yet",
            emptyBody: "A template needs at least one section before a run can use it.",
            heading: "Heading",
            intent: "What this section has to do",
            intentHint: "Written for the model, not for the reader.",
            targetWords: "Target words",
            required: "Required",
            requiredHint: "A required section is never dropped, however short the page is.",
            primaryInHeading: "Primary keyword in the heading",
            include: "Keywords this section must use",
            includeAdd: "Add",
            includePlaceholder: "ceramic mug",
            includeRemove: (word: string) => `Remove ${word}`,
            includeEmpty: "No keyword is pinned to this section.",
            moveUp: "Move up",
            moveDown: "Move down",
            remove: "Remove this section",
            untitled: "Untitled section",
            position: (index: number, total: number) => `${index} of ${total}`,
        },
        content: {
            title: "Tone and length",
            tone: "Tone",
            toneHint: "One or two sentences the writer follows on every page.",
            lengthMin: "Shortest",
            lengthMax: "Longest",
            lengthHint: "Total words across every section.",
            keywords: "Primary keyword",
            keywordsBody: "Where the page has to carry the keyword it is written for.",
            primaryInTitle: "In the title",
            primaryInH1: "In the H1",
            primaryInFirstParagraph: "In the first paragraph",
            maxDensity: "Highest density",
            maxDensityHint: "As a share of all words. 0.025 is 2.5%.",
        },
        links: {
            title: "Link rules",
            body: "These decide which internal links a generated page carries and how many.",
            fromTemplate:
                "At run time these come from the template, not from the link policy. The policy decides only external links, self links and anchors.",
            upDepth: "Levels up",
            upDepthHint: "How far up the parent chain the page links.",
            downLinks: "Link down to children",
            siblingMinWeight: "Lowest sibling score",
            siblingMinWeightHint: "Between 0 and 1. A related entity below this is not linked.",
            maxLinks: "Most links on a page",
            maxPerTarget: "Most links to one page",
            parentLinkWithinParagraphs: "Parent link within",
            parentLinkWithinParagraphsHint: "Paragraphs from the top. 0 turns the rule off.",
            childrenSection: "Add a section listing the children",
        },
        meta: {
            title: "Meta",
            titlePattern: "Title pattern",
            titlePatternHint: "Placeholders such as {primaryKeyword} and {siteName} are filled in per page.",
            descriptionMax: "Longest description",
            descriptionMaxHint: "Characters. Google truncates around 155.",
            images: "Images",
            featured: "Featured image",
            inline: "Inline images",
            source: "Where images come from",
            sourceHint: "A source is required as soon as any image is asked for.",
            noSource: "Not chosen",
        },
        imageSource: {
            ai: "the image model",
            wpmedia: "the WordPress media library",
            local: "a local folder",
        },
        models: {
            title: "Models",
            body: "A role left out here falls back to the site profile, and then to the global one.",
            role: "Role",
            provider: "Provider",
            model: "Model",
            add: "Pin a role to a model",
            remove: (role: string) => `Unpin the ${role} role`,
            empty: "No role is pinned here",
            emptyBody:
                "Every role follows the model settings. Pin one only when this template needs a different model.",
            pickModel: "Pick a model",
            catalogEmpty: "The model catalog is empty, so there is nothing to pin a role to.",
            allPinned: "Every role is already pinned.",
        },
        recipe: {
            title: "Recipe",
            body: "The steps a run takes for one page, in the order the pipeline runs them.",
            order: "This order is the pipeline order and cannot be rearranged.",
            enabled: (on: number, total: number) => `${on} of ${total} steps on`,
            noneEnabled: "No step is on, so a run cannot start from this template.",
            unknown: "Not a step this build knows about. It is kept as it was written.",
            carriesParams: "Carries settings the agent wrote",
        },
        steps: {
            resolve_context: "Work out what this page may link to",
            generate_body: "Write the body",
            generate_meta: "Write the title and description",
            insert_links: "Insert the internal links",
            repair_links: "Repair the links the checks refused",
            generate_images: "Make the images",
            validate: "Check the page against the rules",
            judge: "Score the page",
            publish: "Publish it to WordPress",
            relink_neighbors: "Relink the neighbouring pages",
            sync_back: "Read the published page back",
            report: "Write the run report",
            sync_site: "Read the whole site",
        },
    },
    policies: {
        title: "Link policies",
        subtitle: "A policy decides external links, self links and how anchor text is chosen.",
        loading: "Loading link policies",
        effective: "In force on this site",
        effectiveFromSite: "Chosen on the site as its link policy.",
        effectiveFallback: "No policy is chosen on the site, so the workspace default applies.",
        effectiveMissing: "No link policy applies to this site.",
        split: "Two sources, one outcome",
        splitBody:
            "A run reads the link rules — how many links, how far up, which siblings — from the template it is using. It reads external links, self links and the anchor strategy from the policy in force. The link rules stored on a policy are kept but never read.",
        forbidExternal: "Forbid links off the site",
        forbidSelf: "Forbid a page linking to itself",
        anchorStrategy: "Anchor text",
        anchorStrategyHint: "How the anchor for a link is chosen when an entity carries several.",
        anchor: {
            prefer_user: "Prefer the anchor you wrote",
            rotate: "Rotate through every anchor",
        },
        forbidsBoth: "external, self",
        forbidsExternal: "external",
        forbidsSelf: "self",
        forbidsNone: "nothing",
        newPolicy: "New policy",
        edit: "Edit",
        create: {
            title: "New link policy",
            body: "A new policy starts from the one in force on this site.",
            confirm: "Create it",
            editTitle: "Edit this link policy",
            editBody: "Saving changes it for every site that uses it.",
            save: "Save",
            cancel: "Cancel",
            name: "Name",
            scope: "Available to",
            scopeHint: "Either every site in this workspace, or this site alone.",
        },
        rulesTitle: "Link rules on this policy",
        rulesBody: "Kept on the record, but a run reads its link rules from the template instead.",
        deleteTitle: "Delete this link policy?",
        deleteBody: "Sites that point at it fall back to the workspace default.",
        deleteConfirm: "Delete",
        delete: "Delete",
    },
    toasts: {
        saved: "Saved",
        deleted: "Deleted",
        started: "Started",
        copied: "Copied",
    },
    errors: errorMessages,
};
