export const errorMessages = {
    NOT_FOUND: "That record no longer exists here. The view has been refreshed.",
    CONFLICT: "Something else changed this first. The view has been refreshed.",
    INVALID: "Check the highlighted fields and try again.",
    UNAUTHORIZED: "WordPress refused the credentials for this site.",
    RATE_LIMITED: "The model provider is rate limiting. Retrying shortly.",
    BUDGET_EXCEEDED: "The run stopped at its budget cap. Raise the cap or send fewer pages.",
    EXTERNAL: "An external service failed. Nothing here was changed.",
    INTERNAL: "Something went wrong inside Postulator. The details are in errors.log.",
    CANCELLED: "Cancelled.",
    NEEDS_HUMAN: "This needs your decision before it can continue.",
    LOCKED: "Postulator is locked. Unlock it to continue.",
} as const;

export const copy = {
    app: {
        name: "Postulator",
        tagline: "An entity graph turned into graph-compliant WordPress pages.",
        loading: "Loading",
        retry: "Try again",
        dismiss: "Dismiss",
        refreshed: "Refreshed",
        save: "Save",
        cancel: "Cancel",
        loadMore: "Load more",
        openExternal: "Open in your browser",
    },
    lock: {
        title: "Postulator is locked",
        prompt: "Enter the master password to unlock the workspace.",
        password: "Master password",
        unlock: "Unlock",
        unlocking: "Unlocking. Deriving the key takes a few seconds.",
        wrong: "That password did not unlock the workspace.",
        firstRun: "No master password is set. Everything is protected by Windows DPAPI alone.",
        setPassword: "Set a master password",
        unrecoverable: "The master key cannot be read. Restore a backup to recover this workspace.",
        lockNow: "Lock now",
    },
    nav: {
        overview: "Overview",
        graph: "Graph",
        pages: "Pages",
        links: "Links",
        runs: "Runs",
        templates: "Templates",
        schedules: "Schedules",
        importExport: "Import",
        reports: "Reports",
        agent: "Agent",
        settings: "Settings",
        sites: "Sites",
        inbox: "Inbox",
    },
    shell: {
        sections: "Sections",
        siteSwitcher: "Switch site",
        noSiteSelected: "No site selected",
        search: "Search",
        agentDock: "Agent",
        collapseDock: "Collapse the agent dock",
        expandDock: "Expand the agent dock",
        activeRuns: "Active runs",
        spend: "Spent",
        pluginInstalled: "Plugin installed",
        pluginMissing: "Plugin missing",
        locked: "Locked",
        unlocked: "Unlocked",
        unprotected: "No master password",
    },
    notBuilt: {
        title: "Not built yet",
        body: "This screen is scheduled and nothing stands in for it here.",
        wave: (wave: string) => `It arrives with ${wave}.`,
    },
    empty: {
        sites: "No sites yet. Add the WordPress site you want Postulator to work on.",
        pages: "No pages in the map. Import a sitemap or let the agent plan the first pages.",
        pageTree: "The page tree is empty. Sync the site or import a sheet to fill it.",
        pageLinks: "This page links nowhere yet. A generate run writes its internal links.",
        entities: "The entity graph is empty. Import a sheet or ask the agent to propose entities from the pages.",
        proposedEdges: "No proposed edges are waiting. Run a proposal to suggest relationships.",
        edges: "No edges between these entities yet. Add one or approve a proposal.",
        runs: "No runs yet. Start a generate run from the page map.",
        runItems: "This run has no items. It was started against an empty selection.",
        runEvents: "No steps have been recorded yet for this run.",
        artifacts: "This item produced no artifacts yet.",
        templates: "No templates yet. Create one or let the agent draft it for you.",
        policies: "No link policies yet. The built-in defaults apply until you add one.",
        overrides: "No overrides. Every page uses the template as written.",
        schedules: "No schedules yet. Add one to generate or sync on a timer.",
        mappings: "No saved column mappings for this site yet.",
        previewPages: "The sheet produced no pages. Check the column mapping.",
        previewEntities: "The sheet produced no entities. Check the column mapping.",
        previewEdges: "The sheet produced no relationships between entities.",
        importFindings: "Nothing to report. Every row read cleanly.",
        cannibalization: "No two pages compete for the same entity.",
        orphans: "No orphan pages. Every page is reachable from the graph.",
        topEntities: "No entity has a score yet. Recompute the scores after approving edges.",
        conversations: "No conversations yet. Ask the agent for something and it starts one.",
        messages: "Nothing said yet in this conversation.",
        pendingActions: "Nothing is waiting for approval.",
        tools: "The agent has no tools registered.",
        models: "No models in the catalog. Add one or restore the seeded catalog.",
        profiles: "No role profiles set. Every role falls back to the global model.",
        providerKeys: "No provider key is stored yet.",
        settings: "No settings in this group.",
        readiness: "Everything on the checklist is done. Start a generate run.",
        usage: "Nothing has been spent yet.",
        depth: "No pages are deep enough to chart.",
    },
    readiness: {
        providerKey: "Store an API key for at least one model provider.",
        profiles: "Point each model role at a model.",
        site: "Add the WordPress site you are working on.",
        plugin: "Install the companion plugin on the site.",
        sync: "Sync the site so Postulator knows what is already published.",
        graph: "Create entities and approve the edges between them.",
        canonicals: "Give every entity a canonical page so it can be linked to.",
        template: "Pick the template a generate run should use.",
    },
    onboarding: {
        title: "Getting ready",
        subtitle: "A generate run writes pages that prove the graph. Every line below has to be true first.",
        panel: "Readiness",
        progress: (done: number, total: number) => `${done} / ${total} done`,
        remaining: (left: number) => (left === 1 ? "1 step left" : `${left} steps left`),
        ready: "Ready to generate",
        blocked: "Add a site before this one can be answered.",
        forSite: (name: string) => `Checked against ${name}.`,
        noSite: "Checked against your model settings only — there is no site yet.",
        recheck: "Check again",
        names: {
            providerKey: "Provider key",
            profiles: "Model roles",
            site: "Site",
            plugin: "Companion plugin",
            sync: "First sync",
            graph: "Entities and edges",
            canonicals: "Canonical pages",
            template: "Template",
        },
        actions: {
            providerKey: "Open model settings",
            profiles: "Assign the roles",
            site: "Add a site",
            plugin: "Open the site",
            sync: "Open the page map",
            graph: "Open the graph",
            canonicals: "Show the entities without a page",
            template: "Open templates",
        },
        done: {
            providerKey: (count: number) => (count === 1 ? "1 provider has a key." : `${count} providers have a key.`),
            profiles: "Writer, editor, linker and judge all point at a model.",
            plugin: (version: string) => (version === "" ? "Installed." : `Installed, version ${version}.`),
            sync: (count: number) => `${count} pages in the map.`,
            syncAt: (when: string) => `Last synced ${when}.`,
            graph: "Entities exist and at least one edge is approved.",
            canonicals: "Every entity points at a canonical page.",
            template: "A template is available to a generate run.",
        },
        todo: {
            profiles: (roles: string) => `Still unassigned: ${roles}.`,
            graphNoEntities: "No entities yet.",
            graphNoEdges: "Entities exist, but no edge is approved yet.",
            canonicals: "At least one entity has no canonical page, so nothing can link to it.",
        },
    },
    sites: {
        title: "Sites",
        subtitle: "Every graph, page map and run below belongs to exactly one WordPress site.",
        add: "Add site",
        addTitle: "Add a site",
        editTitle: "Edit site",
        open: "Open this site",
        edit: "Edit",
        anyStatus: "Any status",
        columns: {
            name: "Name",
            baseUrl: "Base URL",
            status: "Status",
            plugin: "Plugin",
            created: "Added",
        },
        field: {
            name: "Name",
            nameHint: "What you call this site inside Postulator.",
            baseUrl: "Base URL",
            baseUrlHint: "The WordPress home URL, for example https://example.com.",
            username: "WordPress user",
            usernameHint: "The account the application password belongs to.",
            password: "Application password",
            passwordHint: "Generated under Users → Profile in WordPress, not the login password.",
            passwordKeep: "Leave empty to keep the stored password.",
            allowInsecure: "Allow plain http",
            allowInsecureHint: "Credentials travel unencrypted. Only for a local install.",
        },
        insecureWarning: "This site is reached over plain http, so the application password crosses the network unencrypted.",
        test: "Test connection",
        testing: "Testing",
        reach: {
            ok: "The site answered and the credentials work.",
            upgradeRequired: "The site answered on http and asked for https.",
            unauthorized: "The site answered but refused these credentials.",
            unreachable: "The site did not answer.",
        },
        useSuggested: (url: string) => `Use ${url}`,
        detected: (name: string) => `Reported name: ${name}`,
        woo: "WooCommerce detected",
        deleteTitle: "Delete this site",
        deleteBody: (name: string) =>
            `${name} goes, and with it its page map, entities and edges, runs and their artifacts, site templates and link policies, schedules, saved import mappings and agent conversations. Nothing on WordPress is touched.`,
        deleteConfirm: "Delete the site",
        pickSite: "Pick a site on the left to see its plugin state and credentials.",
        plugin: {
            title: "Companion plugin",
            installed: (version: string) => (version === "" ? "Installed" : `Installed, version ${version}`),
            missingTitle: (name: string) => `The companion plugin is not installed on ${name}`,
            missingBody: "Postulator falls back to the plain WordPress REST API. In that mode:",
            losses: [
                "Products and product categories stay invisible to a sync.",
                "SEO meta is read-only — title and description cannot be written back.",
                "relink_neighbors is skipped on every item, so neighbour links are never repaired.",
            ],
            recheck: "Check again",
            download: "Save the plugin zip",
            saved: (path: string) => `Companion plugin written to ${path}`,
            capabilities: "Capabilities",
            seo: "SEO plugin",
            noSeo: "none detected",
            noCapabilities: "none reported",
        },
    },
    runs: {
        title: "Runs",
        subtitle: "Every run writes pages for one site and stops itself at its budget.",
        reconnecting: "Reconnecting to the run log",
        reconnectingBody:
            "Live events are never buffered, so a reload loses the stream while the run carries on. The log below is being refilled from the run itself.",
        logFailed: "The run log could not be read",
        status: {
            pending: "Pending",
            running: "Running",
            waiting: "Waiting",
            paused: "Paused",
            completed: "Completed",
            failed: "Failed",
            cancelled: "Cancelled",
        },
        pauseReason: {
            budget_exceeded: "Paused at the budget cap.",
            awaiting_confirmation: "Paused until you approve the pending action.",
            needs_human: "Paused for a human decision.",
            user: "Paused by you.",
        },
        pauseReasonShort: {
            budget_exceeded: "budget cap",
            awaiting_confirmation: "awaiting approval",
            needs_human: "needs human",
            user: "paused by you",
        },
        unknownPauseReason: "Paused for a reason this build does not recognise.",
        budgetPausedTitle: "This run stopped at its budget cap",
        budgetPausedBody:
            "A run carries the cap it was started with and there is no binding that raises it. Resuming lets the run continue until its next model call and then it pauses again. To finish the work, cancel this run and start a new one over the same pages with a higher cap.",
        pause: "Pause",
        resume: "Resume",
        cancel: "Cancel run",
        cancelTitle: "Cancel this run",
        cancelBody:
            "Every pending, running and waiting item stops. Pages already published stay published; nothing on WordPress is undone.",
        cancelConfirm: "Cancel the run",
        keepRunning: "Keep it running",
        retryStep: "Retry this step",
        retryBusy: "The item has not stopped, so there is nothing to retry.",
        retryBlocked: {
            inputs_expired: "Inputs expired — re-run the page",
        },
        retryBlockedBody:
            "The artifacts this step needs were purged after the page published, and no step regenerates them. Start a fresh run over this page instead.",
        unknownRetryBlock: "Retry is refused for a reason this build does not recognise.",
        rerunPage: "Start a run over this page",
        columns: {
            kind: "Kind",
            status: "Status",
            progress: "Items",
            spend: "Spent",
            started: "Started",
            finished: "Finished",
            created: "Created",
            path: "Path",
            step: "Step",
            attempts: "Try",
            error: "Error",
            updated: "Updated",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            status: "Status",
            anyStatus: "Any status",
            kind: "Kind",
            anyKind: "Any kind",
            itemStatus: "Items",
            anyItemStatus: "All items",
        },
        loading: "Loading the run list",
        loadingItems: "Loading the run items",
        loadMore: "Load more",
        noMatch: "No run matches these filters",
        noMatchBody: "Widen the filters or reset them to see every run of this site.",
        noItemMatch: "No item of this run has that status.",
        openRun: "Open this run",
        backToRuns: "Runs",
        notFound: "This run is no longer here.",
        detail: {
            header: (kind: string) => `${kind} run`,
            startedBy: (actor: string) => `started by ${actor}`,
            publishMode: (mode: string) => `publish mode: ${mode}`,
            deadline: "Deadline",
            template: (id: string, version: number) => `template ${id} v${version}`,
            noTemplate: "no template recorded",
            targets: (count: number) => (count === 1 ? "1 target page" : `${count} target pages`),
            items: (done: number, total: number) => `${done} / ${total} items`,
            done: "completed",
            failed: "failed",
            needsHuman: "need a human",
            running: "running",
            pending: "pending",
            spent: "Spent",
            spentOf: (spent: string, cap: string) => `${spent} of ${cap}`,
            noCap: "No cap was set for this run",
            noCapBody:
                "A run with no dollar cap never stops itself on spend. Cancel it if the bill matters, and give the next run a cap.",
            hardStop: "A run pauses itself at the cap; it never overruns it.",
            tokens: "Tokens",
            tokensBody: "Tokens are reported, not capped — the run stops on dollars.",
            calls: (count: number) => (count === 1 ? "1 model call" : `${count} model calls`),
            liveStats: "Counted from the run log while the run is live.",
            rowStats: "Counted from the finished run.",
            failure: "The run failed",
        },
        events: {
            title: "Events",
            live: "live",
            catchingUp: "catching up",
            settled: "log complete",
            filterItem: "This item only",
            filterAll: "Whole run",
            names: {
                "run.queued": "Run queued",
                "run.started": "Run started",
                "run.paused": "Run paused",
                "run.resumed": "Run resumed",
                "run.cancelled": "Run cancelled",
                "run.completed": "Run completed",
                "run.failed": "Run failed",
                "run.budget_exceeded": "Budget cap reached",
                "item.started": "Item started",
                "item.done": "Item done",
                "item.failed": "Item failed",
                "item.needs_human": "Item needs a human",
                "step.started": "Step started",
                "step.done": "Step done",
                "step.failed": "Step failed",
                "step.retrying": "Step retrying",
                "llm.usage": "Model call",
            },
            attempt: (attempt: number) => `attempt ${attempt}`,
            retryIn: (delay: string) => `retrying in ${delay}`,
            seq: (seq: number) => `#${seq}`,
        },
        step: {
            position: (at: number, total: number, name: string) => `step ${at} of ${total} — ${name}`,
            unknownRecipe: (name: string) => `step ${name}`,
            noStep: "no step recorded yet",
            waitingUntil: (left: string) => `waiting ${left}`,
            retrying: (attempt: number, left: string) => `retrying, attempt ${attempt} in ${left}`,
            recipe: (first: string, last: string, total: number) => `${total} steps · ${first} → ${last}`,
            noPercent: "There is no progress inside a step — only which step the item is on.",
        },
        start: {
            open: "Start run",
            title: "Start a run",
            body: "A run writes pages for the selected targets and stops itself at the dollar cap you set here.",
            pages: "Target pages",
            pagesHint: "Every selected page becomes one item of the run.",
            selected: (count: number) => (count === 1 ? "1 page selected" : `${count} pages selected`),
            noPages: "Select at least one page.",
            search: "Path prefix",
            publishMode: "Publish mode",
            kind: "Kind",
            template: "Template",
            templateAuto: "Resolved per page",
            templateHint: "Left automatic, each page uses the template its own overrides resolve to.",
            cap: "Dollar cap",
            capHint: "The run pauses itself once spend passes this. Zero means no cap at all.",
            capZero: "With no cap this run will not stop itself on spend.",
            estimate: "Price this run",
            estimating: "Pricing",
            estimated: (usd: string, tokens: string) => `${usd} · about ${tokens} tokens`,
            estimateHint: "Priced without enqueuing anything.",
            estimateFirst: "Price the run before starting it.",
            overCap: "The estimate is above the cap, so this run will pause before it finishes.",
            confirm: "Start the run",
            cancel: "Cancel",
            started: "Run started",
        },
        review: {
            title: "Review",
            close: "Close",
            item: (path: string) => path,
            attempt: (attempts: number) => (attempts === 1 ? "attempt 1" : `${attempts} attempts`),
            noArtifacts: "Nothing to review yet",
            noArtifactsBody:
                "This item has produced no artifact so far. Each step writes its own, and they appear as the run reaches them.",
            loading: "Loading the artifacts of this item",
            unreadable: "This artifact could not be read",
            unreadableBody: "It is not in the shape this build expects, so nothing is shown rather than something wrong.",
            purged: "Removed by the retention sweep",
            purgedBody: (days: number) =>
                `Bodies, drafts and images are dropped ${days} days after the page publishes. The row stays, and the compliance findings and the judge score below are untouched.`,
            purgedBodyUnknown:
                "Bodies, drafts and images are dropped once the retention window passes on a published page. The row stays, and the compliance findings and the judge score below are untouched.",
            noDiff: "There is no comparison with the live page — raw WordPress content is not exposed by any binding.",
            kinds: {
                link_context: "Targets",
                draft: "Draft",
                body_html: "Body",
                meta: "Meta",
                images: "Images",
                validation_report: "Links & compliance",
                judge_report: "Judge",
                publish_result: "Publish",
                relink_result: "Neighbours",
                sync_result: "Sync",
                final_report: "Report",
            },
            body: {
                preview: "Sandboxed preview",
                isolated: "Rendered in an isolated frame with no scripts and no access to this window.",
                empty: "The body artifact is empty.",
            },
            links: {
                owed: "Owed to the graph",
                owedEmpty: "The graph asked this page for no links.",
                satisfied: "satisfied",
                missing: "missing",
                required: "required",
                optional: "optional",
                relation: { up: "up", down: "down", sibling: "sideways" },
                actual: "Links on the page",
                actualEmpty: "No link was recorded on this page.",
                classes: {
                    graph: "graph",
                    self: "self",
                    external: "external",
                    unknown_internal: "unknown internal",
                },
                classesNote:
                    "Graph links come from the placements the run made; the rest are the links compliance flagged, so a clean non-graph link leaves no record.",
                findings: "Findings",
                errors: (count: number) => (count === 1 ? "1 error — the item fails" : `${count} errors — the item fails`),
                warnings: (count: number) => (count === 1 ? "1 warning" : `${count} warnings`),
                clean: "No compliance finding on this page.",
                warningsDoNotFail: "A warning does not fail the item; an error does.",
                score: (score: number) => `score ${score.toFixed(2)}`,
            },
            judge: {
                score: "Score",
                outOf: "out of 1.00",
                issues: "Issues",
                suggestions: "Suggestions",
                none: "The judge raised nothing.",
                rejudge: "Judge this page again",
                rejudging: "Judging",
                rejudgeHint: "This calls the judge model and spends tokens. It never runs on its own.",
                rejudged: (tokens: number) => `Judged again for ${tokens} tokens.`,
                unavailable: "The judge did not return a score for this item.",
            },
            publish: {
                result: "Result",
                created: "created",
                updated: "updated",
                status: "WordPress status",
                wpId: "WordPress id",
                hash: "Content hash",
                seoApplied: "SEO fields written",
                skipped: "Skipped",
                liveUrl: "Live URL",
                none: "This item has not published.",
            },
            draft: { sections: "Sections", summary: "Summary" },
            meta: { characters: (count: number) => `${count} characters` },
            images: { featured: "Featured image", skipped: "Skipped", none: "No image was placed." },
            relink: {
                linked: "linked",
                conflicts: "conflicts",
                skipped: "skipped",
                neighbours: "Neighbours",
                none: "No neighbour was touched.",
            },
            sync: { none: "Nothing was read back for this item." },
            report: {
                score: "Final score",
                errors: "errors",
                warnings: "warnings",
                none: "This item produced no final report.",
            },
        },
    },
    agent: {
        title: "Agent",
        subtitle: "The agent can do everything this app can. Every write stops and asks, in plain words.",
        send: "Send",
        cancelTurn: "Stop",
        thinking: "Working",
        confirmTitle: "Approve this action",
        approve: "Approve",
        reject: "Reject",
        autonomous: "Autonomous mode runs write and dangerous tools without asking.",
        confirmMode: "Confirm mode asks before every write.",
        turnStalled: "The turn stopped reporting. The saved messages are shown instead.",
        untitled: "Untitled conversation",
        you: "You",
        assistant: "Assistant",
        composer: {
            placeholder: "Ask the agent to change something…",
            firstPlaceholder: "Ask something. Your first message starts a conversation on this site.",
            hint: "Enter sends · Shift+Enter breaks the line",
            answering: "The agent is answering. Stop it to ask something else.",
            noModel: "No chat model is set. Point the chat role at a model in the settings first.",
        },
        header: {
            rename: "Rename",
            renameTitle: "Conversation title",
            noSite: "No site",
            everywhere: "Everywhere",
            modeConfirm: "Confirm",
            modeAutonomous: "Autonomous",
            modeSwitch: "Runs without asking",
            spend: (usd: string, calls: number) => `${usd} · ${calls === 1 ? "1 call" : `${calls} calls`}`,
            noSpend: "Nothing spent yet",
            modelUnset: "Chat model not set",
            tools: (count: number) => (count === 1 ? "1 tool" : `${count} tools`),
            openFull: "Open as a page",
            backToDock: "Back to the dock",
            switchConversation: "Switch conversation",
            newConversation: "New conversation",
            recent: "Recent on this site",
            recentEverywhere: "Recent",
            more: "All conversations",
        },
        autonomousTitle: "Autonomous. Writes happen without asking.",
        autonomousBody:
            "Every tool runs as soon as the agent calls it, deletions and imports included. Switch back to confirm mode to be asked first.",
        autonomousDialog: {
            title: "Run without asking?",
            body: "In autonomous mode the agent writes to the graph, the pages, the templates and the site as soon as it decides to. You will see what it did, not approve it first.",
            confirm: "Run without asking",
            cancel: "Keep asking me",
        },
        transcript: {
            jumpToLatest: "Jump to the latest",
            usage: (input: string, output: string, usd: string) => `${input} in · ${output} out · ${usd}`,
            tool: {
                running: "running",
                ok: "done",
                error: "failed",
                denied: "refused",
                showResult: "Show what it answered",
                hideResult: "Hide",
                duration: (ms: number) => (ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(1)} s`),
            },
        },
        states: {
            cancelledTitle: "Turn stopped",
            cancelledBody: "You stopped the agent mid-answer. Nothing more was written.",
            errorTitle: "The turn failed",
            stalledTitle: "The agent stopped reporting",
            retry: "Ask again",
            start: "Ask something to begin.",
            startBody: "Try: how many pages carry no entity, or: plan the missing pages under an entity.",
            loading: "Loading the conversation",
        },
        card: {
            kickerWrite: "Needs your approval",
            kickerDangerous: "Dangerous. Needs your approval",
            riskWrite: "Write",
            riskDangerous: "Dangerous",
            dangerousWarn: "This cannot be undone from Postulator.",
            hints: "Ctrl+Enter approves · Esc rejects",
            approving: "Approving",
            rejecting: "Rejecting",
            executed: "Approved and done",
            executedWith: (summary: string) => `Approved and done: ${summary}`,
            approved: "Approved, running",
            rejected: "Rejected",
            failed: (reason: string) => `Failed: ${reason}`,
            requested: (when: string) => `Asked ${when}`,
            tool: (name: string) => `Tool ${name}`,
            unknownRef: "no longer here",
        },
        inbox: {
            title: "Inbox",
            subtitle: "What the agent proposed and is waiting on. Kept on disk, so it survives closing the app.",
            waiting: (count: number) =>
                count === 1 ? "1 action is waiting for your decision" : `${count} actions are waiting for your decision`,
            waitingBody: "Read-only tools never appear here; they run at once. Every write and every deletion waits.",
            rejectAll: "Reject all",
            rejectAllTitle: "Reject every pending action?",
            rejectAllBody: (count: number) =>
                `${count === 1 ? "The one action" : `All ${count} actions`} shown here will be rejected. The agent learns that on its next turn.`,
            rejectAllConfirm: "Reject them",
            cancel: "Cancel",
            keys: "j / k move · a approve · r reject · Enter opens the conversation",
            tabs: {
                pending: "Waiting",
                executed: "Done",
                rejected: "Rejected",
                failed: "Failed",
            },
            openConversation: "Open the conversation",
            deletedConversation: "A conversation that was deleted",
            nothingDone: "Nothing has been approved yet.",
            nothingRejected: "Nothing has been rejected.",
            nothingFailed: "No approved action has failed.",
        },
        screen: {
            conversations: "Conversations",
            search: "Search conversations",
            noMatch: "No conversation matches.",
            groupEverywhere: "Everywhere",
            deleteTitle: "Delete this conversation?",
            deleteBody: "Its messages, its pending actions and its history go with it. A turn in flight is stopped.",
            deleteConfirm: "Delete it",
            cancel: "Cancel",
            delete: "Delete",
            newTitle: "New conversation",
            newSite: "Site",
            newEverywhere: "No site. The agent can only read the list of sites and create one.",
            newStart: "Start",
            pendingCount: (count: number) => (count === 1 ? "1 waiting" : `${count} waiting`),
            awaiting: (count: number) => (count === 1 ? "1 awaiting approval" : `${count} awaiting approval`),
        },
        tools: {
            title: "What the agent can do",
            subtitle: (count: number) => `${count} tools, each one a thing this app can do.`,
            search: "Search tools",
            noMatch: "No tool matches.",
            read: "Read",
            write: "Write",
            dangerous: "Dangerous",
            readBody: "Runs at once, changes nothing.",
            writeBody: "Asks first in confirm mode.",
            dangerousBody: "Asks first in confirm mode and reads differently, because it cannot be undone.",
        },
        families: {
            sites: "Sites",
            graph: "Graph",
            pages: "Pages",
            templates: "Templates",
            policies: "Link policies",
            runs: "Runs",
            sync: "Sync",
            reports: "Reports",
            imports: "Import",
            models: "Models",
            content: "Content",
            schedules: "Schedules",
            other: "Other",
        } as Readonly<Record<string, string>>,
        describe: {
            yes: "yes",
            no: "no",
            hidden: "kept hidden",
            more: (count: number) => `and ${count} more`,
            field: (label: string, value: string) => `${label}: ${value}`,
            sites: {
                create: (name: string) => `Register site "${name}"`,
                update: "Update site",
                delete: "Delete site",
                deleteBody: "Its pages, entities, runs, schedules and conversations go with it.",
                address: (url: string) => `Address ${url}`,
                user: (name: string) => `WordPress user ${name}`,
                password: "New application password, kept hidden",
                insecure: "Insecure TLS allowed",
                secure: "Insecure TLS refused",
                status: (status: string) => `Status ${status}`,
                renamed: (name: string) => `Renamed to "${name}"`,
                defaultTemplate: "Default template",
                defaultPolicy: "Default link policy",
            },
            graph: {
                create: (name: string) => `Create entity "${name}"`,
                update: "Update entity",
                delete: "Delete entity",
                deleteBody: "Its pages keep their content and lose their entity. Its edges go.",
                kind: (kind: string) => `Kind ${kind}`,
                intent: (intent: string) => `Intent ${intent}`,
                primary: (keyword: string) => `Primary keyword "${keyword}"`,
                secondary: (keywords: string) => `Also targets ${keywords}`,
                renamed: (name: string) => `Renamed to "${name}"`,
                anchorsCount: (count: number) => (count === 1 ? "1 anchor" : `${count} anchors`),
                anchor: (text: string, weight: string, source: string) => `"${text}" · ${weight} · ${source}`,
                setAnchors: "Set the anchors of",
                connect: "Connect",
                under: "under",
                with: "with",
                weight: (weight: string) => `Weight ${weight}`,
                approve: "Approve the edge",
                reject: "Reject the edge",
                deleteEdge: "Delete the edge",
                recompute: "Recompute the entity scores",
                recomputeBody: "Every score is recalculated from the approved edges. Nothing else changes.",
                proposeFromPages: "Propose entities and edges from the pages",
                proposeBody: "One model call per forty unmapped pages. Nothing is approved on its own.",
                proposeRelated: "Propose related edges",
                proposeAround: "Only pairs that involve",
            },
            pages: {
                create: (path: string) => `Plan page ${path}`,
                update: "Update page",
                delete: "Delete page",
                deleteBody: "The row leaves the map. The page on WordPress is not touched.",
                map: "Map",
                to: "to",
                unmap: "Take the entity off",
                canonical: "Make",
                canonicalOf: "the canonical page of",
                replaceLinks: "Replace the links of",
                linksCount: (count: number) => (count === 1 ? "1 link" : `${count} links`),
                link: (anchor: string) => `"${anchor}" →`,
                title: (title: string) => `Title "${title}"`,
                h1: (h1: string) => `H1 "${h1}"`,
                path: (path: string) => `Path ${path}`,
                wpType: (kind: string) => `WordPress type ${kind}`,
                status: (status: string) => `Status ${status}`,
                metaTitle: (title: string) => `Meta title "${title}"`,
                metaDescription: (text: string) => `Meta description "${text}"`,
                canonicalUrl: (url: string) => `Canonical ${url}`,
                entity: "Entity",
                template: "Template",
            },
            templates: {
                create: (name: string) => `Create template "${name}"`,
                update: "Update template",
                delete: "Delete template",
                deleteBody: "Pages that used it fall back to the site default. Its overrides go.",
                override: "Override",
                forSite: "for the site",
                forPage: "for the page",
                deleteOverride: "Remove a template override",
                pageKind: (kind: string) => `Page kind ${kind}`,
                scopeSite: "Only on the site",
                scopeGlobal: "Available on every site",
                renamed: (name: string) => `Renamed to "${name}"`,
                replaces: "Replaces the whole specification",
                unreadableSpec: "The specification could not be read.",
                nothingChanges: "Nothing in the specification changes.",
            },
            policies: {
                create: (name: string) => `Create link policy "${name}"`,
                update: "Update link policy",
                delete: "Delete link policy",
                renamed: (name: string) => `Renamed to "${name}"`,
                maxLinks: (count: number) => `At most ${count} links per page`,
                perTarget: (count: number) => `At most ${count} per target`,
                upDepth: (levels: number) => `Links up ${levels} ${levels === 1 ? "level" : "levels"}`,
                down: "Links down to the children",
                noDown: "No links down",
                siblings: (weight: string) => `Sideways from weight ${weight}`,
                childrenSection: "A children section at the end",
                noChildrenSection: "No children section",
                forbidExternal: "External links forbidden",
                allowExternal: "External links allowed",
                forbidSelf: "Self links forbidden",
                allowSelf: "Self links allowed",
                anchors: (strategy: string) => `Anchors: ${strategy}`,
            },
            runs: {
                start: (kind: string, count: number) => `Start a ${kind} run over ${count === 1 ? "1 page" : `${count} pages`}`,
                pages: "Pages",
                template: "Template",
                templateDefault: "Template: each page's own",
                steps: (steps: string) => `Steps ${steps}`,
                stepsDefault: "Steps: the template recipe",
                publishes: "Publishes the pages live on WordPress",
                drafts: "Writes drafts, nothing goes live",
                budget: (usd: string) => `Budget ${usd}`,
                tokens: (count: string) => `${count} tokens at most`,
                noBudget: "No budget cap",
                pause: "Pause the run",
                resume: "Resume the run",
                cancel: "Cancel the run",
                cancelBody: "Items already published stay published.",
                reason: (reason: string) => `Reason: ${reason}`,
                retry: "Retry the current step of the item",
            },
            sync: {
                site: "Pull the site's live content into the page map",
                body: "Rows are updated from WordPress. Nothing on WordPress changes.",
            },
            imports: {
                apply: (file: string) => `Import ${file} into the site`,
                applyBody: "One transaction: every row lands or none does.",
                file: (path: string) => `File ${path}`,
                columns: (count: number) => (count === 1 ? "1 column mapped" : `${count} columns mapped`),
                column: (field: string, column: string) => `${field} ← ${column}`,
                option: (name: string, value: string) => `${name} "${value}"`,
                saveAs: (name: string) => `Saved as the mapping "${name}"`,
                export: (path: string) => `Export the site to ${path}`,
                saveMapping: (name: string) => `Save the column mapping "${name}"`,
                deleteMapping: "Delete the column mapping",
            },
            models: {
                upsert: (ref: string) => `Add or update the model ${ref}`,
                disable: (ref: string) => `Disable the model ${ref}`,
                setProfile: (role: string, ref: string) => `Point the ${role} role at ${ref}`,
                setKey: (provider: string) => `Store the ${provider} API key`,
                setKeyBody: "The key is stored encrypted and never shown again.",
                test: (ref: string) => `Test ${ref}`,
                testBody: "One small paid call to the provider.",
                context: (count: string) => `Context ${count} tokens`,
                output: (count: string) => `Output up to ${count} tokens`,
                prices: (input: string, output: string) => `${input} in, ${output} out per million`,
                limits: (rpm: number, tpm: string) => `${rpm} requests and ${tpm} tokens per minute`,
                structured: "Structured output",
                images: "Images",
                reasoning: "Reasoning",
            },
            content: {
                judge: "Judge the live page",
                body: "One priced model call over what WordPress serves right now.",
            },
            schedules: {
                create: (name: string) => `Create schedule "${name}"`,
                update: "Update schedule",
                delete: "Delete schedule",
                enable: "Enable the schedule",
                disable: "Disable the schedule",
                runNow: "Run the schedule now",
                renamed: (name: string) => `Renamed to "${name}"`,
                cron: (cron: string) => `On the cron ${cron}`,
                every: (minutes: number) => `Every ${minutes} ${minutes === 1 ? "minute" : "minutes"}`,
                entity: "Only the pages of",
                status: (status: string) => `Only ${status} pages`,
                limit: (count: number) => `At most ${count} pages a run`,
                template: "Template",
                enabled: "Enabled at once",
                paused: "Created paused",
            },
        },
        askAbout: "Ask the agent about this",
        ask: {
            entity: (name: string, id: string) => `Entity "${name}" (id ${id}). `,
            page: (path: string, id: string) => `Page ${path} (id ${id}). `,
            template: (name: string, id: string) => `Template "${name}" (id ${id}). `,
            newTemplate: "Create a template for this site. ",
            runItem: (path: string, runId: string, itemId: string) =>
                `Run item for ${path} (run ${runId}, item ${itemId}). `,
        },
    },
    pages: {
        views: { table: "Table", tree: "Tree" },
        preview: {
            panel: "On the site",
            title: (path: string) => `How ${path} looks on the site`,
            open: "View on the site",
            openDraft: "Preview the draft",
            fromReview: "Preview on the site",
            openInBrowser: "Open in your browser",
            openAnyway: "Open in your browser anyway",
            newLink: "New link",
            close: "Close",
            public: "Public page",
            draft: "Draft preview",
            expiresIn: (minutes: number) => (minutes <= 1 ? "link expires in a minute" : `link expires in ${minutes} min`),
            expired: "This link has expired. Ask for a new one.",
            loading: "Loading the page from the site",
            embedHint: "If the site refuses to be shown inside the app, open it in your browser.",
            publicBody: "The page is published, so this is its public address.",
            draftBody: "The draft is shown through the site's theme with a private link that works for an hour and is hidden from search engines.",
            notOnSite: "Not on the site yet",
            notOnSiteBody: "A generate run writes this page to WordPress. Preview it once it is there.",
            archived: "No longer on the site",
            archivedBody: "This page was removed from WordPress.",
            needsPlugin: "Install the companion plugin to preview drafts",
            needsPluginBody:
                "Without the plugin WordPress shows a draft only to a logged-in editor. Published pages still open by their address.",
            outdatedPlugin: "Update the companion plugin to preview drafts",
            outdatedPluginBody: "The plugin on this site predates draft previews. Version 1.1.0 or later issues them.",
            viewports: { desktop: "Desktop", tablet: "Tablet", phone: "Phone" },
            viewport: "Preview width",
        },
        columns: {
            path: "Path",
            title: "Title",
            wpType: "WP type",
            status: "Status",
            entity: "Entity",
            drift: "Drift",
            synced: "Synced",
            created: "Created",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            pathPrefix: "Path prefix",
            pathPrefixHint: "Matches the start of a path, such as /collections/.",
            status: "Status",
            anyStatus: "Any status",
            entity: "Entity",
            anyEntity: "Any entity",
            unmapped: "No entity attached",
            noEntities: "This site has no entities yet.",
            partialEntities: "More entities exist than were loaded, so some rows read as mapped without a name.",
        },
        siteTotal: (total: number) => `${total} pages`,
        loadMore: "Load more",
        loading: "Loading the page map",
        noMatch: "No page matches these filters",
        noMatchBody: "Widen the filters or reset them to see the whole map.",
        plan: "Plan a page",
        untitled: "Untitled",
        mapped: "mapped",
        unmapped: "no entity",
        empty: { title: "The page map is empty" },
        drift: {
            badge: "drift",
            title: "Someone edited this page in WordPress",
            body: "WordPress reports a change made after Postulator last wrote this page. What changed cannot be shown: raw WordPress content never crosses into the app, so there is nothing here to compare against.",
            decision:
                "A publish run started with refuseDrift pauses this page for a human instead of overwriting the edit. Without it the run overwrites the page and records a drift finding on the publish result.",
            lastWritten: "Last synced",
            wpModified: "WordPress modified",
        },
        tree: {
            title: "Page tree",
            noFilters: "The tree takes a site and nothing else, so the filters apply to the table only.",
            unbounded:
                "The tree call returns every page on the site in one uncursored response. There is no limit and no cursor.",
            guard: (total: number) =>
                `This site has ${total} pages, and loading them all in one response would block the window.`,
            unknownSize: "The size of this site is not known, so the tree was not fetched automatically.",
            useTable: "Use the table instead",
            loadAnyway: "Load the whole tree anyway",
            load: "Load the tree",
            nodes: (count: number) => `${count} pages in the tree`,
            children: (count: number) => `${count} below`,
            expandAll: "Expand all",
            collapseAll: "Collapse all",
            showMore: (hidden: number) => `Show ${hidden} more`,
        },
        detail: {
            close: "Close",
            notFound: "This page is no longer in the map.",
            template: "Template",
            templateOwn: "Chosen for this page",
            templateDefault: "Site default",
            templateNone: "No template. The site has no default and this page names none, so a run cannot write it.",
            templateVersion: (name: string, version: number) => `${name} · v${version}`,
            templateDefaultOption: "Site default",
            templateSave: "Use it",
            templateCustomize: "Customize for this page",
            templateOpen: "Open the template",
            templateEdit: "Edit",
            entity: "Entity",
            entityMissing: "The entity this page points at could not be read.",
            entityMeta: (kind: string, score: number) => `${kind} · score ${score.toFixed(2)}`,
            noEntity: "Not mapped to an entity",
            noEntityBody: "A page outside the graph is never a link target, so generation cannot link to it.",
            noEntityOption: "No entity",
            map: "Map",
            change: "Change",
            unmap: "Unmap",
            canonical: "canonical",
            canonicalTitle: "Canonical pages are what the graph links to",
            canonicalBody:
                "An entity with no canonical page is never a link target, so generation cannot link to it. Mapping a page to an entity does not make it canonical.",
            makeCanonical: "Make this the canonical page",
            canonicalIsHere: "This page is the canonical page for its entity.",
            canonicalElsewhere: "Another page is canonical for this entity.",
            canonicalMissing: "This entity has no canonical page, so nothing can link to it.",
            openCanonical: "Open the canonical page",
            meta: "Meta",
            path: "Path",
            pathHint: "Normalised on save: lower case, a leading and a trailing slash, no query and no fragment.",
            title: "Title",
            h1: "H1",
            metaTitle: "Meta title",
            metaDescription: "Meta description",
            canonicalUrl: "Canonical URL",
            wpType: "WP type",
            status: "Status",
            characters: (count: number) => `${count} characters`,
            save: "Save",
            revert: "Revert",
            links: "Outgoing links",
            linksSummary: (total: number, generated: number) => `${total} links · ${generated} written by a run`,
            report: "Last report",
            noReport: "No run has touched this page yet",
            noReportBody: "Send this page through a generate run and its report lands here.",
            openRun: "Open the run item",
            judge: (score: number) => `judge ${score.toFixed(0)}`,
            validation: (score: number) => `validation ${score.toFixed(0)}`,
            publishedAs: (status: string) => `published as ${status}`,
            liveUrl: "Live URL",
            deletePage: "Delete",
            deleteTitle: "Delete this page?",
            deleteBody: "The row leaves the page map. Nothing on the WordPress site is touched.",
            deleteConfirm: "Delete",
            cancel: "Cancel",
        },
        create: {
            title: "Plan a page",
            body: "A planned page is a row in the map. It does not exist on WordPress until a run publishes it.",
            confirm: "Plan it",
            cancel: "Cancel",
            noEntity: "No entity",
            entityHint: "A page with no entity is not part of the graph and is never a link target.",
        },
        conflict: {
            title: "This would cannibalise another page",
            body: "Two pages cannot compete for the same target, so nothing was written.",
            reason: {
                path_conflict: "already takes that path",
                same_entity_canonical: "is already the canonical page for that entity",
                same_primary_keyword: "already targets that primary keyword",
            },
            unknownReason: "conflicts with this page",
            descendantsTitle: "The path cannot change",
            descendants: (count: number) =>
                `${count} pages sit beneath this one, so its path is fixed. Move or delete them first.`,
        },
    },
    graph: {
        views: { map: "Map", outline: "Outline" },
        label: "Entity graph",
        loading: "Loading the graph",
        total: (total: number) => (total === 1 ? "1 entity" : `${total} entities`),
        search: {
            label: "Find an entity",
            placeholder: "Find an entity",
            noHits: "Nothing matches",
            field: { name: "name", primaryKeyword: "keyword", secondaryKeyword: "secondary keyword" },
        },
        lens: {
            all: "All",
            noPage: "No page",
            proposed: "Proposed",
            orphan: "Orphans",
            ai: "From AI",
            kinds: "Kinds",
            anyKind: "Every kind",
            isolate: "Isolate",
            isolateHint: "Hide everything the lens does not match and keep the path to each match.",
            proof: "Link proof",
            proofHint: "Colour every entity by whether its page carries the links the graph asks for.",
            proofLoading: "Auditing the links",
            hint: {
                all: "Every entity of the site.",
                noPage: "Entities without a canonical page. Nothing can link to them until they get one.",
                proposed: "Entities touched by an edge that still waits for a decision.",
                orphan: "Entities that are not hubs and have no approved parent.",
                ai: "Entities the model proposed. Review their names, keywords and anchors.",
            },
        },
        controls: {
            zoomIn: "Zoom in",
            zoomOut: "Zoom out",
            fit: "Fit the whole map",
            expandAll: "Expand every subtree",
            collapseToRoots: "Collapse to the roots",
            showRelated: "Show every related link",
            hideRelated: "Show related links for the selection only",
            legend: "Legend",
            minimap: "Minimap",
            zoom: (percent: number) => `${percent}%`,
        },
        legend: {
            title: "Legend",
            kinds: "Kinds",
            nodes: "Nodes",
            edges: "Edges",
            noPage: "No canonical page, cannot be linked to",
            proposedPlacement: "Placed under a proposed parent",
            collapsed: "Collapsed subtree with its count",
            selected: "Selected",
            parent: "Parent",
            related: "Related, approved",
            relatedProposed: "Related, proposed",
            extraParent: "A second parent",
            proposedBadge: "Proposed edges waiting on it",
            order: "Children are ordered by score, strongest first.",
            proof: "Link proof",
            proofOk: "Every link the graph asks for is in place",
            proofWarn: "An optional link is missing",
            proofDanger: "A required link is missing or a target has no page",
            proofMuted: "Not audited, no page or no template",
        },
        node: {
            more: (shown: number, hidden: number) => `${shown} shown, ${hidden} more`,
            showMore: (count: number) => `Show ${count} more`,
            showAll: "Show all",
            noPage: "no page",
            proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
            parents: (count: number) => `${count} parents`,
        },
        empty: {
            title: "The graph is empty",
            body: "Nothing gets linked until entities exist and their edges are approved.",
            propose: "Propose from pages",
            add: "Add an entity",
            import: "Import a sheet",
        },
        summary: {
            title: "This site",
            hint: "Pick an entity on the map to read and edit it.",
            byKind: "By kind",
            attention: "Needs attention",
            noPage: (count: number) => (count === 1 ? "1 entity has no page" : `${count} entities have no page`),
            orphan: (count: number) => (count === 1 ? "1 orphan" : `${count} orphans`),
            proposed: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
            multiParent: (count: number) => (count === 1 ? "1 entity with two parents" : `${count} entities with several parents`),
            clean: "Every entity has a page, a parent and no edge waiting.",
            top: "Highest scores",
            keys: "Keys",
            keyRows: [
                ["Arrows", "move through the map"],
                ["Space", "fold or unfold a subtree"],
                ["Ctrl F", "find an entity"],
                ["F", "fit the map"],
                ["Esc", "clear the selection"],
            ],
        },
        inspector: {
            title: "Entity",
            close: "Close the inspector",
            kind: "Kind",
            intent: "Intent",
            primaryKeyword: "Primary keyword",
            secondaryKeywords: "Secondary keywords",
            anchors: "Anchors",
            anchorsHint: "The link texts another page may use to point here.",
            noAnchors: "No anchors. The entity name is used instead.",
            score: "Score",
            rank: (rank: number, total: number) => `rank ${rank} of ${total}`,
            source: "Source",
            page: "Canonical page",
            openPage: "Open the canonical page",
            noPage: "No canonical page",
            noPageBody: "Nothing can link to this entity until a page is canonical for it.",
            relations: "Relations",
            parents: "Parents",
            children: "Children",
            related: "Related",
            proposedParent: "proposed parent",
            showInMap: "Show in the map",
            moreChildren: (count: number) => `${count} more in the map`,
            noRelations: "No edges yet.",
            created: "Created",
            links: "Links",
            linksOpen: "Open in Links",
            linksRow: (satisfied: number, targets: number) => `${satisfied} of ${targets} in place`,
            linksMissing: (missing: number, required: number) =>
                required > 0 ? `${missing} missing, ${required} required` : `${missing} missing`,
            linksBlocked: (count: number) => `${count} blocked`,
            linksOff: "Turn on the link proof to see how its pages link.",
        },
        form: {
            name: "Name",
            kind: "Kind",
            intent: "Intent",
            intentHint: "What a reader wants from this entity's page, in one sentence.",
            primaryKeyword: "Primary keyword",
            secondaryKeywords: "Secondary keywords",
            keywordsHint: "Enter adds one. Four is plenty.",
            remove: "Remove",
            save: "Save",
            discard: "Discard",
        },
        anchorsForm: {
            text: "Anchor text",
            weight: "Weight",
            add: "Add an anchor",
            remove: "Remove the anchor",
            save: "Save the anchors",
            hint: "A weight closer to 1 is preferred when a page links here.",
            duplicate: "That anchor is already listed.",
        },
        pageForm: {
            open: "Open the page",
            drift: "edited in WordPress",
            mapped: "Pages mapped to this entity",
            makeCanonical: "Make it canonical",
            none: "No page is mapped to this entity yet.",
            find: "Find an unmapped page by path",
            noMatch: "No unmapped page matches that path.",
            partial: "More unmapped pages exist. Narrow the path to find one.",
            map: "Map it and make it canonical",
            plan: "Plan a page",
        },
        create: {
            title: "New entity",
            under: (name: string) => `New entity under ${name}`,
            parent: "Parent",
            noParent: "No parent. It becomes a root.",
            anchors: "Anchors",
            anchorsHint: "Enter adds one. The name is used when this is empty.",
            submit: "Create the entity",
            cancel: "Cancel",
            created: (name: string) => `${name} created`,
            attachFailed: (name: string) => `${name} was created but could not be attached to its parent`,
        },
        connect: {
            start: "Connect",
            stop: "Stop connecting",
            picking: (name: string) => `Connecting ${name}. Pick the other entity on the map or in the outline.`,
            title: (from: string, to: string) => `Connect ${from} and ${to}`,
            close: "Close",
            parentOf: (child: string, parent: string) => `${parent} becomes the parent of ${child}`,
            related: "Related, no direction",
            weight: "Weight",
            weightHint: "How close they are, from 0 to 1. A sibling below the policy threshold is not linked.",
            submit: "Add the edge",
            cycle: "That parent edge would close a loop",
            cycleBody: "Parent edges must form a tree. Make it a related edge instead, or pick another parent.",
            makeRelated: "Make it related instead",
            self: "An entity cannot connect to itself.",
            added: "Edge added",
        },
        remove: {
            title: (name: string) => `Delete ${name}?`,
            alone: "The entity goes. No edge touches it, and its page stays in the map, unmapped.",
            withEdges: (edges: number) =>
                `The entity goes, and so ${edges === 1 ? "does the 1 edge" : `do the ${edges} edges`} that touch it. Its page stays in the map, unmapped.`,
            confirm: "Delete the entity",
            cancel: "Keep it",
            deleted: (name: string) => `${name} deleted`,
        },
        move: {
            title: (child: string, parent: string) => `Move ${child} under ${parent}?`,
            fromParent: (previous: string) => `Adds the parent edge and removes the one to ${previous}.`,
            fromRoot: "Adds the parent edge. The entity was a root.",
            keepBoth: "Keep the current parent too",
            confirm: "Move it",
            cancel: "Cancel",
            moved: (child: string, parent: string) => `${child} moved under ${parent}`,
            dropHint: "Drop on the new parent. Esc cancels.",
        },
        menu: {
            label: "Entity actions",
            addChild: "Add a child",
            connect: "Connect…",
            fold: "Fold the subtree",
            unfold: "Unfold the subtree",
            center: "Center on it",
            delete: "Delete…",
        },
        edges: {
            approve: "Approve",
            reject: "Reject",
            remove: "Remove the edge",
            reason: "Why",
        },
        ai: {
            menu: "Model",
            menuLabel: "Ask the model",
            fromPages: "Propose entities from the pages",
            related: "Propose related edges",
            relatedFor: (name: string) => `Propose related edges for ${name}`,
            recompute: "Recompute the scores",
            fromPagesTitle: "Propose entities from the pages",
            fromPagesBody: (unmapped: number, calls: number) =>
                unmapped === 0
                    ? "Every page is already mapped to an entity. There is nothing to propose from."
                    : `${unmapped === 1 ? "1 page has" : `${unmapped} pages have`} no entity. The model reads them in batches of 40, so this is ${calls === 1 ? "1 model call" : `about ${calls} model calls`}, one after another, and the window waits for all of them. Each batch is saved as it lands; cancelling keeps what was already proposed.`,
            relatedTitle: "Propose related edges",
            relatedBody: (total: number) =>
                `The model reads all ${total} entities in one call and suggests which pairs belong together. Every suggestion arrives as a proposed edge with a reason, for you to approve or reject.`,
            relatedForBody: (name: string) => `The model reads every entity and suggests which ones belong beside ${name}. Every suggestion arrives as a proposed edge with a reason, for you to approve or reject.`,
            scope: "Scope",
            wholeSite: "The whole site",
            onlySelection: (name: string) => `Only pairs with ${name}`,
            start: "Start",
            cancel: "Cancel",
            running: "Working",
            elapsed: (seconds: number) => `${seconds}s`,
            stop: "Stop and keep what landed",
            cancelled: "Stopped. Whatever had landed is kept.",
            fromPagesDone: (entities: number, edges: number, skipped: number) =>
                `${entities} ${entities === 1 ? "entity" : "entities"} and ${edges} ${edges === 1 ? "edge" : "edges"} proposed${skipped > 0 ? `, ${skipped} skipped` : ""}`,
            relatedDone: (edges: number, skipped: number) =>
                `${edges} related ${edges === 1 ? "edge" : "edges"} proposed${skipped > 0 ? `, ${skipped} skipped` : ""}`,
            tokens: (tokens: number) => `${tokens} tokens`,
            nothingProposed: "The model proposed nothing new.",
            recomputed: (changed: number) => (changed === 0 ? "Scores are unchanged." : `${changed} ${changed === 1 ? "score" : "scores"} changed.`),
            close: "Close",
            review: "Review the proposals",
        },
        queue: {
            open: "Review",
            title: (count: number) => (count === 1 ? "1 proposed edge" : `${count} proposed edges`),
            close: "Close the review",
            emptyTitle: "Nothing to review",
            columns: { from: "From", kind: "Edge", to: "To", confidence: "Confidence", reason: "Why", decision: "Decision" },
            keys: "A approve · R reject · ↑ ↓ move · Enter show",
            parent: "parent",
            related: "related",
            noReason: "No reason recorded",
            threshold: "Threshold",
            approveAbove: (count: number) => `Approve ${count} at or above`,
            rejectBelow: (count: number) => `Reject ${count} below`,
            bulkApproveTitle: (count: number, threshold: number) =>
                `Approve ${count} ${count === 1 ? "edge" : "edges"} at or above ${threshold.toFixed(2)}?`,
            bulkRejectTitle: (count: number, threshold: number) =>
                `Reject ${count} ${count === 1 ? "edge" : "edges"} below ${threshold.toFixed(2)}?`,
            bulkBody: "Each decision is made one at a time. A rejected edge can be proposed again, and an approved one can be removed later.",
            progress: (done: number, total: number) => `${done} of ${total}`,
            confirm: "Go",
            cancel: "Cancel",
            bulkDone: (count: number, decision: "approve" | "reject") => `${count} ${decision === "approve" ? "approved" : "rejected"}`,
            bulkStopped: (done: number, total: number, message: string) => `Stopped after ${done} of ${total}: ${message}`,
        },
        outline: {
            columns: { name: "Entity", kind: "Kind", score: "Score", page: "Page", attention: "Attention" },
            page: "page",
            noPage: "no page",
            fold: "Fold",
            unfold: "Unfold",
            children: (count: number) => `${count} below`,
        },
    },
    links: {
        title: "Links",
        subtitle: "Every mapped page owes links up to its parents, down to its children and sideways to related entities. A relink run writes the missing ones.",
        loading: "Auditing the links",
        policy: (name: string) => `Policy ${name}`,
        forbidExternal: "no external links",
        allowExternal: "external links allowed",
        forbidSelf: "no self links",
        allowSelf: "self links allowed",
        meters: {
            required: "Links the graph asks for",
            targets: (count: number) => (count === 1 ? "1 target" : `${count} targets`),
            satisfied: "in place",
            missingRequired: "required, missing",
            missingOptional: "optional, missing",
            blocked: "blocked, the target has no page",
            audited: "Pages audited",
            ofPages: (audited: number, pages: number) => `${audited} of ${pages}`,
            auditedHint: "Pages mapped to an entity with a template.",
            orphans: "Orphan pages",
            orphansHint: "Nothing links to them.",
            offGraph: "Links outside the graph",
            offGraphHint: "Self, external and unknown internal links on the audited pages.",
        },
        relink: {
            start: (count: number) => (count === 1 ? "Relink 1 page" : `Relink ${count} pages`),
            none: "Nothing to relink",
            capped: (count: number) => `The worst ${count} pages. A run takes at most ${count} targets.`,
            page: "Relink this page",
            hint: "A relink run adds the missing links to the pages that already exist on the site and writes nothing else.",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            show: "Show",
            status: "Status",
            anyStatus: "Any status",
            entity: "Under an entity",
            anyEntity: "Any entity",
            sort: "Order",
            severity: "Worst first",
            path: "By path",
        },
        show: {
            all: "All pages",
            missing: "Missing links",
            missingRequired: "Missing required links",
            blocked: "Blocked targets",
            offGraph: "Links outside the graph",
            orphans: "Orphans",
            skipped: "Not audited",
        },
        columns: {
            path: "Page",
            entity: "Entity",
            links: "Links",
            missing: "Missing",
            blocked: "Blocked",
            offGraph: "Outside",
            inbound: "Inbound",
            status: "Status",
        },
        cell: {
            ofTargets: (satisfied: number, targets: number) => `${satisfied} / ${targets}`,
            required: (count: number) => `${count} required`,
            orphan: "orphan",
            skipped: { unmapped: "no entity", no_template: "no template" } as Readonly<Record<string, string>>,
        },
        empty: {
            title: "No page to audit",
            body: "The audit covers pages mapped to an entity. Map pages in the graph or the page map first.",
            graph: "Open the graph",
            noMatch: "No page matches these filters",
            noMatchBody: "Widen the filters or reset them to see every page.",
        },
        panel: {
            title: "Page links",
            close: "Close the page",
            openPage: "Open the page",
            openEntity: "Open the entity",
            up: "Up, to the parents",
            down: "Down, to the children",
            sibling: "Sideways, to related entities",
            blocked: "Blocked",
            blockedHint: "These targets have no canonical page, so no link can be written to them.",
            givePage: "Give it a page",
            extra: "Links the graph did not ask for",
            satisfied: "in place",
            missing: "missing",
            required: "required",
            anchor: (text: string) => `anchor “${text}”`,
            anchorNotAllowed: "anchor not in the list",
            allowed: (anchors: readonly string[]) => (anchors.length === 0 ? "No anchors listed." : `Allowed: ${anchors.join(", ")}`),
            none: "None",
            rules: (upDepth: number, downLinks: boolean, siblingMinWeight: number) =>
                `up ${upDepth} · down ${downLinks ? "on" : "off"} · sibling weight ≥ ${siblingMinWeight}`,
            skipped: {
                unmapped: "This page has no entity, so the graph asks nothing of it.",
                no_template: "This page has no template, so its link rules cannot be resolved.",
            } as Readonly<Record<string, string>>,
            inbound: (count: number) => (count === 1 ? "1 page links here" : `${count} pages link here`),
            orphan: "Nothing links here",
        },
        classes: { graph: "graph", self: "self", external: "external", unknown_internal: "unknown internal" } as Readonly<Record<string, string>>,
        relations: { up: "up", down: "down", sibling: "sideways" } as Readonly<Record<string, string>>,
    },
    templates: {
        title: "Templates",
        subtitle:
            "A template says what a generated page contains. Ask the agent to write one; this is where you read it and change it.",
        loading: "Loading templates",
        tabs: {
            templates: "Templates",
            policies: "Link policies",
        },
        columns: {
            name: "Name",
            pageKind: "Page kind",
            sections: "Sections",
            words: "Words",
            version: "Version",
            created: "Created",
            links: "Max links",
            anchors: "Anchors",
            forbids: "Forbids",
        },
        groups: {
            global: "Available on every site",
            globalBody: "Changing one of these changes it for every site in this workspace.",
            site: "Only on this site",
            siteBody: "These belong to this site and no other site can use them.",
        },
        scope: {
            global: "Every site",
            site: "This site",
        },
        siteDefault: "Site default",
        siteDefaultHint: "Pages with no template of their own use this one. That choice is made on the site, not here.",
        sectionCount: (count: number) => (count === 1 ? "1 section" : `${count} sections`),
        wordRange: (min: number, max: number) => `${min}–${max}`,
        versionLabel: (version: number) => `v${version}`,
        newTemplate: "New template",
        nothingToCopy: "Nothing to copy from",
        nothingToCopyBody:
            "A new template starts as a copy of one that already exists. Ask the agent to write the first one.",
        askAgent: "Ask the agent",
        noMatch: "No template of that kind",
        noMatchBody: "Clear the page kind filter to see the rest.",
        anyPageKind: "Any page kind",
        blank: {
            firstHeading: "Introduction",
            firstIntent: "Say what the page is about and who it is for.",
        },
        create: {
            title: "New template",
            body: "Start blank with sane rules, or copy a template that already exists. Either way, rename it and change what you need.",
            confirm: "Create it",
            cancel: "Cancel",
            startFrom: "Start from",
            startBlank: "A blank template",
            startBlankHint: "One introduction section, sensible length and link rules, no images. Every step but the image step is on.",
            startCopy: "A copy of",
            copyFrom: "Copy from",
            copyFromHint: "Every section, rule, model and step is copied. Nothing ties the two together afterwards.",
            name: "Name",
            pageKind: "Page kind",
            pageKindHint: "A short label such as hub, product or guide. It is how a page asks for this template.",
            scope: "Available to",
            scopeHint: "Either every site in this workspace, or this site alone.",
        },
        editor: {
            back: "All templates",
            save: "Save",
            revert: "Revert",
            unsaved: "Unsaved changes",
            deleteTemplate: "Delete",
            deleteTitle: "Delete this template?",
            deleteBody:
                "The template goes and its overrides go with it. Pages already generated from it are untouched.",
            deleteConfirm: "Delete",
            cancel: "Cancel",
            notFound: "This template no longer exists.",
            name: "Name",
            pageKind: "Page kind",
            identity: "Name and kind",
            forPage: (path: string) => `for ${path}`,
            makeDefault: "Make it the site default",
            isDefault: "Site default",
            tabs: {
                sections: "Sections",
                content: "Content",
                links: "Links",
                meta: "Meta and images",
                models: "Models",
                recipe: "Recipe",
            },
            aside: {
                preview: "Preview",
                overrides: "Overrides",
            },
        },
        preview: {
            title: "How a page from this template is built",
            tab: "Browser tab",
            description: (max: number) => `Meta description, up to ${max} characters`,
            h1: "H1",
            keyword: "primary keyword",
            featured: "Featured image",
            inline: "Inline image",
            words: (count: number) => `≈ ${count} words`,
            required: "required",
            optional: "optional",
            parentLink: (paragraphs: number) =>
                paragraphs === 1 ? "↑ parent link in the first paragraph" : `↑ parent link within the first ${paragraphs} paragraphs`,
            noParentLink: "no early parent link",
            children: "Links to the child pages",
            total: (count: number) => `≈ ${count} words in all`,
            range: (min: number, max: number) => `${min}–${max} allowed`,
            under: "The sections add up to less than the shortest page allowed.",
            over: "The sections add up to more than the longest page allowed.",
            unbounded: "no length limit",
            links: (count: number) => `up to ${count} links`,
            images: (count: number) => (count === 0 ? "no images" : count === 1 ? "1 image" : `${count} images`),
            noSections: "Add a section to see the page take shape.",
            untitled: "Untitled section",
        },
        layer: {
            label: "Editing",
            global: "The template",
            site: "This site",
            globalHint: "What you change here reaches every site that uses this template.",
            siteHint:
                "What you change here stays on this site. Everything you leave alone keeps following the template.",
            page: "This page",
            pageHint: "What you change here stays on this page alone. Everything you leave alone follows the site and the template.",
            fromGlobal: "From the template",
            fromSite: "Set by this site",
            fromPage: "Set by this page",
            follow: "Follow the template again",
            followSite: "Follow the site again",
            siteSays: (value: string) => `The site says ${value}.`,
            templateSays: (value: string) => `The template says ${value}.`,
            on: "on",
            off: "off",
            none: "nothing",
        },
        overrides: {
            title: "Where the values come from",
            base: "The template is the starting point. A site, and then a page, may change parts of it.",
            runOrder: "Template, then this site, then the page. The last one to set a value wins.",
            siteTitle: "What this site changes",
            siteNone: "This site changes nothing. Every value comes from the template.",
            sitePrefix: "This site",
            pagePrefix: "This page",
            clearSite: "Drop every change this site makes",
            clearSiteTitle: "Drop the changes this site makes?",
            clearSiteBody: "Every value goes back to what the template says. Pages keep their own changes.",
            clearConfirm: "Drop them",
            cancel: "Cancel",
            pagesTitle: "Pages that change it",
            pagesNone: "No page changes this template.",
            pageCount: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
            clearPage: "Drop the changes this page makes",
            clearPageTitle: "Drop the changes this page makes?",
            clearPageBody: "The page goes back to what the template and this site say.",
            viewResolved: "See what this page ends up with",
            resolvedTitle: "What this page ends up with",
            resolvedBody: "Every value below, and the layer that decided it.",
            unknownPage: "a page that no longer exists",
            resolveFailed: "This page cannot be resolved: it has no template and its site has no default.",
            close: "Close",
        },
        sentence: {
            sections: (count: number, headings: string) =>
                count === 1 ? `writes one section, ${headings}` : `writes its own ${count} sections: ${headings}`,
            sectionsNone: "removes every section",
            tone: (tone: string) => `changes the tone to “${tone}”`,
            toneNone: "drops the tone instruction",
            shorter: (min: number, max: number) => `shortens the page to ${min}–${max} words`,
            longer: (min: number, max: number) => `lengthens the page to ${min}–${max} words`,
            length: (min: number, max: number) => `sets the page length to ${min}–${max} words`,
            lengthMin: (min: number) => `asks for at least ${min} words`,
            lengthMax: (max: number) => `caps the page at ${max} words`,
            primaryInTitle: (on: boolean) =>
                on ? "requires the primary keyword in the title" : "stops requiring the primary keyword in the title",
            primaryInH1: (on: boolean) =>
                on ? "requires the primary keyword in the H1" : "stops requiring the primary keyword in the H1",
            primaryInFirstParagraph: (on: boolean) =>
                on
                    ? "requires the primary keyword in the first paragraph"
                    : "stops requiring the primary keyword in the first paragraph",
            maxDensity: (percent: string) => `caps keyword density at ${percent}`,
            upDepth: (levels: number) =>
                levels === 0
                    ? "stops linking up to parent pages"
                    : levels === 1
                      ? "links up one level to the parent page"
                      : `links up ${levels} levels of parent pages`,
            downLinks: (on: boolean) => (on ? "links down to child pages" : "stops linking down to child pages"),
            siblingMinWeight: (weight: string) => `only links siblings scoring ${weight} or higher`,
            maxLinks: (links: number) => `allows at most ${links} internal links`,
            maxPerTarget: (links: number) =>
                links === 1 ? "allows one link to any single page" : `allows up to ${links} links to the same page`,
            parentLinkWithinParagraphs: (paragraphs: number) =>
                paragraphs === 0
                    ? "stops insisting on an early parent link"
                    : paragraphs === 1
                      ? "puts the parent link in the first paragraph"
                      : `puts the parent link inside the first ${paragraphs} paragraphs`,
            childrenSection: (on: boolean) =>
                on ? "adds a section listing the child pages" : "drops the section listing the child pages",
            titlePattern: (pattern: string) => `uses the title pattern “${pattern}”`,
            titlePatternNone: "drops the title pattern",
            descriptionMax: (characters: number) => `caps the meta description at ${characters} characters`,
            featured: (on: boolean) => (on ? "adds a featured image" : "drops the featured image"),
            inline: (images: number) =>
                images === 0
                    ? "uses no inline images"
                    : images === 1
                      ? "asks for one inline image"
                      : `asks for ${images} inline images`,
            imageSource: (source: string) => `takes images from ${source}`,
            profile: (role: string, provider: string, model: string) => `uses ${provider} ${model} for the ${role}`,
            profileNone: (role: string) => `lets the ${role} fall back to the site model`,
            stepsOff: (steps: string) => `skips ${steps}`,
            stepsOn: (steps: string) => `also runs ${steps}`,
            recipe: "changes which steps run",
            allowErrors: (on: boolean) =>
                on ? "lets a page through the checks with errors" : "stops a page at the checks when it has errors",
            repairIterations: (times: number) => (times === 1 ? "repairs the links once" : `repairs the links up to ${times} times`),
            other: (field: string) => `changes ${field}`,
        },
        sections: {
            title: "Sections",
            body: "A generated page is written section by section, in this order.",
            add: "Add a section",
            empty: "No sections yet",
            emptyBody: "A template needs at least one section before a run can use it.",
            heading: "Heading",
            intent: "What this section has to do",
            intentHint: "Written for the model, not for the reader.",
            targetWords: "Target words",
            required: "Required",
            requiredHint: "A required section is never dropped, however short the page is.",
            primaryInHeading: "Primary keyword in the heading",
            include: "Keywords this section must use",
            includeAdd: "Add",
            includePlaceholder: "ceramic mug",
            includeRemove: (word: string) => `Remove ${word}`,
            includeEmpty: "No keyword is pinned to this section.",
            moveUp: "Move up",
            moveDown: "Move down",
            remove: "Remove this section",
            untitled: "Untitled section",
            position: (index: number, total: number) => `${index} of ${total}`,
        },
        content: {
            title: "Tone and length",
            tone: "Tone",
            toneHint: "One or two sentences the writer follows on every page.",
            lengthMin: "Shortest",
            lengthMax: "Longest",
            lengthHint: "Total words across every section.",
            keywords: "Primary keyword",
            keywordsBody: "Where the page has to carry the keyword it is written for.",
            primaryInTitle: "In the title",
            primaryInH1: "In the H1",
            primaryInFirstParagraph: "In the first paragraph",
            maxDensity: "Highest density",
            maxDensityHint: "As a share of all words. 0.025 is 2.5%.",
        },
        links: {
            title: "Link rules",
            body: "These decide which internal links a generated page carries and how many.",
            fromTemplate:
                "At run time these come from the template, not from the link policy. The policy decides only external links, self links and anchors.",
            upDepth: "Levels up",
            upDepthHint: "How far up the parent chain the page links.",
            downLinks: "Link down to children",
            siblingMinWeight: "Lowest sibling score",
            siblingMinWeightHint: "Between 0 and 1. A related entity below this is not linked.",
            maxLinks: "Most links on a page",
            maxPerTarget: "Most links to one page",
            parentLinkWithinParagraphs: "Parent link within",
            parentLinkWithinParagraphsHint: "Paragraphs from the top. 0 turns the rule off.",
            childrenSection: "Add a section listing the children",
        },
        meta: {
            title: "Meta",
            titlePattern: "Title pattern",
            titlePatternHint: "Placeholders such as {primaryKeyword} and {siteName} are filled in per page.",
            descriptionMax: "Longest description",
            descriptionMaxHint: "Characters. Google truncates around 155.",
            images: "Images",
            featured: "Featured image",
            inline: "Inline images",
            source: "Where images come from",
            sourceHint: "A source is required as soon as any image is asked for.",
            noSource: "Not chosen",
        },
        imageSource: {
            ai: "the image model",
            wpmedia: "the WordPress media library",
            local: "a local folder",
        },
        models: {
            title: "Models",
            body: "A role left out here falls back to the site profile, and then to the global one.",
            role: "Role",
            provider: "Provider",
            model: "Model",
            add: "Pin a role to a model",
            remove: (role: string) => `Unpin the ${role} role`,
            empty: "No role is pinned here",
            emptyBody:
                "Every role follows the model settings. Pin one only when this template needs a different model.",
            pickModel: "Pick a model",
            catalogEmpty: "The model catalog is empty, so there is nothing to pin a role to.",
            allPinned: "Every role is already pinned.",
        },
        recipe: {
            title: "Recipe",
            body: "The steps a run takes for one page, in the order the pipeline runs them.",
            order: "This order is the pipeline order and cannot be rearranged.",
            enabled: (on: number, total: number) => `${on} of ${total} steps on`,
            noneEnabled: "No step is on, so a run cannot start from this template.",
            unknown: "Not a step this build knows about. It is kept as it was written.",
            carriesParams: "Carries settings the agent wrote",
            params: {
                allowErrors: "Let the page through with errors",
                allowErrorsHint: "Off, a page with errors stops here and waits for a person.",
                iterations: "Repair attempts",
                iterationsHint: "How many times the links are repaired before the page moves on.",
            },
        },
        steps: {
            resolve_context: "Work out what this page may link to",
            generate_body: "Write the body",
            generate_meta: "Write the title and description",
            insert_links: "Insert the internal links",
            repair_links: "Repair the links the checks refused",
            generate_images: "Make the images",
            validate: "Check the page against the rules",
            judge: "Score the page",
            publish: "Publish it to WordPress",
            relink_neighbors: "Relink the neighbouring pages",
            sync_back: "Read the published page back",
            report: "Write the run report",
            sync_site: "Read the whole site",
        },
    },
    policies: {
        title: "Link policies",
        subtitle: "A policy decides external links, self links and how anchor text is chosen.",
        loading: "Loading link policies",
        effective: "In force on this site",
        effectiveFromSite: "Chosen on the site as its link policy.",
        effectiveFallback: "No policy is chosen on the site, so the workspace default applies.",
        effectiveMissing: "No link policy applies to this site.",
        split: "Two sources, one outcome",
        splitBody:
            "A run reads the link rules — how many links, how far up, which siblings — from the template it is using. It reads external links, self links and the anchor strategy from the policy in force. The link rules stored on a policy are kept but never read.",
        forbidExternal: "Forbid links off the site",
        forbidSelf: "Forbid a page linking to itself",
        anchorStrategy: "Anchor text",
        anchorStrategyHint: "How the anchor for a link is chosen when an entity carries several.",
        anchor: {
            prefer_user: "Prefer the anchor you wrote",
            rotate: "Rotate through every anchor",
        },
        forbidsBoth: "external, self",
        forbidsExternal: "external",
        forbidsSelf: "self",
        forbidsNone: "nothing",
        newPolicy: "New policy",
        edit: "Edit",
        create: {
            title: "New link policy",
            body: "A new policy starts from the one in force on this site.",
            confirm: "Create it",
            editTitle: "Edit this link policy",
            editBody: "Saving changes it for every site that uses it.",
            save: "Save",
            cancel: "Cancel",
            name: "Name",
            scope: "Available to",
            scopeHint: "Either every site in this workspace, or this site alone.",
        },
        rulesTitle: "Link rules on this policy",
        rulesBody: "Kept on the record, but a run reads its link rules from the template instead.",
        deleteTitle: "Delete this link policy?",
        deleteBody: "Sites that point at it fall back to the workspace default.",
        deleteConfirm: "Delete",
        delete: "Delete",
    },
    toasts: {
        saved: "Saved",
        deleted: "Deleted",
        started: "Started",
        copied: "Copied",
    },
    errors: errorMessages,
};
