export const errorMessages = {
    NOT_FOUND: "That record no longer exists here. The view has been refreshed.",
    CONFLICT: "Something else changed this first. The view has been refreshed.",
    INVALID: "Check the highlighted fields and try again.",
    UNAUTHORIZED: "WordPress refused the credentials for this site.",
    RATE_LIMITED: "The model provider is rate limiting. Retrying shortly.",
    BUDGET_EXCEEDED: "The run stopped at its budget cap. Raise the cap or send fewer pages.",
    EXTERNAL: "An external service failed. Nothing here was changed.",
    INTERNAL: "Something went wrong inside Postulator. The details are in errors.log.",
    CANCELLED: "Cancelled.",
    NEEDS_HUMAN: "This needs your decision before it can continue.",
    LOCKED: "Postulator is locked. Unlock it to continue.",
} as const;

export const copy = {
    app: {
        name: "Postulator",
        tagline: "An entity graph turned into graph-compliant WordPress pages.",
        loading: "Loading",
        retry: "Try again",
        dismiss: "Dismiss",
        refreshed: "Refreshed",
        save: "Save",
        cancel: "Cancel",
        loadMore: "Load more",
        openExternal: "Open in your browser",
    },
    lock: {
        title: "Postulator is locked",
        prompt: "Enter the master password to unlock the workspace.",
        password: "Master password",
        unlock: "Unlock",
        unlocking: "Unlocking. Deriving the key takes a few seconds.",
        wrong: "That password did not unlock the workspace.",
        firstRun: "No master password is set. Everything is protected by Windows DPAPI alone.",
        setPassword: "Set a master password",
        unrecoverable: "The master key cannot be read. Restore a backup to recover this workspace.",
        lockNow: "Lock now",
    },
    nav: {
        overview: "Overview",
        graph: "Graph",
        pages: "Pages",
        runs: "Runs",
        templates: "Templates",
        schedules: "Schedules",
        importExport: "Import",
        reports: "Reports",
        agent: "Agent",
        settings: "Settings",
        sites: "Sites",
        inbox: "Inbox",
    },
    shell: {
        sections: "Sections",
        siteSwitcher: "Switch site",
        noSiteSelected: "No site selected",
        search: "Search",
        agentDock: "Agent",
        collapseDock: "Collapse the agent dock",
        expandDock: "Expand the agent dock",
        activeRuns: "Active runs",
        spend: "Spent",
        pluginInstalled: "Plugin installed",
        pluginMissing: "Plugin missing",
        locked: "Locked",
        unlocked: "Unlocked",
        unprotected: "No master password",
    },
    notBuilt: {
        title: "Not built yet",
        body: "This screen is scheduled and nothing stands in for it here.",
        wave: (wave: string) => `It arrives with ${wave}.`,
    },
    empty: {
        sites: "No sites yet. Add the WordPress site you want Postulator to work on.",
        pages: "No pages in the map. Import a sitemap or let the agent plan the first pages.",
        pageTree: "The page tree is empty. Sync the site or import a sheet to fill it.",
        pageLinks: "This page links nowhere yet. A generate run writes its internal links.",
        entities: "The entity graph is empty. Import a sheet or ask the agent to propose entities from the pages.",
        proposedEdges: "No proposed edges are waiting. Run a proposal to suggest relationships.",
        edges: "No edges between these entities yet. Add one or approve a proposal.",
        runs: "No runs yet. Start a generate run from the page map.",
        runItems: "This run has no items. It was started against an empty selection.",
        runEvents: "No steps have been recorded yet for this run.",
        artifacts: "This item produced no artifacts yet.",
        templates: "No templates yet. Create one or let the agent draft it for you.",
        policies: "No link policies yet. The built-in defaults apply until you add one.",
        overrides: "No overrides. Every page uses the template as written.",
        schedules: "No schedules yet. Add one to generate or sync on a timer.",
        mappings: "No saved column mappings for this site yet.",
        previewPages: "The sheet produced no pages. Check the column mapping.",
        previewEntities: "The sheet produced no entities. Check the column mapping.",
        previewEdges: "The sheet produced no relationships between entities.",
        importFindings: "Nothing to report. Every row read cleanly.",
        cannibalization: "No two pages compete for the same entity.",
        orphans: "No orphan pages. Every page is reachable from the graph.",
        topEntities: "No entity has a score yet. Recompute the scores after approving edges.",
        conversations: "No conversations yet. Ask the agent for something and it starts one.",
        messages: "Nothing said yet in this conversation.",
        pendingActions: "Nothing is waiting for approval.",
        tools: "The agent has no tools registered.",
        models: "No models in the catalog. Add one or restore the seeded catalog.",
        profiles: "No role profiles set. Every role falls back to the global model.",
        providerKeys: "No provider key is stored yet.",
        settings: "No settings in this group.",
        readiness: "Everything on the checklist is done. Start a generate run.",
        usage: "Nothing has been spent yet.",
        depth: "No pages are deep enough to chart.",
    },
    readiness: {
        providerKey: "Store an API key for at least one model provider.",
        profiles: "Point each model role at a model.",
        site: "Add the WordPress site you are working on.",
        plugin: "Install the companion plugin on the site.",
        sync: "Sync the site so Postulator knows what is already published.",
        graph: "Create entities and approve the edges between them.",
        canonicals: "Give every entity a canonical page so it can be linked to.",
        template: "Pick the template a generate run should use.",
    },
    onboarding: {
        title: "Getting ready",
        subtitle: "A generate run writes pages that prove the graph. Every line below has to be true first.",
        panel: "Readiness",
        progress: (done: number, total: number) => `${done} / ${total} done`,
        remaining: (left: number) => (left === 1 ? "1 step left" : `${left} steps left`),
        ready: "Ready to generate",
        blocked: "Add a site before this one can be answered.",
        forSite: (name: string) => `Checked against ${name}.`,
        noSite: "Checked against your model settings only — there is no site yet.",
        recheck: "Check again",
        names: {
            providerKey: "Provider key",
            profiles: "Model roles",
            site: "Site",
            plugin: "Companion plugin",
            sync: "First sync",
            graph: "Entities and edges",
            canonicals: "Canonical pages",
            template: "Template",
        },
        actions: {
            providerKey: "Open model settings",
            profiles: "Assign the roles",
            site: "Add a site",
            plugin: "Open the site",
            sync: "Open the page map",
            graph: "Open the graph",
            canonicals: "Open the page map",
            template: "Open templates",
        },
        done: {
            providerKey: (count: number) => (count === 1 ? "1 provider has a key." : `${count} providers have a key.`),
            profiles: "Writer, editor, linker and judge all point at a model.",
            plugin: (version: string) => (version === "" ? "Installed." : `Installed, version ${version}.`),
            sync: (count: number) => `${count} pages in the map.`,
            syncAt: (when: string) => `Last synced ${when}.`,
            graph: "Entities exist and at least one edge is approved.",
            canonicals: "Every entity points at a canonical page.",
            template: "A template is available to a generate run.",
        },
        todo: {
            profiles: (roles: string) => `Still unassigned: ${roles}.`,
            graphNoEntities: "No entities yet.",
            graphNoEdges: "Entities exist, but no edge is approved yet.",
            canonicals: "At least one entity has no canonical page, so nothing can link to it.",
        },
    },
    sites: {
        title: "Sites",
        subtitle: "Every graph, page map and run below belongs to exactly one WordPress site.",
        add: "Add site",
        addTitle: "Add a site",
        editTitle: "Edit site",
        open: "Open this site",
        edit: "Edit",
        anyStatus: "Any status",
        columns: {
            name: "Name",
            baseUrl: "Base URL",
            status: "Status",
            plugin: "Plugin",
            created: "Added",
        },
        field: {
            name: "Name",
            nameHint: "What you call this site inside Postulator.",
            baseUrl: "Base URL",
            baseUrlHint: "The WordPress home URL, for example https://example.com.",
            username: "WordPress user",
            usernameHint: "The account the application password belongs to.",
            password: "Application password",
            passwordHint: "Generated under Users → Profile in WordPress, not the login password.",
            passwordKeep: "Leave empty to keep the stored password.",
            allowInsecure: "Allow plain http",
            allowInsecureHint: "Credentials travel unencrypted. Only for a local install.",
        },
        insecureWarning: "This site is reached over plain http, so the application password crosses the network unencrypted.",
        test: "Test connection",
        testing: "Testing",
        reach: {
            ok: "The site answered and the credentials work.",
            upgradeRequired: "The site answered on http and asked for https.",
            unauthorized: "The site answered but refused these credentials.",
            unreachable: "The site did not answer.",
        },
        useSuggested: (url: string) => `Use ${url}`,
        detected: (name: string) => `Reported name: ${name}`,
        woo: "WooCommerce detected",
        deleteTitle: "Delete this site",
        deleteBody: (name: string) =>
            `${name} goes, and with it its page map, entities and edges, runs and their artifacts, site templates and link policies, schedules, saved import mappings and agent conversations. Nothing on WordPress is touched.`,
        deleteConfirm: "Delete the site",
        pickSite: "Pick a site on the left to see its plugin state and credentials.",
        plugin: {
            title: "Companion plugin",
            installed: (version: string) => (version === "" ? "Installed" : `Installed, version ${version}`),
            missingTitle: (name: string) => `The companion plugin is not installed on ${name}`,
            missingBody: "Postulator falls back to the plain WordPress REST API. In that mode:",
            losses: [
                "Products and product categories stay invisible to a sync.",
                "SEO meta is read-only — title and description cannot be written back.",
                "relink_neighbors is skipped on every item, so neighbour links are never repaired.",
            ],
            recheck: "Check again",
            download: "Save the plugin zip",
            saved: (path: string) => `Companion plugin written to ${path}`,
            capabilities: "Capabilities",
            seo: "SEO plugin",
            noSeo: "none detected",
            noCapabilities: "none reported",
        },
    },
    runs: {
        queued: "Queued",
        running: "Running",
        waiting: "Waiting",
        paused: "Paused",
        completed: "Completed",
        failed: "Failed",
        cancelled: "Cancelled",
        reconnecting: "Reconnecting to the run log",
        pauseReason: {
            budget_exceeded: "Paused at the budget cap.",
            awaiting_confirmation: "Paused until you approve the pending action.",
            needs_human: "Paused for a human decision.",
            user: "Paused by you.",
        },
        start: "Start run",
        pause: "Pause",
        resume: "Resume",
        cancel: "Cancel run",
        retryStep: "Retry this step",
        estimate: "Estimated cost",
        budgetCap: "Budget cap",
        deadline: "Deadline",
    },
    agent: {
        send: "Send",
        cancelTurn: "Stop",
        thinking: "Working",
        confirmTitle: "Approve this action",
        approve: "Approve",
        reject: "Reject",
        autonomous: "Autonomous mode runs write and dangerous tools without asking.",
        confirmMode: "Confirm mode asks before every write.",
        turnStalled: "The turn stopped reporting. The saved messages are shown instead.",
    },
    pages: {
        views: { table: "Table", tree: "Tree" },
        columns: {
            path: "Path",
            title: "Title",
            wpType: "WP type",
            status: "Status",
            entity: "Entity",
            drift: "Drift",
            synced: "Synced",
            created: "Created",
        },
        filters: {
            title: "Filters",
            reset: "Reset",
            pathPrefix: "Path prefix",
            pathPrefixHint: "Matches the start of a path, such as /collections/.",
            status: "Status",
            anyStatus: "Any status",
            entity: "Entity",
            anyEntity: "Any entity",
            unmapped: "No entity attached",
            noEntities: "This site has no entities yet.",
            partialEntities: "More entities exist than were loaded, so some rows read as mapped without a name.",
        },
        siteTotal: (total: number) => `${total} pages`,
        loadMore: "Load more",
        loading: "Loading the page map",
        noMatch: "No page matches these filters",
        noMatchBody: "Widen the filters or reset them to see the whole map.",
        plan: "Plan a page",
        untitled: "Untitled",
        mapped: "mapped",
        unmapped: "no entity",
        empty: { title: "The page map is empty" },
        drift: {
            badge: "drift",
            title: "Someone edited this page in WordPress",
            body: "WordPress reports a change made after Postulator last wrote this page. What changed cannot be shown: raw WordPress content never crosses into the app, so there is nothing here to compare against.",
            decision:
                "A publish run started with refuseDrift pauses this page for a human instead of overwriting the edit. Without it the run overwrites the page and records a drift finding on the publish result.",
            lastWritten: "Last synced",
            wpModified: "WordPress modified",
        },
        tree: {
            title: "Page tree",
            noFilters: "The tree takes a site and nothing else, so the filters apply to the table only.",
            unbounded:
                "The tree call returns every page on the site in one uncursored response. There is no limit and no cursor.",
            guard: (total: number) =>
                `This site has ${total} pages, and loading them all in one response would block the window.`,
            unknownSize: "The size of this site is not known, so the tree was not fetched automatically.",
            useTable: "Use the table instead",
            loadAnyway: "Load the whole tree anyway",
            load: "Load the tree",
            nodes: (count: number) => `${count} pages in the tree`,
            children: (count: number) => `${count} below`,
            expandAll: "Expand all",
            collapseAll: "Collapse all",
            showMore: (hidden: number) => `Show ${hidden} more`,
        },
        detail: {
            close: "Close",
            notFound: "This page is no longer in the map.",
            entity: "Entity",
            entityMissing: "The entity this page points at could not be read.",
            entityMeta: (kind: string, score: number) => `${kind} · score ${score.toFixed(2)}`,
            noEntity: "Not mapped to an entity",
            noEntityBody: "A page outside the graph is never a link target, so generation cannot link to it.",
            noEntityOption: "No entity",
            map: "Map",
            change: "Change",
            unmap: "Unmap",
            canonical: "canonical",
            canonicalTitle: "Canonical pages are what the graph links to",
            canonicalBody:
                "An entity with no canonical page is never a link target, so generation cannot link to it. Mapping a page to an entity does not make it canonical.",
            makeCanonical: "Make this the canonical page",
            canonicalIsHere: "This page is the canonical page for its entity.",
            canonicalElsewhere: "Another page is canonical for this entity.",
            canonicalMissing: "This entity has no canonical page, so nothing can link to it.",
            openCanonical: "Open the canonical page",
            meta: "Meta",
            path: "Path",
            pathHint: "Normalised on save: lower case, a leading and a trailing slash, no query and no fragment.",
            title: "Title",
            h1: "H1",
            metaTitle: "Meta title",
            metaDescription: "Meta description",
            canonicalUrl: "Canonical URL",
            wpType: "WP type",
            status: "Status",
            characters: (count: number) => `${count} characters`,
            save: "Save",
            revert: "Revert",
            links: "Outgoing links",
            linksSummary: (total: number, generated: number) => `${total} links · ${generated} written by a run`,
            report: "Last report",
            noReport: "No run has touched this page yet",
            noReportBody: "Send this page through a generate run and its report lands here.",
            openRun: "Open the run item",
            judge: (score: number) => `judge ${score.toFixed(0)}`,
            validation: (score: number) => `validation ${score.toFixed(0)}`,
            publishedAs: (status: string) => `published as ${status}`,
            liveUrl: "Live URL",
            deletePage: "Delete",
            deleteTitle: "Delete this page?",
            deleteBody: "The row leaves the page map. Nothing on the WordPress site is touched.",
            deleteConfirm: "Delete",
            cancel: "Cancel",
        },
        create: {
            title: "Plan a page",
            body: "A planned page is a row in the map. It does not exist on WordPress until a run publishes it.",
            confirm: "Plan it",
            cancel: "Cancel",
            noEntity: "No entity",
            entityHint: "A page with no entity is not part of the graph and is never a link target.",
        },
        conflict: {
            title: "This would cannibalise another page",
            body: "Two pages cannot compete for the same target, so nothing was written.",
            reason: {
                path_conflict: "already takes that path",
                same_entity_canonical: "is already the canonical page for that entity",
                same_primary_keyword: "already targets that primary keyword",
            },
            unknownReason: "conflicts with this page",
            descendantsTitle: "The path cannot change",
            descendants: (count: number) =>
                `${count} pages sit beneath this one, so its path is fixed. Move or delete them first.`,
        },
    },
    toasts: {
        saved: "Saved",
        deleted: "Deleted",
        started: "Started",
        copied: "Copied",
    },
    errors: errorMessages,
};
