export const links = {
    title: "Linking",
    loading: "Auditing the links",
    policy: (name: string) => `Policy ${name}`,
    forbidExternal: "no external links",
    allowExternal: "external links allowed",
    forbidSelf: "no self links",
    allowSelf: "self links allowed",
    meters: {
        required: "Links the graph asks for",
        targets: (count: number) => (count === 1 ? "1 target" : `${count} targets`),
        satisfied: "in place",
        missingRequired: "required, missing",
        missingOptional: "optional, missing",
        blocked: "blocked, the target has no page",
        audited: "Pages audited",
        ofPages: (audited: number, pages: number) => `${audited} of ${pages}`,
        orphans: "Orphan pages",
        offGraph: "Links outside the graph",
    },
    relink: {
        start: (count: number) => (count === 1 ? "Relink 1 page" : `Relink ${count} pages`),
        none: "Nothing to relink",
        noneTitle: "Every audited page carries the links the graph asks for",
        title: "Start a relink run over the pages with missing links",
        capped: (count: number) => `The worst ${count} pages; a run takes at most ${count} targets`,
        page: "Relink this page",
        does: "A relink reads each page from WordPress, places the links its rules ask for and writes it back. It never rewrites the body and it calls no model, so it costs nothing.",
    },
    filters: {
        title: "Filters",
        reset: "Reset",
        show: "Show",
        status: "Status",
        anyStatus: "Any status",
        entity: "Under an entity",
        anyEntity: "Any entity",
        sort: "Order",
        severity: "Worst first",
        path: "By path",
    },
    show: {
        all: "All pages",
        missing: "Missing links",
        missingRequired: "Missing required links",
        blocked: "Blocked targets",
        offGraph: "Links outside the graph",
        orphans: "Orphans",
        skipped: "Not audited",
    },
    columns: {
        path: "Page",
        entity: "Entity",
        links: "Links",
        missing: "Missing",
        blocked: "Blocked",
        offGraph: "Outside",
        inbound: "Inbound",
        status: "Status",
    },
    cell: {
        ofTargets: (satisfied: number, targets: number) => `${satisfied} / ${targets}`,
        required: (count: number) => `${count} required`,
        orphan: "orphan",
        skipped: { unmapped: "no entity", no_template: "no template" } as Readonly<Record<string, string>>,
    },
    empty: {
        title: "No page to audit",
        body: "The audit covers pages mapped to an entity. Map pages in the graph or the page map first.",
        graph: "Open the graph",
        noMatch: "No page matches these filters",
        noMatchBody: "Widen the filters or reset them to see every page.",
    },
    panel: {
        title: "Page links",
        close: "Close the page",
        openPage: "Open the page",
        openEntity: "Open the entity",
        up: "Up, to the parents",
        down: "Down, to the children",
        sibling: "Sideways, to related entities",
        blocked: "Blocked",
        blockedHint: "These targets have no canonical page, so no link can be written to them.",
        givePage: "Give it a page",
        extra: "Links the graph did not ask for",
        satisfied: "in place",
        missing: "missing",
        required: "required",
        anchor: (text: string) => `anchor “${text}”`,
        anchorNotAllowed: "anchor not in the list",
        allowed: (anchors: readonly string[]) => (anchors.length === 0 ? "No anchors listed." : `Allowed: ${anchors.join(", ")}`),
        none: "None",
        rules: (upDepth: number, downLinks: boolean, siblingMinWeight: number) =>
            `up ${upDepth} · down ${downLinks ? "on" : "off"} · sibling weight ≥ ${siblingMinWeight}`,
        skipped: {
            unmapped: "This page has no entity, so the graph asks nothing of it.",
            no_template: "This page has no template, so its link rules cannot be resolved.",
        } as Readonly<Record<string, string>>,
        inbound: (count: number) => (count === 1 ? "1 page links here" : `${count} pages link here`),
        orphan: "Nothing links here",
    },
    classes: { graph: "graph", self: "self", external: "external", unknown_internal: "unknown internal" } as Readonly<Record<string, string>>,
    relations: { up: "up", down: "down", sibling: "sideways" } as Readonly<Record<string, string>>,
};
