export const readiness = {
    providerKey: "Store an API key for at least one model provider.",
    profiles: "Point each model role at a model.",
    site: "Add the WordPress site you are working on.",
    plugin: "Install the companion plugin on the site.",
    sync: "Sync the site so Postulator knows what is already published.",
    graph: "Create entities and approve the edges between them.",
    canonicals: "Give every entity a canonical page so it can be linked to.",
    template: "Pick the template a generate run should use.",
};

export const onboarding = {
    title: "Getting ready",
    subtitle: "A generate run writes pages that prove the graph. Every line below has to be true first.",
    panel: "Readiness",
    progress: (done: number, total: number) => `${done} / ${total} done`,
    remaining: (left: number) => (left === 1 ? "1 step left" : `${left} steps left`),
    ready: "Ready to generate",
    blocked: "Add a site before this one can be answered.",
    forSite: (name: string) => `Checked against ${name}.`,
    noSite: "Checked against your model settings only — there is no site yet.",
    recheck: "Check again",
    names: {
        providerKey: "Provider key",
        profiles: "Model roles",
        site: "Site",
        plugin: "Companion plugin",
        sync: "First sync",
        graph: "Entities and edges",
        canonicals: "Canonical pages",
        template: "Template",
    },
    actions: {
        providerKey: "Open model settings",
        profiles: "Assign the roles",
        site: "Add a site",
        plugin: "Open the site",
        sync: "Open the page map",
        graph: "Open the graph",
        canonicals: "Show the entities without a page",
        template: "Open templates",
    },
    done: {
        providerKey: (count: number) => (count === 1 ? "1 provider has a key." : `${count} providers have a key.`),
        profiles: "Writer, editor, linker and judge all point at a model.",
        plugin: (version: string) => (version === "" ? "Installed." : `Installed, version ${version}.`),
        sync: (count: number) => `${count} pages in the map.`,
        syncAt: (when: string) => `Last synced ${when}.`,
        graph: "Entities exist and at least one edge is approved.",
        canonicals: "Every entity points at a canonical page.",
        template: "A template is available to a generate run.",
    },
    todo: {
        profiles: (roles: string) => `Still unassigned: ${roles}.`,
        graphNoEntities: "No entities yet.",
        graphNoEdges: "Entities exist, but no edge is approved yet.",
        canonicals: "At least one entity has no canonical page, so nothing can link to it.",
    },
};
