export const readiness = {
    panel: "Readiness",
    progress: (done: number, total: number) => `${done} / ${total} done`,
    remaining: (left: number) => (left === 1 ? "1 step left" : `${left} steps left`),
    ready: "Ready to generate",
    blocked: "Add a site before this one can be answered.",
    recheck: "Check again",
    names: {
        providerKey: "Provider key",
        profiles: "Model roles",
        site: "Site",
        plugin: "Companion plugin",
        sync: "First sync",
        graph: "Entities and edges",
        canonicals: "Canonical pages",
        template: "Template",
    },
    instructions: {
        providerKey: "Store an API key for at least one model provider.",
        profiles: "Point each model role at a model.",
        site: "Add the WordPress site you are working on.",
        plugin: "Install the companion plugin on the site.",
        sync: "Sync the site so Postulator knows what is already published.",
        graph: "Create entities and approve the edges between them.",
        canonicals: "Give every entity a canonical page so it can be linked to.",
        template: "Pick the template a generate run should use.",
    },
    actions: {
        providerKey: "Open model settings",
        profiles: "Assign the roles",
        site: "Add a site",
        plugin: "Open the site",
        sync: "Open the page map",
        graph: "Open the graph",
        canonicals: "Show the entities without a page",
        template: "Open templates",
    },
    done: {
        providerKey: (count: number) => (count === 1 ? "1 provider has a key." : `${count} providers have a key.`),
        profiles: "Writer, editor, linker and judge all point at a model.",
        plugin: (version: string) => (version === "" ? "Installed." : `Installed, version ${version}.`),
        sync: (count: number) => `${count} pages in the map.`,
        syncAt: (when: string) => `Last synced ${when}.`,
        graph: "Entities exist and at least one edge is approved.",
        canonicals: "Every entity points at a canonical page.",
        template: "A template is available to a generate run.",
    },
    todo: {
        profiles: (roles: string) => `Still unassigned: ${roles}.`,
        graphNoEntities: "No entities yet.",
        graphNoEdges: "Entities exist, but no edge is approved yet.",
        canonicals: "At least one entity has no canonical page, so nothing can link to it.",
    },
};

export const overview = {
    title: "Overview",
    sync: "Sync site",
    startRun: "Start run",
    openSite: "Open the site",
    reports: "Open reports",
    loading: "Loading the site overview",
    empty: "Nothing has been read back from this site yet.",
    emptyBody: "Sync the site to fill the page map, then the graph and the charts follow.",
    run: {
        title: "Latest run",
        active: "Running now",
        none: "No run has been started for this site yet.",
        items: (done: number, total: number) => `${done} / ${total} items`,
        failed: (count: number) => (count === 1 ? "1 failed" : `${count} failed`),
        budget: "Budget",
        open: "Open the run",
        startedBy: (who: string) => `started by ${who}`,
        publish: (mode: string) => (mode === "publish" ? "publishes live" : "writes drafts"),
    },
    tiles: {
        entities: "Entities",
        entitiesTotal: "Entities",
        withCanonical: "With a canonical page",
        withPublished: "Published",
        withoutPage: "Without a page",
        pages: "Pages",
        mapped: "Mapped to an entity",
        unmapped: "Unmapped",
        orphans: "Orphans",
        edges: "Edges",
        approved: "Approved",
        realized: "Realised as links",
        proposed: "Proposed",
        capped: (count: number) => `${count}+`,
    },
    depth: {
        title: "Page depth",
        unit: "segments in path",
        bucket: (depth: number) => (depth === 1 ? "1 seg" : `${depth} segs`),
    },
    top: {
        title: "Top entities",
        unit: "weight 0…1",
    },
    drift: {
        title: (count: number) => (count === 1 ? "1 page drifted" : `${count} pages drifted`),
        body: "Edited by hand in WordPress after the last publish.",
        action: "Open the page map",
    },
    coverage: {
        title: "Edge coverage",
        gap: (count: number) =>
            count === 1
                ? "1 approved edge has no link on the site yet."
                : `${count} approved edges have no link on the site yet.`,
        closed: "Every approved edge is realised as a link.",
        action: "Start a relink run",
    },
    plugin: {
        title: "The companion plugin is not installed",
        body: "Postulator falls back to the plain WordPress API, so SEO meta, product types and neighbour relinks stay off.",
        save: "Save the plugin package",
        saved: "Plugin package saved",
        open: "Open the site",
        dismiss: "Continue without it",
        fileName: "postulator-companion.zip",
        filter: "Zip archive",
    },
};
