export const pages = {
    title: "Pages",
    views: { table: "Table", tree: "Tree" },
    newPage: "New page",
    search: "Path starts with",
    sort: "Sort",
    sortOptions: {
        pathAsc: "Path A to Z",
        pathDesc: "Path Z to A",
        newest: "Newest first",
        oldest: "Oldest first",
    },
    tableOnly: "The tree reads the whole site at once, so filtering and sorting belong to the table.",
    summary: {
        open: "Open the editor",
        openOnSite: "Open in Tor Browser",
        notOnSite: "This page is not on the site yet.",
        entity: "Entity",
        noEntity: "No entity",
        meta: "Meta",
        links: "Outgoing links",
        moreLinks: (hidden: number) => `and ${hidden} more`,
        report: "Last report",
    },
    importSheet: "Import",
    sync: "Sync site",
    syncing: "Syncing",
    preview: {
        panel: "On the site",
        title: (path: string) => `How ${path} looks on the site`,
        open: "View on the site",
        openDraft: "Preview the draft",
        fromReview: "Preview on the site",
        openInBrowser: "Open in your browser",
        openAnyway: "Open in your browser anyway",
        newLink: "New link",
        close: "Close",
        public: "Public page",
        draft: "Draft preview",
        expiresIn: (minutes: number) => (minutes <= 1 ? "link expires in a minute" : `link expires in ${minutes} min`),
        expired: "This link has expired. Ask for a new one.",
        loading: "Loading the page from the site",
        embedHint: "If the site refuses to be shown inside the app, open it in your browser.",
        publicBody: "The page is published, so this is its public address.",
        draftBody: "The draft is shown through the site's theme with a private link that works for an hour and is hidden from search engines.",
        notOnSite: "Not on the site yet",
        notOnSiteBody: "A generate run writes this page to WordPress. Preview it once it is there.",
        archived: "No longer on the site",
        archivedBody: "This page was removed from WordPress.",
        needsPlugin: "Install the companion plugin to preview drafts",
        needsPluginBody:
            "Without the plugin WordPress shows a draft only to a logged-in editor. Published pages still open by their address.",
        outdatedPlugin: "Update the companion plugin to preview drafts",
        outdatedPluginBody: "The plugin on this site predates draft previews. Version 1.1.0 or later issues them.",
        viewports: { desktop: "Desktop", tablet: "Tablet", phone: "Phone" },
        viewport: "Preview width",
    },
    columns: {
        path: "Path",
        title: "Title",
        wpType: "WP type",
        status: "Status",
        entity: "Entity",
        drift: "Drift",
        synced: "Synced",
        created: "Created",
    },
    filters: {
        title: "Filters",
        reset: "Reset",
        pathPrefix: "Path prefix",
        status: "Status",
        anyStatus: "Any status",
        entity: "Entity",
        anyEntity: "Any entity",
        unmapped: "No entity attached",
        noEntities: "This site has no entities yet.",
    },
    loading: "Loading the page map",
    noMatch: "No page matches these filters",
    untitled: "Untitled",
    mapped: "mapped",
    unmapped: "no entity",
    empty: { title: "The page map is empty" },
    drift: {
        badge: "drift",
        title: "Someone edited this page in WordPress",
        body: "WordPress reports a change made after Postulator last wrote this page. What changed cannot be shown: raw WordPress content never crosses into the app, so there is nothing here to compare against.",
        decision:
            "A publish run started with refuseDrift pauses this page for a human instead of overwriting the edit. Without it the run overwrites the page and records a drift finding on the publish result.",
        lastWritten: "Last synced",
        wpModified: "WordPress modified",
    },
    tree: {
        title: "Page tree",
        unbounded:
            "The tree call returns every page on the site in one uncursored response. There is no limit and no cursor.",
        guard: (total: number) =>
            `This site has ${total} pages, and loading them all in one response would block the window.`,
        unknownSize: "The size of this site is not known, so the tree was not fetched automatically.",
        loadAnyway: "Load the whole tree anyway",
        load: "Load the tree",
        nodes: (count: number) => `${count} pages in the tree`,
        children: (count: number) => `${count} below`,
        expandAll: "Expand all",
        collapseAll: "Collapse all",
        showMore: (hidden: number) => `Show ${hidden} more`,
    },
    detail: {
        close: "Close",
        notFound: "This page is no longer in the map.",
        template: "Template",
        templateOwn: "Chosen for this page",
        templateDefault: "Site default",
        templateNone: "No template. The site has no default and this page names none, so a run cannot write it.",
        templateVersion: (name: string, version: number) => `${name} · v${version}`,
        templateDefaultOption: "Site default",
        templateSave: "Use it",
        templateCustomize: "Customize for this page",
        templateOpen: "Open the template",
        templateEdit: "Edit",
        entity: "Entity",
        entityMissing: "The entity this page points at could not be read.",
        entityMeta: (kind: string, score: number) => `${kind} · score ${score.toFixed(2)}`,
        noEntity: "Not mapped to an entity",
        noEntityBody: "A page outside the graph is never a link target, so generation cannot link to it.",
        noEntityOption: "No entity",
        map: "Map",
        change: "Change",
        unmap: "Unmap",
        canonical: "canonical",
        canonicalTitle: "Canonical pages are what the graph links to",
        canonicalBody:
            "An entity with no canonical page is never a link target, so generation cannot link to it. Mapping a page to an entity does not make it canonical.",
        makeCanonical: "Make this the canonical page",
        canonicalIsHere: "This page is the canonical page for its entity.",
        canonicalElsewhere: "Another page is canonical for this entity.",
        canonicalMissing: "This entity has no canonical page, so nothing can link to it.",
        openCanonical: "Open the canonical page",
        meta: "Meta",
        path: "Path",
        pathHint: "Normalised on save: lower case, a leading and a trailing slash, no query and no fragment.",
        title: "Title",
        h1: "H1",
        metaTitle: "Meta title",
        metaDescription: "Meta description",
        canonicalUrl: "Canonical URL",
        wpType: "WP type",
        status: "Status",
        characters: (count: number) => `${count} characters`,
        actions: "Actions",
    save: "Save",
        revert: "Revert",
        links: "Outgoing links",
        linksSummary: (total: number, generated: number) => `${total} links · ${generated} written by a run`,
        report: "Last report",
        noReport: "No run has touched this page yet",
        noReportBody: "Send this page through a generate run and its report lands here.",
        openRun: "Open the run item",
        judge: (score: number) => `judge ${score.toFixed(0)}`,
        validation: (score: number) => `validation ${score.toFixed(0)}`,
        publishedAs: (status: string) => `published as ${status}`,
        liveUrl: "Live URL",
        deletePage: "Delete",
        deleteTitle: "Delete this page?",
        deleteBody: "The row leaves the page map. Nothing on the WordPress site is touched.",
        deleteConfirm: "Delete",
        cancel: "Cancel",
    },
    create: {
        title: "Plan a page",
        body: "A planned page is a row in the map. It does not exist on WordPress until a run publishes it.",
        confirm: "Plan it",
        cancel: "Cancel",
        noEntity: "No entity",
        entityHint: "A page with no entity is not part of the graph and is never a link target.",
    },
    conflict: {
        title: "This would cannibalise another page",
        body: "Two pages cannot compete for the same target, so nothing was written.",
        reason: {
            path_conflict: "already takes that path",
            same_entity_canonical: "is already the canonical page for that entity",
            same_primary_keyword: "already targets that primary keyword",
        },
        unknownReason: "conflicts with this page",
        descendantsTitle: "The path cannot change",
        descendants: (count: number) =>
            `${count} pages sit beneath this one, so its path is fixed. Move or delete them first.`,
    },
};
