export const palette = {
    title: "Search",
    placeholder: "Search entities, pages, runs and commands",
    field: "Search",
    search: "search",
    goTo: "Go to",
    entities: "Entities",
    pages: "Pages",
    runs: "Runs",
    actions: "Actions",
    nothing: "Nothing matches that.",
    needSite: "Open a site to search its entities and pages.",
    navigate: "move",
    open: "open",
    close: "close",
    kinds: {
        screen: "screen",
        entity: "entity",
        page: "page",
        run: "run",
        action: "action",
    },
    run: (id: string, kind: string) => `Run ${id} · ${kind}`,
    newRun: "New run",
    newEntity: "New entity",
    syncSite: "Sync site",
    askAgent: "Ask the agent",
    syncing: "Sync started",
};
