export const reports = {
    title: "Reports",
    tabs: {
        label: "Report scale",
        site: "Site",
        runs: "Runs",
        pages: "Pages",
    },
    loading: "Measuring the site",
    tiles: {
        pagesMapped: "Pages mapped",
        pagesMappedNote: (mapped: number, total: number) => `${mapped} of ${total}`,
        entitiesWithPage: "Entities with a page",
        entitiesWithPageNote: (withPage: number, total: number) => `${withPage} of ${total}`,
        orphans: "Orphan pages",
        orphansNote: "no inbound link",
        drifted: "Drifted pages",
        driftedNote: "changed on the site",
        depth: "Average depth",
        depthNote: "segments in the path",
    },
    depth: {
        title: "Depth histogram",
        level: (level: number) => `depth ${level}`,
        pages: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
    },
    audit: {
        title: "Link audit",
        compliant: "of the pages on the site carry every link the graph asks for",
        audited: (audited: number, pages: number) => `${audited} of ${pages} pages audited`,
        missingRequired: "Missing required links",
        missing: "Missing links",
        pending: "Links waiting for a page to be written or published",
        blocked: "Blocked, the target has no page",
        offGraph: "Links outside the graph",
        orphans: "Orphan pages",
        open: "Open Linking",
    },
    coverage: {
        title: "Coverage",
        order: "worst first",
        entity: "Entity",
        kind: "Kind",
        path: "Page path",
        state: "Page",
        links: "Links",
        linkCount: (count: number) => (count === 1 ? "1 link" : `${count} links`),
        reasons: {
            noPage: "No canonical page",
            planned: "Page planned",
            exists: "Page exists",
            published: "Published",
            archived: "Archived",
        },
    },
    drift: {
        title: "Drift",
        path: "Page path",
        synced: "Last synced",
        changed: "Changed on the site",
        resync: "Re-sync the site",
        resyncTitle: "A sync run reads every page back from WordPress",
        none: "No page has changed on the site since its last sync.",
    },
    runs: {
        kind: "Kind",
        when: "Finished",
        items: "Items",
        outcome: "Done / failed",
        cost: "Cost",
        empty: "No finished runs yet. A report is written when a run reaches its last step.",
        report: "Run report",
        open: "Open run",
        path: "Page",
        status: "Status",
        findings: "Findings",
        errors: (count: number) => (count === 1 ? "1 error" : `${count} errors`),
        warnings: (count: number) => (count === 1 ? "1 warning" : `${count} warnings`),
        clean: "No findings",
        score: (score: number) => `scored ${Math.round(score * 100)}%`,
        tokens: "Tokens",
        perPage: "Per page",
        choose: "Choose a run to read its report.",
    },
    pages: {
        search: "Find a page by path",
        searchPlaceholder: "/guides/",
        searchHint: "Type a path to find the page whose last run you want to read.",
        noMatch: "No page starts with that path.",
        noReport: "No run has touched this page yet.",
        validation: "Validation",
        judge: "Judge",
        publish: "Publish",
        relink: "Relink",
        finishedAt: "Finished",
        openPage: "Open the page",
        openItem: "Open the run item",
        score: (score: number) => `${Math.round(score * 100)}%`,
        complianceScore: (score: number) => `compliance ${Math.round(score * 100)}%`,
        structureScore: (score: number) => `structure ${Math.round(score * 100)}%`,
        findings: (count: number) => (count === 1 ? "1 finding" : `${count} findings`),
        noFindings: "Nothing to fix",
        issues: "Issues",
        suggestions: "Suggestions",
        notPublished: "Not published",
        liveUrl: "Live address",
        neighbours: "Neighbour pages",
        linked: "linked",
        conflicts: "conflicts",
        skipped: "skipped",
        seoApplied: "SEO fields written",
        seoSkipped: "SEO fields skipped",
    },
    empty: {
        site: "No runs yet. Coverage, drift and link compliance are measured once a run has finished.",
        startRun: "Start a run",
        graph: "Open the graph",
    },
};
