export const runs = {
    title: "Runs",
    openOnSite: "Open in Tor Browser",
    reconnecting: "Reconnecting to the run log",
    reconnectingBody:
        "Live events are never buffered, so a reload loses the stream while the run carries on. The log below is being refilled from the run itself.",
    logFailed: "The run log could not be read",
    steps: {
        resolve_context: "Resolve context",
        generate_body: "Write the body",
        generate_meta: "Write the meta",
        insert_links: "Insert links",
        repair_links: "Repair links",
        generate_images: "Make images",
        validate: "Validate",
        judge: "Judge",
        publish: "Publish",
        relink_neighbors: "Relink neighbours",
        sync_back: "Read back",
        report: "Report",
    },
    perKindSteps: {
        repair_hierarchy: "Move under the parent",
        sync_site: "Sync the site",
        relink_page: "Place the links",
        revert: "Put it back",
    },
    kinds: {
        generate: "Generate",
        relink: "Relink",
        audit: "Audit",
        sync: "Sync",
        import: "Import",
        repair: "Repair",
        revert: "Revert",
        custom: "Custom",
    },
    status: {
        pending: "Pending",
        running: "Running",
        waiting: "Waiting",
        paused: "Paused",
        completed: "Completed",
        failed: "Failed",
        cancelled: "Cancelled",
    },
    pauseReason: {
        budget_exceeded: "Paused at the budget cap.",
        awaiting_confirmation: "Paused until you approve the pending action.",
        needs_human: "Paused for a human decision.",
        user: "Paused by you.",
        awaiting_parent: "Waiting for a parent page to reach the site; it goes on by itself once the parent is there.",
    },
    pauseReasonShort: {
        budget_exceeded: "budget cap",
        awaiting_confirmation: "awaiting approval",
        needs_human: "needs human",
        user: "paused by you",
        awaiting_parent: "waiting for parent",
    },
    unknownPauseReason: "Paused for a reason this build does not recognise.",
    budgetPausedTitle: "This run stopped at its budget cap",
    budgetPausedBody:
        "A run carries the cap it was started with and there is no binding that raises it. Resuming lets the run continue until its next model call and then it pauses again. To finish the work, cancel this run and start a new one over the same pages with a higher cap.",
    pause: "Pause",
    settled: "This run has already finished.",
    wholeSite: "The whole site",
    alreadyPaused: "This run is already paused.",
    notPaused: "This run is not paused.",
    notRunning: "Only a running run can be paused.",
    resume: "Resume",
    cancel: "Cancel run",
    cancelTitle: "Cancel this run",
    cancelBody:
        "Every pending, running and waiting item stops. Pages already published stay published; use Revert afterwards to take them back off the site.",
    cancelConfirm: "Cancel the run",
    keepRunning: "Keep it running",
    revert: "Revert",
    revertRunning: "A run that is still going cannot be reverted. Cancel it first.",
    revertOfARevert: "A revert cannot itself be reverted.",
    revertTitle: "Put back what this run wrote",
    revertBody:
        "Every page this run created goes to the WordPress trash and its row here goes back to planned. Every page it updated gets the body it replaced, and every neighbour it relinked gets the content it replaced. A page a human has edited since is left alone and held for you. Images it uploaded stay in the media library, and the SEO meta it wrote stays as it is.",
    revertConfirm: "Revert the run",
    revertKeep: "Leave it as it is",
    retryStep: "Retry this step",
    retryBusy: "The item has not stopped, so there is nothing to retry.",
    retryBlocked: {
        inputs_expired: "Inputs expired — re-run the page",
    },
    retryBlockedBody:
        "The artifacts this step needs were purged after the page published, and no step regenerates them. Start a fresh run over this page instead.",
    unknownRetryBlock: "Retry is refused for a reason this build does not recognise.",
    rerunPage: "Start a run over this page",
    columns: {
        kind: "Kind",
        status: "Status",
        progress: "Items",
        spend: "Spent",
        started: "Started",
        lasted: "Took",
        path: "Path",
        step: "Step",
        attempts: "Try",
        error: "Error",
        updated: "Updated",
    },
    filters: {
        title: "Filters",
        reset: "Reset",
        status: "Status",
        anyStatus: "Any status",
        kind: "Kind",
        anyKind: "Any kind",
        anyItemStatus: "All items",
    },
    loading: "Loading the run list",
    loadingItems: "Loading the run items",
    noMatch: "No run matches these filters",
    noItemMatch: "No item of this run has that status.",
    missingItem: "This item is not in the run.",
    backToRuns: "Runs",
    notFound: "This run is no longer here.",
    detail: {
        header: (kind: string) => `${kind} run`,
        startedBy: (actor: string) => `started by ${actor}`,
        publishModes: {
            draft: "Draft",
            publish: "Publish live",
        },
        publishing: {
            draft: "writes drafts",
            publish: "publishes live",
        },
        deadline: "Deadline",
        template: (name: string, version: number) => `${name} v${version}`,
        templateGone: "Template removed",
        noTemplate: "no template recorded",
        targets: (count: number) => (count === 1 ? "1 target page" : `${count} target pages`),
        items: (done: number, total: number) => `${done} / ${total} items`,
        done: "completed",
        failed: "failed",
        needsHuman: "need a human",
        pending: "pending",
        spent: "Spent",
        spentOf: (spent: string, cap: string) => `${spent} of ${cap}`,
        noCap: "No cap was set for this run",
        noCapBody:
            "A run with no dollar cap never stops itself on spend. Cancel it if the bill matters, and give the next run a cap.",
        hardStop: "A run pauses itself at the cap; it never overruns it.",
        tokens: "Tokens",
        tokensOf: (spent: string, cap: string) => `${spent} of ${cap}`,
        tokensBody: "Tokens are reported, not capped — the run stops on dollars.",
        calls: (count: number) => (count === 1 ? "1 model call" : `${count} model calls`),
        liveStats: "Counted from the run log while the run is live.",
        rowStats: "Counted from the finished run.",
        failure: "The run failed",
    },
    events: {
        title: "Events",
        live: "live",
        catchingUp: "catching up",
        settled: "log complete",
        names: {
            "run.queued": "Run queued",
            "run.started": "Run started",
            "run.paused": "Run paused",
            "run.resumed": "Run resumed",
            "run.cancelled": "Run cancelled",
            "run.completed": "Run completed",
            "run.failed": "Run failed",
            "run.budget_exceeded": "Budget cap reached",
            "item.started": "Item started",
            "item.done": "Item done",
            "item.failed": "Item failed",
            "item.needs_human": "Item needs a human",
            "step.started": "Step started",
            "step.done": "Step done",
            "step.failed": "Step failed",
            "step.retrying": "Step retrying",
            "llm.usage": "Model call",
        },
        attempt: (attempt: number) => `attempt ${attempt}`,
        retryIn: (delay: string) => `retrying in ${delay}`,
        seq: (seq: number) => `#${seq}`,
    },
    step: {
        position: (at: number, total: number, name: string) => `step ${at} of ${total} — ${name}`,
        unknownRecipe: (name: string) => `step ${name}`,
        noStep: "no step recorded yet",
        waitingUntil: (left: string) => `waiting ${left}`,
        retrying: (attempt: number, left: string) => `retrying, attempt ${attempt} in ${left}`,
        recipe: (first: string, last: string, total: number) =>
            `${total === 1 ? "1 step" : `${total} steps`} · ${first} → ${last}`,
    },
    start: {
        open: "Start run",
        title: "Start a run",
        body: "A run writes pages for the selected targets and stops itself at the dollar cap you set here.",
        pages: "Target pages",
        selected: (count: number) => (count === 1 ? "1 page selected" : `${count} pages selected`),
        noPages: "Select at least one page.",
        search: "Path prefix",
        publishMode: "Publish mode",
        kind: "Kind",
        template: "Template",
        templateAuto: "Resolved per page",
        templateHint: "Left automatic, each page uses the template its own overrides resolve to.",
        cap: "Dollar cap",
        capHint: "The run pauses itself once spend passes this. Zero means no cap at all.",
        capZero: "With no cap this run will not stop itself on spend.",
        tokenCap: "Token cap",
        tokenCapHint: "The run pauses itself once it has used this many tokens. Zero means no cap at all.",
        tokenCapZero: "With no cap this run will not stop itself on tokens.",
        kindDoes: {
            generate: "Writes each page from its template and publishes it, then links the pages around it.",
            relink: "Reads each page from WordPress and places the links its rules ask for. The body is left as it is and no model is called.",
            audit: "Runs the page steps you choose without a recipe of its own.",
            sync: "Reads the whole site back into the page map. The pages it names are ignored.",
            import: "Runs the page steps you choose without a recipe of its own.",
            repair: "Moves each page under the parent its path asks for, without rewriting it. No model is called.",
            revert: "A revert is started from the run it undoes, on that run's page.",
            custom: "Runs exactly the steps of the template, whatever they are.",
        },
        estimate: "Price this run",
        estimated: (usd: string, tokens: string) => `${usd} · about ${tokens} tokens`,
        estimateFirst: "Price the run before starting it.",
        overCap: "The estimate is above the cap, so this run will pause before it finishes.",
        confirm: "Start the run",
        cancel: "Cancel",
        started: "Run started",
    },
    review: {
        title: "Review",
        close: "Close",
        openPage: "Open the page",
        moveItems: "move between items",
        position: (at: number, total: number) => `item ${at} of ${total}`,
        waitingOn: (step: string) => `The artifact appears when ${step} returns.`,
        driftRefused: "Publish stopped — the page changed in WordPress",
        driftRefusedBody:
            "This run refuses drift, so it did not overwrite the edit. What changed cannot be shown: raw WordPress content is not exposed by any binding.",
        attempt: (attempts: number) => (attempts === 1 ? "attempt 1" : `${attempts} attempts`),
        noArtifacts: "Nothing to review yet",
        noArtifactsBody:
            "This item has produced no artifact so far. Each step writes its own, and they appear as the run reaches them.",
        loading: "Loading the artifacts of this item",
        unreadable: "This artifact could not be read",
        unreadableBody: "It is not in the shape this build expects, so nothing is shown rather than something wrong.",
        purged: "Removed by the retention sweep",
        purgedBody: (days: number) =>
            `Bodies, drafts and images are dropped ${days} days after the page publishes. The row stays, and the compliance findings and the judge score below are untouched.`,
        purgedBodyUnknown:
            "Bodies, drafts and images are dropped once the retention window passes on a published page. The row stays, and the compliance findings and the judge score below are untouched.",
        noDiff: "There is no comparison with the live page — raw WordPress content is not exposed by any binding.",
        kinds: {
            link_context: "Targets",
            draft: "Draft",
            body_html: "Body",
            meta: "Meta",
            images: "Images",
            validation_report: "Links & compliance",
            judge_report: "Judge",
            publish_result: "Publish",
            relink_result: "Neighbours",
            sync_result: "Sync",
            final_report: "Report",
            revert_result: "Revert",
        },
        body: {
            preview: "Sandboxed preview",
            empty: "The body artifact is empty.",
        },
        links: {
            owed: "Owed to the graph",
            owedEmpty: "The graph asked this page for no links.",
            satisfied: "satisfied",
            missing: "missing",
            required: "required",
            optional: "optional",
            relation: { up: "up", down: "down", sibling: "sideways" },
            actual: "Links on the page",
            actualEmpty: "No link was recorded on this page.",
            classes: {
                graph: "graph",
                self: "self",
                external: "external",
                unknown_internal: "unknown internal",
            },
            classesNote:
                "Graph links come from the placements the run made; the rest are the links compliance flagged, so a clean non-graph link leaves no record.",
            findings: "Findings",
            errors: (count: number) => (count === 1 ? "1 error — the item fails" : `${count} errors — the item fails`),
            warnings: (count: number) => (count === 1 ? "1 warning" : `${count} warnings`),
            clean: "No compliance finding on this page.",
            warningsDoNotFail: "A warning does not fail the item; an error does.",
            score: (score: number) => `score ${score.toFixed(2)}`,
        },
        judge: {
            score: "Score",
            outOf: "out of 1.00",
            issues: "Issues",
            suggestions: "Suggestions",
            none: "The judge raised nothing.",
            rejudge: "Judge this page again",
            rejudging: "Judging",
            rejudgeHint: "This calls the judge model and spends tokens. It never runs on its own.",
            rejudged: (tokens: number) => `Judged again for ${tokens} tokens.`,
            unavailable: "The judge did not return a score for this item.",
        },
        publish: {
            result: "Result",
            created: "created",
            updated: "updated",
            status: "WordPress status",
            wpId: "WordPress id",
            hash: "Content hash",
            seoApplied: "SEO fields written",
            skipped: "Skipped",
            liveUrl: "Live URL",
        },
        draft: { sections: "Sections", summary: "Summary" },
        images: {
            featured: "Featured image",
            problems: "What the step could not do",
            none: "No image was placed.",
        },
        relink: {
            linked: "linked",
            conflicts: "conflicts",
            skipped: "skipped",
            neighbours: "Neighbours",
            none: "No neighbour was touched.",
        },
        report: {
            score: "Final score",
            errors: "errors",
            warnings: "warnings",
        },
    },
};
