export const schedules = {
    title: "Schedules",
    loading: "Loading the schedules",
    create: "New schedule",
    filter: {
        label: "Which schedules",
        all: "All",
        on: "On",
        off: "Off",
    },
    columns: {
        name: "Name",
        targets: "Targets",
        cadence: "Cadence",
        next: "Next run",
        last: "Last run",
        enabled: "On",
    },
    row: {
        off: "Off",
        never: "Not yet",
        toggle: (name: string) => `Turn ${name} on or off`,
    },
    panel: {
        create: "New schedule",
        name: "Name",
        namePlaceholder: "Draft the planned guides",
        cadence: "Cadence",
        interval: "Interval",
        cron: "Cron",
        cronPlaceholder: "0 3 * * *",
        every: "Every",
        units: {
            minutes: "minutes",
            hours: "hours",
            days: "days",
        },
        work: "What it runs",
        template: "Template",
        anyTemplate: "The site default",
        publish: "Publishing",
        targets: "What it picks up",
        status: "Page status",
        anyStatus: "Any status",
        entity: "Under an entity",
        anyEntity: "Any entity",
        limit: "Most pages per run",
        budget: "Budget",
        maxUsd: "Spend cap",
        maxTokens: "Token cap",
        noCap: "No cap",
        recipe: "Steps",
        templateRecipe: "The template's own recipe",
        lastRun: "Last run",
        allRuns: "All runs of this site",
        createdBy: (actor: string) => `Added by ${actor}`,
        actors: {
            user: "you",
            agent: "the agent",
            schedule: "a schedule",
        },
        save: "Save schedule",
        runNow: "Run now",
        enable: "Enable",
        disable: "Disable",
        delete: "Delete schedule",
        deleteBody: "The schedule stops. The runs it already started are kept.",
        close: "Close the panel",
        nothingSelected: "Choose a schedule to edit it.",
    },
    cadence: {
        none: "No cadence set",
        nextIn: (words: string) => `next ${words}`,
    },
    statuses: {
        planned: "Planned",
        exists: "Exists",
        published: "Published",
        archived: "Archived",
    },
    publishModes: {
        draft: "Draft",
        publish: "Publish",
    },
    targets: {
        any: (limit: number) => `Up to ${limit} pages`,
        status: (limit: number, status: string) => `Up to ${limit} ${status} pages`,
        entity: (limit: number, entity: string) => `Up to ${limit} pages of ${entity}`,
        both: (limit: number, status: string, entity: string) => `Up to ${limit} ${status} pages of ${entity}`,
    },
    stats: {
        items: "Items",
        done: "Done",
        failed: "Failed",
        spent: "Spent",
    },
    runNow: {
        started: (targets: number) => (targets === 1 ? "Started on 1 page" : `Started on ${targets} pages`),
        refused: "Nothing to run",
        busy: "Starting",
    },
};
