export const settings = {
    title: "Settings",
    subtitle: "How this workspace talks to WordPress and to the models, and how it protects itself.",
    tabs: {
        general: "General",
        models: "Models",
        security: "Security",
        about: "About",
    },
    search: "Search settings",
    changedOnly: "Changed only",
    reread: "Reread",
    changed: "Changed",
    reset: "Reset to the default",
    undocumented: (key: string) => `${key} has no label yet, so it is shown by its key.`,
    hint: {
        isDefault: "This is the default.",
        range: (min: string, max: string) => `Between ${min} and ${max}.`,
        lowerBound: (min: string) => `At least ${min}.`,
        upperBound: (max: string) => `At most ${max}.`,
        required: "This must not be empty.",
    },
    problem: {
        range: (min: string, max: string) => `Enter a value between ${min} and ${max}.`,
        lowerBound: (min: string) => `Enter a value of at least ${min}.`,
        upperBound: (max: string) => `Enter a value of at most ${max}.`,
        empty: "This must not be empty.",
        whole: "Enter a whole number.",
        duration: "Enter a length of time such as 30s, 5m or 1h30m.",
    },
    groups: {
        runs: { title: "Runs", blurb: "How many pages are generated at once and how long the work may take." },
        wp: { title: "WordPress", blurb: "How this application talks to a site." },
        llm: { title: "Models", blurb: "How model calls are made, and where they are sent." },
        agent: { title: "Agent", blurb: "What the chat agent may do in one turn." },
        browser: { title: "Browser", blurb: "Where a link from this application opens." },
        images: { title: "Images", blurb: "Where generated images come from and where they are kept." },
        import: { title: "Import", blurb: "What a spreadsheet import will accept." },
        schedules: { title: "Schedules", blurb: "How often a schedule is checked." },
        sync: { title: "Sync", blurb: "How a site is read back." },
    },
    enumLabels: {
        "llm.recordReplayMode": {
            off: "Off",
            record: "Record to fixtures",
            replay: "Replay from fixtures",
        },
    },
    keys: {
        "agent.historyBudgetChars": {
            label: "History budget",
            help: "How many characters of a conversation are sent back to the model on the next turn.",
        },
        "agent.loopLimit": {
            label: "Tool calls per turn",
            help: "How many times the agent may call a tool before it has to answer.",
        },
        "agent.maxToolResultBytes": {
            label: "Tool result ceiling",
            help: "A tool result larger than this is cut before the model sees it.",
        },
        "agent.turnTimeout": {
            label: "Turn timeout",
            help: "How long one answer may take before the turn is stopped.",
        },
        "browser.torPath": {
            label: "Tor Browser",
            help: "The full path to firefox.exe inside Tor Browser. Left empty, the usual places are searched.",
        },
        "images.localDir": {
            label: "Image folder",
            help: "Where generated images are written. Empty means the workspace folder.",
        },
        "images.openaiModel": {
            label: "Image model",
            help: "The OpenAI model asked for an image.",
        },
        "import.maxRows": {
            label: "Import row ceiling",
            help: "A spreadsheet with more rows than this is refused rather than half read.",
        },
        "llm.anthropic.baseUrl": {
            label: "Anthropic endpoint",
            help: "An http or https address. Empty means the provider's own endpoint.",
        },
        "llm.gemini.location": {
            label: "Gemini location",
            help: "The Vertex AI region, for example europe-west4.",
        },
        "llm.gemini.projectId": {
            label: "Gemini project",
            help: "The Google Cloud project Vertex AI bills.",
        },
        "llm.geminiOpenai.baseUrl": {
            label: "Gemini OpenAI endpoint",
            help: "An http or https address for the OpenAI-compatible Gemini surface.",
        },
        "llm.openai.baseUrl": {
            label: "OpenAI endpoint",
            help: "An http or https address. Empty means the provider's own endpoint.",
        },
        "llm.recordReplayMode": {
            label: "Record and replay",
            help: "Records model calls to fixtures, or answers from them. For support and testing.",
        },
        "llm.retries": {
            label: "Model retries",
            help: "How many times a failed model call is tried again before the step fails.",
        },
        "llm.timeout": {
            label: "Model timeout",
            help: "How long one model call may take before it is abandoned.",
        },
        "runs.artifactRetentionDays": {
            label: "Keep artifacts for",
            help: "Days a published page keeps its draft, body and images before the sweep removes them.",
        },
        "runs.deadline": {
            label: "Run deadline",
            help: "How long a whole run may take before it fails. A large site legitimately takes days.",
        },
        "runs.eventRetentionDays": {
            label: "Keep run events for",
            help: "Days the step by step history of a run is kept.",
        },
        "runs.leaseDuration": {
            label: "Worker lease",
            help: "How long a worker holds a page before another may take it. Recovery after a crash waits this long.",
        },
        "runs.perSite": {
            label: "Workers per site",
            help: "How many pages of one site are generated at the same time.",
        },
        "runs.stepTimeout": {
            label: "Step timeout",
            help: "How long one step of one page may take before it fails and is retried.",
        },
        "runs.sweepInterval": {
            label: "Sweep interval",
            help: "How often expired artifacts and run events are removed.",
        },
        "runs.workers": {
            label: "Workers",
            help: "How many pages are generated at the same time across every site.",
        },
        "schedules.tickInterval": {
            label: "Schedule tick",
            help: "How often schedules are checked for work that is due.",
        },
        "sync.batchSize": {
            label: "Sync batch",
            help: "How many pages are read from WordPress in one request.",
        },
        "wp.proxyUrl": {
            label: "Proxy",
            help: "An http, https, socks5 or socks5h address. Empty means no proxy, never the system one.",
        },
        "wp.rateLimitPerSecond": {
            label: "Requests per second",
            help: "The ceiling on how fast this application talks to a site.",
        },
        "wp.retries": {
            label: "WordPress retries",
            help: "How many times a failed request to a site is tried again.",
        },
        "wp.timeout": {
            label: "WordPress timeout",
            help: "How long one request to a site may take before it is abandoned.",
        },
    },
    models: {
        keys: {
            title: "Provider keys",
            blurb: "A key is stored sealed and never read back. Revoking one stops every role that resolves to it.",
            provider: "Provider",
            state: "Key",
            stored: "Stored",
            missing: "Not stored",
            store: "Store",
            replace: "Replace",
            revoke: "Revoke",
            test: "Test",
            testing: "Testing",
            apiKey: "API key",
            apiKeyHint: "Pasted once. It is sealed with the master key and never shown again.",
            storeTitle: (provider: string) => `Store the ${provider} key`,
            revokeTitle: (provider: string) => `Revoke the ${provider} key`,
            revokeBody: (provider: string) =>
                `Every role pointing at a ${provider} model will start failing until a key is stored again.`,
            tested: (ms: number, tokens: number) => `answered in ${ms} ms, ${tokens} tokens`,
            noModel: "The catalog carries no model for this provider, so there is nothing to test with.",
        },
        profiles: {
            title: "Roles",
            blurb: "Which model does which job. A role with no choice of its own falls back to the shipped default.",
            role: "Role",
            choice: "Model",
            effective: "In use",
            source: "From",
            sourceGlobal: "Chosen here",
            sourceSeeded: "Shipped default",
            sourceNone: "Nothing set",
            labels: {
                writer: "Writer",
                editor: "Editor",
                linker: "Linker",
                judge: "Judge",
                chat: "Chat",
                image: "Images",
                titler: "Chat names",
            },
        },
        catalog: {
            title: "Model catalog",
            blurb: "What each model costs and how fast it may be called. Editing a row overrides the shipped entry.",
            model: "Model",
            context: "Context",
            maxOutput: "Max out",
            inputPrice: "In $/M",
            outputPrice: "Out $/M",
            rpm: "RPM",
            tpm: "TPM",
            flags: "Carries",
            structured: "JSON",
            images: "Images",
            reasoning: "Reasoning",
            add: "Add a model",
            edit: "Edit",
            disable: "Disable",
            addTitle: "Add a model",
            editTitle: (model: string) => `Edit ${model}`,
            disableTitle: (model: string) => `Disable ${model}`,
            disableBody:
                "The model stops being offered to every role. Bringing it back means adding it again with the same numbers.",
            field: {
                provider: "Provider",
                model: "Model",
                contextTokens: "Context tokens",
                maxOutputTokens: "Max output tokens",
                inputUsdPerM: "Input $ per million",
                outputUsdPerM: "Output $ per million",
                rpm: "Requests per minute",
                tpm: "Tokens per minute",
            },
        },
        spend: {
            title: "Spend",
            blurb: "Everything this workspace has spent on model calls since it was created.",
            spent: "Spent",
            input: "Input tokens",
            output: "Output tokens",
            total: "Total tokens",
            calls: "Calls",
        },
    },
    security: {
        lock: {
            title: "Lock",
            blurb: "Locking closes the database and stops the scheduler, the agent and every run.",
            protected: "A master password protects this workspace.",
            unprotected: "No master password is set, so the workspace opens with your Windows account alone.",
            cannotLock: "Set a master password first; without one nothing could unlock the workspace again.",
            confirmTitle: "Lock the workspace",
            confirmBody: (running: number) =>
                running === 0
                    ? "The scheduler and the agent stop. You will be asked for the master password to carry on."
                    : `${running} running ${running === 1 ? "run" : "runs"} will be stopped, along with the scheduler and the agent.`,
            confirm: "Lock now",
        },
        password: {
            title: "Master password",
            setBlurb: "A master password seals the site credentials and the model keys.",
            changeBlurb: "Changing the password reseals everything this workspace holds.",
            current: "Current password",
            next: "New password",
            repeat: "Repeat the new password",
            set: "Set the password",
            change: "Change the password",
            mismatch: "The two new passwords are not the same.",
            unchanged: "The new password is the one already in use.",
            remove: "Remove the password",
            removeTitle: "Remove the master password",
            removeBody:
                "The workspace falls back to your Windows account alone. It can no longer be locked, and anyone who can sign in as you can open it.",
            removeConfirm: "Remove it",
        },
        backup: {
            title: "Backup",
            blurb: "One encrypted archive holds the whole workspace.",
            choose: "Choose a file",
            noFile: "No file chosen yet.",
            password: "Archive password",
            passwordHint: "This is not the master password. Lose it and the archive cannot be read.",
            filter: "Postulator backup",
            export: "Export",
            exporting: "Exporting",
            written: (path: string, size: string) => `${size} written to ${path}`,
            import: "Import",
            importing: "Importing",
            importTitle: "Replace this workspace",
            importBody:
                "The current database is replaced by the archive. Anything not in the archive is gone, the scheduler, the agent and the run engine are restarted, and site passwords sealed on another machine have to be entered again.",
            importConfirm: "Replace it",
            imported: "The workspace was replaced.",
        },
    },
    about: {
        title: "About",
        version: "Version",
        commit: "Commit",
        built: "Built",
        recheck: "Check again",
        carries: {
            title: "What this build carries",
            settings: "Declared settings",
            models: "Models in the catalog",
            providers: "Providers with a key",
            tools: "Agent tools",
        },
    },
};
