export const settings = {
    title: "Settings",
    tabs: {
        models: "Models",
        runs: "Runs",
        agent: "Agent",
        browser: "Browser",
        security: "Security",
        about: "About",
    },
    changed: "Changed",
    isDefault: "Default",
    reset: "Reset to the default",
    advanced: "Advanced",
    advancedCount: (count: number) => (count === 1 ? "1 setting" : `${count} settings`),
    units: {
        pages: "pages",
        days: "days",
        times: "times",
        perSecond: "a second",
        steps: "steps",
        rows: "rows",
        characters: "characters",
        bytes: "bytes",
    },
    sections: {
        modelCalls: "Model calls",
        endpoints: "Endpoints",
        images: "Images",
        pace: "Pace",
        limits: "Time limits",
        history: "What is kept",
        cleanup: "Recovery and cleanup",
        wordpress: "Talking to WordPress",
        importing: "Importing",
        schedules: "Schedules",
        other: "Everything else",
        agentLimits: "One answer",
        agentDepth: "How much the agent reads",
        tor: "Tor Browser",
        browserOther: "Everything else",
    },
    hint: {
        range: (min: string, max: string) => `Between ${min} and ${max}.`,
        lowerBound: (min: string) => `At least ${min}.`,
        upperBound: (max: string) => `At most ${max}.`,
        required: "This must not be empty.",
    },
    problem: {
        range: (min: string, max: string) => `Enter a value between ${min} and ${max}.`,
        lowerBound: (min: string) => `Enter a value of at least ${min}.`,
        upperBound: (max: string) => `Enter a value of at most ${max}.`,
        empty: "This must not be empty.",
        whole: "Enter a whole number.",
        number: "Enter a number.",
        duration: "Enter a length of time such as 30s, 5m or 1h30m.",
    },
    enumLabels: {
        "llm.recordReplayMode": {
            off: "Off",
            record: "Record to files",
            replay: "Replay from files",
        },
        "images.openaiQuality": {
            low: "Low",
            medium: "Medium",
            high: "High",
            auto: "Let OpenAI choose",
        },
    },
    keys: {
        "agent.historyBudgetChars": {
            label: "Conversation kept in mind",
            help: "How much of a conversation goes back to the model with your next question.",
        },
        "agent.historyToolResultBytes": {
            label: "Tool answer kept for the next question",
            help: "How much of a tool's answer is kept in the conversation. The agent reads more than this at the time; only this much goes back to the model afterwards.",
        },
        "agent.loopLimit": {
            label: "Tool steps per answer",
            help: "How many things the agent may do before it has to answer you.",
        },
        "agent.maxToolResultBytes": {
            label: "Largest tool answer read",
            help: "A longer answer from a tool is cut before the agent reads it.",
        },
        "agent.turnTimeout": {
            label: "Time limit for one answer",
            help: "An answer that takes longer than this is stopped.",
        },
        "browser.torPath": {
            label: "Tor Browser",
            help: "The file Tor Browser starts from. Left empty, the usual places are searched.",
        },
        "images.localDir": {
            label: "Folder of images to pick from",
            help: "The folder a template whose images come from a folder picks them from, by file name. Empty means no folder, and such a template gets no image. Takes effect after a restart.",
        },
        "images.openaiModel": {
            label: "Model that draws images",
            help: "The OpenAI model asked for every drawn image, gpt-image-2 unless you name another. Takes effect after a restart.",
        },
        "images.openaiQuality": {
            label: "Image quality",
            help: "Higher quality costs several times more per image. Letting OpenAI choose usually picks the dearest. Takes effect after a restart.",
        },
        "import.maxRows": {
            label: "Largest spreadsheet accepted",
            help: "A spreadsheet with more rows than this is refused rather than half read.",
        },
        "llm.anthropic.baseUrl": {
            label: "Anthropic endpoint",
            help: "An http or https address. Empty means Anthropic's own endpoint.",
        },
        "llm.gemini.location": {
            label: "Google Cloud region",
            help: "The Vertex AI region, for example europe-west4.",
        },
        "llm.gemini.projectId": {
            label: "Google Cloud project",
            help: "The project Vertex AI bills.",
        },
        "llm.geminiOpenai.baseUrl": {
            label: "Gemini endpoint",
            help: "An http or https address for the OpenAI-compatible Gemini surface.",
        },
        "llm.openai.baseUrl": {
            label: "OpenAI endpoint",
            help: "An http or https address. Empty means OpenAI's own endpoint.",
        },
        "llm.recordReplayMode": {
            label: "Record and replay model calls",
            help: "Records model calls to files, or answers from them. For support and testing.",
        },
        "llm.retries": {
            label: "Retries after a failed call",
            help: "How many times a failed model call is tried again before the step fails.",
        },
        "llm.timeout": {
            label: "Time limit for one model call",
            help: "A model call that takes longer than this is abandoned.",
        },
        "runs.artifactRetentionDays": {
            label: "Keep drafts and images for",
            help: "After this, a published page's draft, body and images are removed.",
        },
        "runs.deadline": {
            label: "Time limit for a whole run",
            help: "A run that takes longer than this fails. A large site legitimately takes days.",
        },
        "runs.eventRetentionDays": {
            label: "Keep run history for",
            help: "After this, the step by step history of a run is removed.",
        },
        "runs.leaseDuration": {
            label: "How long a worker holds a page",
            help: "After a crash, a page is picked up again once this has passed.",
        },
        "runs.perSite": {
            label: "Pages at once on one site",
            help: "How many pages of a single site are written at the same time.",
        },
        "runs.stepTimeout": {
            label: "Time limit for one step",
            help: "A step that takes longer than this fails and is tried again.",
        },
        "runs.sweepInterval": {
            label: "How often old files are cleared",
            help: "How often anything past the retention above is removed.",
        },
        "runs.workers": {
            label: "Pages generated at once",
            help: "How many pages are written at the same time, across every site.",
        },
        "schedules.tickInterval": {
            label: "How often schedules are checked",
            help: "How often this application looks for a schedule that is due.",
        },
        "sync.batchSize": {
            label: "Pages read back in one request",
            help: "How many pages are read from WordPress at a time.",
        },
        "wp.proxyUrl": {
            label: "Proxy for site requests",
            help: "An http, https, socks5 or socks5h address. Empty means no proxy, never the system one.",
        },
        "wp.rateLimitPerSecond": {
            label: "Requests a second to a site",
            help: "The ceiling on how fast this application talks to a site. Lower it for a shared host.",
        },
        "wp.retries": {
            label: "Retries after a failed request",
            help: "How many times a failed request to a site is tried again.",
        },
        "wp.timeout": {
            label: "Time limit for one request to a site",
            help: "A request that takes longer than this is abandoned.",
        },
    },
    models: {
        providers: {
            openai: "OpenAI",
            anthropic: "Anthropic",
            gemini: "Google Gemini",
            "gemini-openai": "Gemini over the OpenAI API",
        },
        keys: {
            title: "Provider keys",
            stored: "Key stored",
            missing: "No key",
            store: "Set key",
            replace: "Replace key",
            revoke: "Revoke",
            test: "Test",
            testing: "Testing",
            apiKey: "API key",
            apiKeyHint: "Pasted once. It is sealed with the master key and never shown again.",
            storeTitle: (provider: string) => `Set the ${provider} key`,
            revokeTitle: (provider: string) => `Revoke the ${provider} key`,
            revokeBody: (provider: string) =>
                `Every role pointing at a ${provider} model will start failing until a key is set again.`,
            tested: (ms: number, tokens: number) => `Answered in ${ms} ms, ${tokens} tokens`,
            noKey: "Set a key before testing it.",
        },
        profiles: {
            title: "Which model does which job",
            role: "Job",
            choice: "Model",
            effective: "In use",
            sourceGlobal: "Chosen here",
            sourceNone: "Nothing set",
            labels: {
                writer: "Writes the body",
                editor: "Edits",
                linker: "Places links",
                judge: "Judges quality",
                chat: "Chat",
                image: "Images",
                titler: "Titles",
            },
            imagesElsewhere: "Images are drawn by the model named under Settings, Images.",
        },
        catalog: {
            open: "Manage models",
            title: "Model catalog",
            subtitle: (count: number) => `${count} models a role can be pointed at.`,
            close: "Done",
            model: "Model",
            context: "Context",
            maxOutput: "Max out",
            inputPrice: "In $/M",
            outputPrice: "Out $/M",
            rpm: "RPM",
            tpm: "TPM",
            structured: "JSON",
            images: "Images",
            reasoning: "Reasoning",
            add: "Add a model",
            edit: "Edit",
            disable: "Disable",
            addTitle: "Add a model",
            editTitle: (model: string) => `Edit ${model}`,
            disableTitle: (model: string) => `Disable ${model}`,
            disableBody:
                "The model stops being offered to every role. Bringing it back means adding it again with the same numbers.",
            field: {
                provider: "Provider",
                model: "Model",
                contextTokens: "Context tokens",
                maxOutputTokens: "Max output tokens",
                inputUsdPerM: "Input $ per million",
                outputUsdPerM: "Output $ per million",
                rpm: "Requests per minute",
                tpm: "Tokens per minute",
                effort: "Reasoning effort",
            },
            effortHint: "How long the model may think before it answers. Its output budget is raised to match.",
            effortDefault: "The provider decides",
            effortLabels: {
                none: "None",
                low: "Low",
                medium: "Medium",
                high: "High",
                xhigh: "Highest",
            },
        },
        spend: {
            title: "Spent on models",
            calls: (count: number) => (count === 1 ? "1 call" : `${count} calls`),
            tokens: (total: string) => `${total} tokens`,
            cached: (percent: number) => `${percent}% cached`,
            cachedHint: "How much of what was sent to the models the providers served from their own cache, at a lower rate.",
        },
    },
    browser: {
        title: "Tor Browser",
        found: "Found",
        missing: "Not found",
        sourceDetected: "Detected",
        sourceChosen: "Chosen",
        startsFrom: "Starts from",
        missingBody: "Tor Browser was not found in the usual places. Choose the file it starts from.",
        choose: "Choose…",
        chooseTitle: "Choose Tor Browser",
        filter: "Tor Browser",
        clear: "Search again",
        clearHint: "Forget the chosen file and look in the usual places.",
        test: "Test in Tor",
        testHint: "Opens the Tor Project's check page in Tor Browser.",
        testUrl: "https://check.torproject.org/",
        testBlocked: "Tor Browser is not installed, so there is nothing to test.",
        notTor: "That file is not Tor Browser. Choose the firefox.exe inside Tor Browser's own Browser folder.",
    },
    security: {
        lock: {
            title: "Lock",
            stateSet: "Set",
            stateUnset: "Not set",
            protected: "A master password protects this workspace.",
            unprotected: "No master password is set, so this workspace opens with your Windows account alone.",
            cannotLock: "Set a master password first; without one nothing could unlock this workspace again.",
            confirmTitle: "Lock the workspace",
            confirmBody: (running: number) =>
                running === 0
                    ? "The scheduler and the agent stop. You will be asked for the master password to carry on."
                    : `${running} running ${running === 1 ? "run" : "runs"} will be stopped, along with the scheduler and the agent.`,
            confirm: "Lock now",
        },
        password: {
            title: "Master password",
            set: "Set a password…",
            change: "Change…",
            remove: "Remove…",
            setTitle: "Set a master password",
            changeTitle: "Change the master password",
            setBody: "A master password seals the site credentials and the model keys.",
            changeBody: "Changing the password reseals everything this workspace holds.",
            current: "Current password",
            next: "New password",
            repeat: "Repeat the new password",
            save: "Save",
            mismatch: "The two new passwords are not the same.",
            unchanged: "The new password is the one already in use.",
            removeTitle: "Remove the master password",
            removeBody:
                "This workspace falls back to your Windows account alone. It can no longer be locked, and anyone who can sign in as you can open it.",
            removeConfirm: "Remove it",
        },
        backup: {
            title: "Backup",
            running: "A run is active. Replacing this workspace will stop it.",
            openRun: "Open the run",
            exportTitle: "Write an archive",
            exportBody: "One encrypted archive holds the whole workspace.",
            importTitle: "Replace this workspace",
            importBody: "Everything here is replaced by what the archive holds.",
            choose: "Choose a file…",
            noFile: "No file chosen yet.",
            password: "Archive password",
            passwordHint: "This is not the master password. Lose it and the archive cannot be read.",
            filter: "Postulator backup",
            export: "Export",
            exporting: "Exporting",
            written: (path: string, size: string) => `${size} written to ${path}`,
            import: "Replace…",
            importing: "Replacing",
            importConfirmTitle: "Replace this workspace",
            importConfirmBody:
                "The current database is replaced by the archive. Anything not in the archive is gone, the scheduler, the agent and the run engine are restarted, and site passwords sealed on another machine have to be entered again.",
            importConfirm: "Replace it",
        },
    },
    about: {
        title: "This build",
        version: "Version",
        commit: "Commit",
        built: "Built",
        recheck: "Check again",
    },
};
