export const sites = {
    title: "Sites",
    subtitle: "Every graph, page map and run below belongs to exactly one WordPress site.",
    add: "Add site",
    addTitle: "Add a site",
    editTitle: "Edit site",
    open: "Open this site",
    edit: "Edit",
    anyStatus: "Any status",
    columns: {
        name: "Name",
        baseUrl: "Base URL",
        status: "Status",
        plugin: "Plugin",
        created: "Added",
    },
    field: {
        name: "Name",
        nameHint: "What you call this site inside Postulator.",
        baseUrl: "Base URL",
        baseUrlHint: "The WordPress home URL, for example https://example.com.",
        username: "WordPress user",
        usernameHint: "The account the application password belongs to.",
        password: "Application password",
        passwordHint: "Generated under Users → Profile in WordPress, not the login password.",
        passwordKeep: "Leave empty to keep the stored password.",
        allowInsecure: "Allow plain http",
        allowInsecureHint: "Credentials travel unencrypted. Only for a local install.",
        localAddress: "This address is on your own machine or network, so plain http is accepted.",
    },
    insecureWarning: "This site is reached over plain http, so the application password crosses the network unencrypted.",
    test: "Test connection",
    testing: "Testing",
    reach: {
        ok: "The site answered and the credentials work.",
        upgradeRequired: "The site answered on http and asked for https.",
        unauthorized: "The site answered but refused these credentials.",
        unreachable: "The site did not answer.",
    },
    useSuggested: (url: string) => `Use ${url}`,
    detected: (name: string) => `Reported name: ${name}`,
    woo: "WooCommerce detected",
    deleteTitle: "Delete this site",
    deleteBody: (name: string) =>
        `${name} goes, and with it its page map, entities and edges, runs and their artifacts, site templates and link policies, schedules, saved import mappings and agent conversations. Nothing on WordPress is touched.`,
    deleteConfirm: "Delete the site",
    pickSite: "Pick a site on the left to see its plugin state and credentials.",
    plugin: {
        title: "Companion plugin",
        installed: (version: string) => (version === "" ? "Installed" : `Installed, version ${version}`),
        missingTitle: (name: string) => `The companion plugin is not installed on ${name}`,
        missingBody: "Postulator falls back to the plain WordPress REST API. In that mode:",
        losses: [
            "Products and product categories stay invisible to a sync.",
            "SEO meta is read-only — title and description cannot be written back.",
            "relink_neighbors is skipped on every item, so neighbour links are never repaired.",
        ],
        recheck: "Check again",
        download: "Save the plugin zip",
        saved: (path: string) => `Companion plugin written to ${path}`,
        capabilities: "Capabilities",
        seo: "SEO plugin",
        noSeo: "none detected",
        noCapabilities: "none reported",
    },
};
