export const sites = {
    statuses: {
        active: "Active",
        paused: "Paused",
        error: "Not reachable",
    },
    title: "Sites",
    add: "Add site",
    addTitle: "Add a site",
    editTitle: "Edit site",
    open: "Open this site",
    edit: "Edit",
    anyStatus: "Any",
    search: "Search sites",
    noMatches: "No site matches that.",
    emptyTitle: "No sites yet",
    emptyBody: "Add the WordPress site Postulator should work on.",
    defaults: {
        title: "Defaults",
        template: "Template",
        linkPolicy: "Link policy",
        modelRoles: "Model roles",
        none: "None chosen",
        roles: (count: number) => (count === 1 ? "1 role set" : `${count} roles set`),
    },
    columns: {
        name: "Name",
        baseUrl: "Base URL",
        status: "Status",
        plugin: "Plugin",
        created: "Added",
    },
    field: {
        name: "Name",
        baseUrl: "Base URL",
        baseUrlExample: "https://example.com",
        username: "WordPress user",
        password: "Application password",
        passwordTooltip: "Generated under Users then Profile in WordPress, not the login password.",
        passwordKeep: "Leave empty to keep the stored password",
        allowInsecure: "Allow plain http",
    },
    insecureWarning: "This site is reached over plain http, so the application password crosses the network unencrypted.",
    test: "Test connection",
    testing: "Testing",
    reach: {
        ok: "The site answered and the credentials work.",
        upgradeRequired: "The site answered on http and asked for https.",
        unauthorized: "The site answered but refused these credentials.",
        unreachable: "The site did not answer.",
    },
    useSuggested: (url: string) => `Use ${url}`,
    detected: (name: string) => `Reported name: ${name}`,
    woo: "WooCommerce detected",
    deleteTitle: "Delete this site",
    deleteBody: (name: string) =>
        `${name} goes, and with it twelve tables: its pages and their links, its entities, their anchors and their edges, its runs with their items, artifacts, step records and event log, its own templates, template overrides and link policies, its schedules, its saved import mappings and its agent conversations with their messages. None of it can be brought back, and the stored application password goes with it. Nothing on WordPress is touched: the pages stay on the site.`,
    deleteConfirm: "Delete the site",
    plugin: {
        title: "Companion plugin",
        installed: (version: string) => (version === "" ? "Installed" : `Installed, version ${version}`),
        missingTitle: (name: string) => `The companion plugin is not installed on ${name}`,
        missingBody: "Products stay invisible to a sync, SEO meta is read-only and neighbour links are never repaired.",
        recheck: "Check again",
        download: "Save the plugin zip",
        saved: (path: string) => `Companion plugin written to ${path}`,
        capabilities: "Capabilities",
        capabilityNames: {
            bulk: "bulk writes",
            seo_meta: "SEO meta",
            content_hash: "change detection",
            raw: "raw content",
            preview: "draft previews",
        } as Readonly<Record<string, string>>,
        seo: "SEO plugin",
        seoNames: {
            yoast: "Yoast SEO",
            rankmath: "Rank Math",
        } as Readonly<Record<string, string>>,
        noSeo: "none detected",
        noCapabilities: "none reported",
    },
};
