export const templates = {
    title: "Templates",
    loading: "Loading templates",
    tabs: {
        templates: "Templates",
        policies: "Link policies",
    },
    columns: {
        name: "Name",
        scope: "Scope",
        pageKind: "Page kind",
        version: "Version",
        default: "Default",
        updated: "Updated",
    },
    search: "Search templates",
    searchLoaded: "Search looks through the templates already loaded.",
    filters: {
        scope: "Scope",
        scopeAll: "All",
        pageKind: "Page kind",
        anyPageKind: "Any page kind",
        sort: "Sort",
    },
    sortOptions: {
        nameAsc: "Name A–Z",
        nameDesc: "Name Z–A",
        newest: "Newest first",
        oldest: "Oldest first",
    },
    scope: {
        global: "Every site",
        site: "This site",
    },
    pageKinds: {
        hub: "Hub",
        category: "Category",
        guide: "Guide",
        comparison: "Comparison",
        product: "Product",
    },
    roles: {
        writer: "Body",
        editor: "Editing",
        linker: "Links",
        judge: "Scoring",
        chat: "Chat",
        image: "Images",
        titler: "Titles",
    },
    siteDefault: "Site default",
    setDefault: "Set as site default",
    alreadyDefault: "This template already is the site default.",
    openEditor: "Open editor",
    duplicate: "Duplicate",
    copyName: (name: string) => `${name} copy`,
    copyNameNumbered: (name: string, index: number) => `${name} copy ${index}`,
    moreActions: "More actions",
    noMatch: "No template matches",
    noMatchBody: "Nothing here matches the search or the filters.",
    clearFilters: "Clear the filters",
    sectionCount: (count: number) => (count === 1 ? "1 section" : `${count} sections`),
    wordRange: (min: number, max: number) => `${min}–${max}`,
    targetWords: (count: number) => `${count} words`,
    versionLabel: (version: number) => `v${version}`,
    newTemplate: "New template",
    askAgent: "Ask the agent",
    detail: {
        sections: "Sections",
        models: "Models",
        recipe: "Recipe",
        noSections: "No sections yet",
        noModels: "Every role follows the model settings",
        siteChanges: "What this site changes",
    },
    blank: {
        firstHeading: "Introduction",
        firstIntent: "Say what the page is about and who it is for.",
    },
    create: {
        title: "New template",
        confirm: "Create it",
        cancel: "Cancel",
        startFrom: "Start from",
        startBlank: "A blank template",
        startBlankHint: "One introduction section, sensible length and link rules, no images. Every step but the image step is on.",
        startCopy: "A copy of",
        copyFrom: "Copy from",
        copyFromHint: "Every section, rule, model and step is copied. Nothing ties the two together afterwards.",
        nothingToCopy: "There is no template to copy yet.",
        name: "Name",
        pageKind: "Page kind",
        pageKindHint: "A short label such as hub, product or guide. It is how a page asks for this template.",
        scope: "Available to",
        scopeHint: "Either every site in this workspace, or this site alone.",
    },
    editor: {
        back: "All templates",
        save: "Save",
        saveNothing: "Nothing has changed on this layer.",
        revert: "Revert",
        unsaved: "Unsaved",
        deleteTemplate: "Delete",
        deleteTitle: "Delete this template?",
        deleteBody:
            "The template goes and its overrides go with it. Pages already generated from it are untouched.",
        deleteConfirm: "Delete",
        cancel: "Cancel",
        notFound: "This template no longer exists.",
        name: "Name",
        nameEdit: "Rename this template",
        pageKind: "Page kind",
        changeKind: "Rename it or change the page kind",
        changeKindTitle: "Name and page kind",
        changeKindBody: "Both belong to the template itself, so a change here reaches every site.",
        changeKindConfirm: "Apply",
        identityLocked: "The name and the page kind belong to the template. Switch to the template layer to change them.",
        openPage: "Preview page",
        openPageRefused: "Open this editor from a page to preview that page.",
        groups: {
            title: "Form groups",
            rules: "Rules",
            overrides: "Overrides",
        },
        skeleton: "Page skeleton",
        hideSkeleton: "Hide the page skeleton",
        showSkeleton: "Show the page skeleton",
        forPage: (path: string) => `for ${path}`,
        leaveTitle: "Leave without saving?",
        leaveBody: "What you changed on this layer has not been written yet.",
        leaveConfirm: "Leave it",
        leaveCancel: "Keep editing",
        conflict: {
            title: "Changed since you opened it",
            template: "The template was saved somewhere else while you were editing.",
            override: "This layer was saved somewhere else while you were editing.",
            reload: "Reload",
            overwrite: "Overwrite",
        },
    },
    preview: {
        tab: "Browser tab",
        description: (max: number) => `Meta description, up to ${max} characters`,
        h1: "H1",
        keyword: "primary keyword",
        featured: "Featured image",
        inline: "Inline image",
        words: (count: number) => `≈ ${count} words`,
        required: "required",
        optional: "optional",
        parentLink: (paragraphs: number) =>
            paragraphs === 1 ? "↑ parent link in the first paragraph" : `↑ parent link within the first ${paragraphs} paragraphs`,
        noParentLink: "no early parent link",
        children: "Links to the child pages",
        total: (count: number) => `≈ ${count} words in all`,
        range: (min: number, max: number) => `${min}–${max} allowed`,
        under: "The sections add up to less than the shortest page allowed.",
        over: "The sections add up to more than the longest page allowed.",
        unbounded: "no length limit",
        links: (count: number) => `up to ${count} links`,
        images: (count: number) => (count === 0 ? "no images" : count === 1 ? "1 image" : `${count} images`),
        noSections: "Add a section to see the page take shape.",
        untitled: "Untitled section",
    },
    layer: {
        label: "Editing",
        global: "The template",
        site: "This site",
        globalHint: "What you change here reaches every site that uses this template.",
        siteHint:
            "What you change here stays on this site. Everything you leave alone keeps following the template.",
        page: "This page",
        pageHint: "What you change here stays on this page alone. Everything you leave alone follows the site and the template.",
        fromGlobal: "From the template",
        fromSite: "Set by this site",
        fromPage: "Set by this page",
        follow: "Follow the template again",
        followSite: "Follow the site again",
        siteSays: (value: string) => `The site says ${value}.`,
        templateSays: (value: string) => `The template says ${value}.`,
        on: "on",
        off: "off",
        none: "nothing",
    },
    overrides: {
        columns: {
            field: "Field",
            below: "Underneath",
            here: "Here",
        },
        revert: "Revert",
        globalTitle: "The template is the starting point",
        globalBody: "Nothing overrides it here. Switch to a site or a page to see and change what they do.",
        siteTitle: "What this site changes",
        siteNone: "This site changes nothing. Every value comes from the template.",
        pageNone: "This page changes nothing. Every value comes from the site and the template.",
        clearSite: "Drop every change this site makes",
        clearSiteTitle: "Drop the changes this site makes?",
        clearSiteBody: "Every value goes back to what the template says. Pages keep their own changes.",
        clearConfirm: "Drop them",
        cancel: "Cancel",
        pagesTitle: "Pages that change it",
        pagesNone: "No page changes this template.",
        pageCount: (count: number) => (count === 1 ? "1 page" : `${count} pages`),
        clearPage: "Drop the changes this page makes",
        clearPageTitle: "Drop the changes this page makes?",
        clearPageBody: "The page goes back to what the template and this site say.",
        unknownPage: "a page that no longer exists",
        sections: "Sections",
        models: "Models",
        recipe: "Recipe",
    },
    sentence: {
        sections: (count: number, headings: string) =>
            count === 1 ? `writes one section, ${headings}` : `writes its own ${count} sections: ${headings}`,
        sectionsNone: "removes every section",
        tone: (tone: string) => `changes the tone to “${tone}”`,
        toneNone: "drops the tone instruction",
        shorter: (min: number, max: number) => `shortens the page to ${min}–${max} words`,
        longer: (min: number, max: number) => `lengthens the page to ${min}–${max} words`,
        length: (min: number, max: number) => `sets the page length to ${min}–${max} words`,
        lengthMin: (min: number) => `asks for at least ${min} words`,
        lengthMax: (max: number) => `caps the page at ${max} words`,
        primaryInTitle: (on: boolean) =>
            on ? "requires the primary keyword in the title" : "stops requiring the primary keyword in the title",
        primaryInH1: (on: boolean) =>
            on ? "requires the primary keyword in the H1" : "stops requiring the primary keyword in the H1",
        primaryInFirstParagraph: (on: boolean) =>
            on
                ? "requires the primary keyword in the first paragraph"
                : "stops requiring the primary keyword in the first paragraph",
        maxDensity: (percent: string) => `caps keyword density at ${percent}`,
        upDepth: (levels: number) =>
            levels === 0
                ? "stops linking up to parent pages"
                : levels === 1
                  ? "links up one level to the parent page"
                  : `links up ${levels} levels of parent pages`,
        downLinks: (on: boolean) => (on ? "links down to child pages" : "stops linking down to child pages"),
        siblingMinWeight: (weight: string) => `only links siblings scoring ${weight} or higher`,
        maxLinks: (links: number) => `allows at most ${links} internal links`,
        maxPerTarget: (links: number) =>
            links === 1 ? "allows one link to any single page" : `allows up to ${links} links to the same page`,
        parentLinkWithinParagraphs: (paragraphs: number) =>
            paragraphs === 0
                ? "stops insisting on an early parent link"
                : paragraphs === 1
                  ? "puts the parent link in the first paragraph"
                  : `puts the parent link inside the first ${paragraphs} paragraphs`,
        childrenSection: (on: boolean) =>
            on ? "adds a section listing the child pages" : "drops the section listing the child pages",
        titlePattern: (pattern: string) => `uses the title pattern “${pattern}”`,
        titlePatternNone: "drops the title pattern",
        descriptionMax: (characters: number) => `caps the meta description at ${characters} characters`,
        featured: (on: boolean) => (on ? "adds a featured image" : "drops the featured image"),
        inline: (images: number) =>
            images === 0
                ? "uses no inline images"
                : images === 1
                  ? "asks for one inline image"
                  : `asks for ${images} inline images`,
        imageSource: (source: string) => `takes images from ${source}`,
        profile: (role: string, provider: string, model: string) => `uses ${provider} ${model} for the ${role}`,
        profileNone: (role: string) => `lets the ${role} fall back to the site model`,
        stepsOff: (steps: string) => `skips ${steps}`,
        stepsOn: (steps: string) => `also runs ${steps}`,
        recipe: "changes which steps run",
        allowErrors: (on: boolean) =>
            on ? "lets a page through the checks with errors" : "stops a page at the checks when it has errors",
        repairIterations: (times: number) => (times === 1 ? "repairs the links once" : `repairs the links up to ${times} times`),
        other: (field: string) => `changes ${field}`,
    },
    sections: {
        title: "Sections",
        body: "A generated page is written section by section, in this order.",
        add: "Add a section",
        empty: "No sections yet",
        emptyBody: "A template needs at least one section before a run can use it.",
        heading: "Heading",
        intent: "What this section has to do",
        intentHint: "Written for the model, not for the reader.",
        targetWords: "Target words",
        required: "Required",
        requiredHint: "A required section is never dropped, however short the page is.",
        primaryInHeading: "Primary keyword in the heading",
        include: "Keywords this section must use",
        includeAdd: "Add",
        includePlaceholder: "ceramic mug",
        includeRemove: "Remove",
        includeEmpty: "No keyword is pinned to this section.",
        moveUp: "Move up",
        moveDown: "Move down",
        remove: "Remove this section",
        untitled: "Untitled section",
        position: (index: number, total: number) => `${index} of ${total}`,
    },
    content: {
        title: "Tone and length",
        tone: "Tone",
        toneHint: "One or two sentences the writer follows on every page.",
        lengthMin: "Shortest",
        lengthMax: "Longest",
        lengthHint: "Total words across every section.",
        keywords: "Primary keyword",
        keywordsBody: "Where the page has to carry the keyword it is written for.",
        primaryInTitle: "In the title",
        primaryInH1: "In the H1",
        primaryInFirstParagraph: "In the first paragraph",
        maxDensity: "Highest density",
        maxDensityHint: "As a share of all words. 0.025 is 2.5%.",
    },
    links: {
        title: "Link rules",
        body: "These decide which internal links a generated page carries and how many.",
        fromTemplate:
            "At run time these come from the template, not from the link policy. The policy decides only external links, self links and anchors.",
        upDepth: "Levels up",
        upDepthHint: "How far up the parent chain the page links.",
        downLinks: "Link down to children",
        siblingMinWeight: "Lowest sibling score",
        siblingMinWeightHint: "Between 0 and 1. A related entity below this is not linked.",
        maxLinks: "Most links on a page",
        maxPerTarget: "Most links to one page",
        parentLinkWithinParagraphs: "Parent link within",
        parentLinkWithinParagraphsHint: "Paragraphs from the top. 0 turns the rule off.",
        childrenSection: "Add a section listing the children",
    },
    meta: {
        title: "Meta",
        titlePattern: "Title pattern",
        titlePatternHint: "Placeholders such as {primaryKeyword} and {siteName} are filled in per page.",
        descriptionMax: "Longest description",
        descriptionMaxHint: "Characters. Google truncates around 155.",
        images: "Images",
        featured: "Featured image",
        inline: "Inline images",
        source: "Where images come from",
        sourceHint: "A source is required as soon as any image is asked for.",
        noSource: "Not chosen",
    },
    imageSource: {
        ai: "the image model",
        wpmedia: "the WordPress media library",
        local: "a local folder",
    },
    models: {
        title: "Models",
        body: "A role left out here falls back to the site profile, and then to the global one.",
        role: "Role",
        provider: "Provider",
        model: "Model",
        add: "Pin a role to a model",
        remove: (role: string) => `Unpin the ${role} role`,
        empty: "No role is pinned here",
        emptyBody:
            "Every role follows the model settings. Pin one only when this template needs a different model.",
        follows: "Follows the model settings",
        pickModel: "Pick a model",
        catalogEmpty: "The model catalog is empty, so there is nothing to pin a role to.",
        allPinned: "Every role is already pinned.",
    },
    recipe: {
        title: "Recipe",
        body: "The steps a run takes for one page, in the order the pipeline runs them.",
        order: "This order is the pipeline order and cannot be rearranged.",
        enabled: (on: number, total: number) => `${on} of ${total} steps on`,
        noneEnabled: "No step is on, so a run cannot start from this template.",
        unknown: "Not a step this build knows about. It is kept as it was written.",
        carriesParams: "Carries settings the agent wrote",
        params: {
            allowErrors: "Let the page through with errors",
            allowErrorsHint: "Off, a page with errors stops here and waits for a person.",
            iterations: "Repair attempts",
            iterationsHint: "How many times the links are repaired before the page moves on.",
        },
    },
    steps: {
        resolve_context: "Work out what this page may link to",
        generate_body: "Write the body",
        generate_meta: "Write the title and description",
        insert_links: "Insert the internal links",
        repair_links: "Repair the links the checks refused",
        generate_images: "Make the images",
        validate: "Check the page against the rules",
        judge: "Score the page",
        publish: "Publish it to WordPress",
        relink_neighbors: "Relink the neighbouring pages",
        sync_back: "Read the published page back",
        report: "Write the run report",
        sync_site: "Read the whole site",
    },
};

export const policies = {
    title: "Link policies",
    loading: "Loading link policies",
    columns: {
        name: "Name",
        scope: "Scope",
        inForce: "In force",
        forbids: "Forbids",
        anchor: "Anchor rule",
        maxLinks: "Max links",
    },
    inForce: "In force",
    useHere: "Use it on this site",
    alreadyInForce: "This policy is already the one in force on this site.",
    empty: "No link policy of your own yet",
    emptyBody: "Until you add one, the workspace default decides external links, self links and anchors.",
    effective: "In force on this site",
    effectiveFromSite: "Chosen on the site as its link policy.",
    effectiveFallback: "No policy is chosen on the site, so the workspace default applies.",
    effectiveMissing: "No link policy applies to this site.",
    forbidExternal: "Forbid links off the site",
    forbidSelf: "Forbid a page linking to itself",
    anchorStrategy: "Anchor text",
    anchorStrategyHint: "How the anchor for a link is chosen when an entity carries several.",
    anchor: {
        prefer_user: "Prefer the anchor you wrote",
        rotate: "Rotate through every anchor",
    },
    forbidsBoth: "Links off the site, self links",
    forbidsExternal: "Links off the site",
    forbidsSelf: "Self links",
    forbidsNone: "Nothing",
    newPolicy: "New policy",
    edit: "Edit",
    create: {
        title: "New link policy",
        body: "A new policy starts from the one in force on this site.",
        confirm: "Create it",
        editTitle: "Edit this link policy",
        editBody: "Saving changes it for every site that uses it.",
        actions: "Actions",
        save: "Save",
        cancel: "Cancel",
        name: "Name",
        scope: "Available to",
        scopeHint: "Either every site in this workspace, or this site alone.",
    },
    rulesTitle: "Link rules on this policy",
    rulesTooltip: "A template with its own link rules replaces these; one without them inherits them.",
    deleteTitle: "Delete this link policy?",
    deleteBody: "Sites that point at it fall back to the workspace default.",
    deleteConfirm: "Delete",
    delete: "Delete",
};
