import { copy } from "../../copy/index.js";
import { imageSources } from "../../generated/vocab.js";
import type { SelectOption } from "../../ui/index.js";
import { decimal, imageSourceLabel, percent } from "./labels.js";
import { paths } from "./patch.js";
import type { Rule, RuleBlock } from "./rules-model.js";
import { unsetSource } from "./rules-model.js";

const sourceOptions: readonly SelectOption<string>[] = [
    { value: unsetSource, label: copy.templates.meta.noSource },
    ...imageSources.map((value) => ({ value, label: imageSourceLabel(value) })),
];

export const ruleBlocks: readonly RuleBlock[] = [
    {
        key: "content",
        title: copy.templates.content.title,
        rules: [
            {
                kind: "text",
                key: "tone",
                label: copy.templates.content.tone,
                hint: copy.templates.content.toneHint,
                field: "tone",
                path: paths.tone,
                read: (draft) => draft.tone,
                write: (tone) => ({ tone }),
            },
            {
                kind: "number",
                key: "lengthMin",
                label: copy.templates.content.lengthMin,
                hint: copy.templates.content.lengthHint,
                field: "length.min",
                path: paths.lengthMin,
                min: 0,
                read: (draft) => draft.lengthMin,
                write: (lengthMin) => ({ lengthMin }),
            },
            {
                kind: "number",
                key: "lengthMax",
                label: copy.templates.content.lengthMax,
                hint: copy.templates.content.lengthHint,
                field: "length.max",
                path: paths.lengthMax,
                min: 0,
                read: (draft) => draft.lengthMax,
                write: (lengthMax) => ({ lengthMax }),
            },
        ],
    },
    {
        key: "keywords",
        title: copy.templates.content.keywords,
        rules: [
            {
                kind: "switch",
                key: "primaryInTitle",
                label: copy.templates.content.primaryInTitle,
                field: "keywordRules.primaryInTitle",
                path: paths.primaryInTitle,
                read: (draft) => draft.primaryInTitle,
                write: (primaryInTitle) => ({ primaryInTitle }),
            },
            {
                kind: "switch",
                key: "primaryInH1",
                label: copy.templates.content.primaryInH1,
                field: "keywordRules.primaryInH1",
                path: paths.primaryInH1,
                read: (draft) => draft.primaryInH1,
                write: (primaryInH1) => ({ primaryInH1 }),
            },
            {
                kind: "switch",
                key: "primaryInFirstParagraph",
                label: copy.templates.content.primaryInFirstParagraph,
                field: "keywordRules.primaryInFirstParagraph",
                path: paths.primaryInFirstParagraph,
                read: (draft) => draft.primaryInFirstParagraph,
                write: (primaryInFirstParagraph) => ({ primaryInFirstParagraph }),
            },
            {
                kind: "number",
                key: "maxDensity",
                label: copy.templates.content.maxDensity,
                hint: copy.templates.content.maxDensityHint,
                field: "keywordRules.maxDensity",
                path: paths.maxDensity,
                min: 0,
                max: 1,
                step: 0.005,
                read: (draft) => draft.maxDensity,
                write: (maxDensity) => ({ maxDensity }),
                show: (draft) => percent(draft.maxDensity),
            },
        ],
    },
    {
        key: "links",
        title: copy.templates.links.title,
        rules: [
            {
                kind: "number",
                key: "upDepth",
                label: copy.templates.links.upDepth,
                hint: copy.templates.links.upDepthHint,
                field: "linkRules.upDepth",
                path: paths.upDepth,
                min: 0,
                read: (draft) => draft.upDepth,
                write: (upDepth) => ({ upDepth }),
            },
            {
                kind: "switch",
                key: "downLinks",
                label: copy.templates.links.downLinks,
                field: "linkRules.downLinks",
                path: paths.downLinks,
                read: (draft) => draft.downLinks,
                write: (downLinks) => ({ downLinks }),
            },
            {
                kind: "number",
                key: "siblingMinWeight",
                label: copy.templates.links.siblingMinWeight,
                hint: copy.templates.links.siblingMinWeightHint,
                field: "linkRules.siblingMinWeight",
                path: paths.siblingMinWeight,
                min: 0,
                max: 1,
                step: 0.05,
                read: (draft) => draft.siblingMinWeight,
                write: (siblingMinWeight) => ({ siblingMinWeight }),
                show: (draft) => decimal(draft.siblingMinWeight),
            },
            {
                kind: "number",
                key: "maxLinks",
                label: copy.templates.links.maxLinks,
                field: "linkRules.maxLinks",
                path: paths.maxLinks,
                min: 0,
                read: (draft) => draft.maxLinks,
                write: (maxLinks) => ({ maxLinks }),
            },
            {
                kind: "number",
                key: "maxPerTarget",
                label: copy.templates.links.maxPerTarget,
                field: "linkRules.maxPerTarget",
                path: paths.maxPerTarget,
                min: 0,
                read: (draft) => draft.maxPerTarget,
                write: (maxPerTarget) => ({ maxPerTarget }),
            },
            {
                kind: "number",
                key: "parentLinkWithinParagraphs",
                label: copy.templates.links.parentLinkWithinParagraphs,
                hint: copy.templates.links.parentLinkWithinParagraphsHint,
                field: "linkRules.parentLinkWithinParagraphs",
                path: paths.parentLinkWithinParagraphs,
                min: 0,
                read: (draft) => draft.parentLinkWithinParagraphs,
                write: (parentLinkWithinParagraphs) => ({ parentLinkWithinParagraphs }),
            },
            {
                kind: "switch",
                key: "childrenSection",
                label: copy.templates.links.childrenSection,
                field: "linkRules.childrenSection",
                path: paths.childrenSection,
                read: (draft) => draft.childrenSection,
                write: (childrenSection) => ({ childrenSection }),
            },
        ],
    },
    {
        key: "meta",
        title: copy.templates.meta.title,
        rules: [
            {
                kind: "text",
                key: "titlePattern",
                label: copy.templates.meta.titlePattern,
                hint: copy.templates.meta.titlePatternHint,
                field: "metaRules.titlePattern",
                path: paths.titlePattern,
                mono: true,
                read: (draft) => draft.titlePattern,
                write: (titlePattern) => ({ titlePattern }),
            },
            {
                kind: "number",
                key: "descriptionMax",
                label: copy.templates.meta.descriptionMax,
                hint: copy.templates.meta.descriptionMaxHint,
                field: "metaRules.descriptionMax",
                path: paths.descriptionMax,
                min: 0,
                read: (draft) => draft.descriptionMax,
                write: (descriptionMax) => ({ descriptionMax }),
            },
        ],
    },
    {
        key: "images",
        title: copy.templates.meta.images,
        rules: [
            {
                kind: "switch",
                key: "featuredImage",
                label: copy.templates.meta.featured,
                field: "images.featured",
                path: paths.featuredImage,
                read: (draft) => draft.featuredImage,
                write: (featuredImage) => ({ featuredImage }),
            },
            {
                kind: "number",
                key: "inlineImages",
                label: copy.templates.meta.inline,
                field: "images.inline",
                path: paths.inlineImages,
                min: 0,
                read: (draft) => draft.inlineImages,
                write: (inlineImages) => ({ inlineImages }),
            },
            {
                kind: "select",
                key: "imageSource",
                label: copy.templates.meta.source,
                hint: copy.templates.meta.sourceHint,
                field: "images.source",
                path: paths.imageSource,
                options: sourceOptions,
                read: (draft) => (draft.imageSource === "" ? unsetSource : draft.imageSource),
                write: (value) => ({ imageSource: value === unsetSource ? "" : value }),
                show: (draft) => imageSourceLabel(draft.imageSource),
            },
        ],
    },
];

export const allRules: readonly Rule[] = ruleBlocks.flatMap((block) => block.rules);

