// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIProviderService() {
  return window['go']['app']['App']['AIProviderService']();
}

export function AssignTopicToSite(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AssignTopicToSite'](arg1, arg2, arg3, arg4);
}

export function BuildServices() {
  return window['go']['app']['App']['BuildServices']();
}

export function CheckHealth(arg1) {
  return window['go']['app']['App']['CheckHealth'](arg1);
}

export function CountUnusedTopics(arg1) {
  return window['go']['app']['App']['CountUnusedTopics'](arg1);
}

export function CreateAIProvider(arg1) {
  return window['go']['app']['App']['CreateAIProvider'](arg1);
}

export function CreateJob(arg1) {
  return window['go']['app']['App']['CreateJob'](arg1);
}

export function CreatePrompt(arg1) {
  return window['go']['app']['App']['CreatePrompt'](arg1);
}

export function CreateSite(arg1) {
  return window['go']['app']['App']['CreateSite'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['app']['App']['CreateTopic'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['app']['App']['DeleteAIProvider'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['app']['App']['DeleteJob'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['app']['App']['DeletePrompt'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['app']['App']['DeleteSite'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['app']['App']['DeleteTopic'](arg1);
}

export function ExecuteJobManually(arg1) {
  return window['go']['app']['App']['ExecuteJobManually'](arg1);
}

export function GetAIModels() {
  return window['go']['app']['App']['GetAIModels']();
}

export function GetAIProvider(arg1) {
  return window['go']['app']['App']['GetAIProvider'](arg1);
}

export function GetAvailableModels(arg1) {
  return window['go']['app']['App']['GetAvailableModels'](arg1);
}

export function GetAvailableTopic(arg1, arg2) {
  return window['go']['app']['App']['GetAvailableTopic'](arg1, arg2);
}

export function GetJob(arg1) {
  return window['go']['app']['App']['GetJob'](arg1);
}

export function GetPendingValidations() {
  return window['go']['app']['App']['GetPendingValidations']();
}

export function GetPrompt(arg1) {
  return window['go']['app']['App']['GetPrompt'](arg1);
}

export function GetSite(arg1) {
  return window['go']['app']['App']['GetSite'](arg1);
}

export function GetSiteCategories(arg1) {
  return window['go']['app']['App']['GetSiteCategories'](arg1);
}

export function GetSiteTopics(arg1) {
  return window['go']['app']['App']['GetSiteTopics'](arg1);
}

export function GetTopic(arg1) {
  return window['go']['app']['App']['GetTopic'](arg1);
}

export function GetTopicsBySite(arg1) {
  return window['go']['app']['App']['GetTopicsBySite'](arg1);
}

export function ImportAndAssignToSite(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportAndAssignToSite'](arg1, arg2, arg3, arg4);
}

export function ImportTopics(arg1) {
  return window['go']['app']['App']['ImportTopics'](arg1);
}

export function InitAI(arg1) {
  return window['go']['app']['App']['InitAI'](arg1);
}

export function InitDB(arg1) {
  return window['go']['app']['App']['InitDB'](arg1);
}

export function InitWP() {
  return window['go']['app']['App']['InitWP']();
}

export function JobService() {
  return window['go']['app']['App']['JobService']();
}

export function ListAIProviders() {
  return window['go']['app']['App']['ListAIProviders']();
}

export function ListActiveAIProviders() {
  return window['go']['app']['App']['ListActiveAIProviders']();
}

export function ListJobs() {
  return window['go']['app']['App']['ListJobs']();
}

export function ListPrompts() {
  return window['go']['app']['App']['ListPrompts']();
}

export function ListSites() {
  return window['go']['app']['App']['ListSites']();
}

export function ListTopics() {
  return window['go']['app']['App']['ListTopics']();
}

export function MarkTopicAsUsed(arg1, arg2) {
  return window['go']['app']['App']['MarkTopicAsUsed'](arg1, arg2);
}

export function PauseJob(arg1) {
  return window['go']['app']['App']['PauseJob'](arg1);
}

export function PromptService() {
  return window['go']['app']['App']['PromptService']();
}

export function RenderPrompt(arg1, arg2) {
  return window['go']['app']['App']['RenderPrompt'](arg1, arg2);
}

export function RestoreScheduler() {
  return window['go']['app']['App']['RestoreScheduler']();
}

export function RestoreState(arg1) {
  return window['go']['app']['App']['RestoreState'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['app']['App']['ResumeJob'](arg1);
}

export function SetAIProviderStatus(arg1, arg2) {
  return window['go']['app']['App']['SetAIProviderStatus'](arg1, arg2);
}

export function SiteService() {
  return window['go']['app']['App']['SiteService']();
}

export function Start(arg1) {
  return window['go']['app']['App']['Start'](arg1);
}

export function StartApp(arg1) {
  return window['go']['app']['App']['StartApp'](arg1);
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}

export function StopApp() {
  return window['go']['app']['App']['StopApp']();
}

export function SyncCategories(arg1) {
  return window['go']['app']['App']['SyncCategories'](arg1);
}

export function TopicService() {
  return window['go']['app']['App']['TopicService']();
}

export function UnassignTopicFromSite(arg1, arg2) {
  return window['go']['app']['App']['UnassignTopicFromSite'](arg1, arg2);
}

export function UpdateAIProvider(arg1) {
  return window['go']['app']['App']['UpdateAIProvider'](arg1);
}

export function UpdateJob(arg1) {
  return window['go']['app']['App']['UpdateJob'](arg1);
}

export function UpdatePrompt(arg1) {
  return window['go']['app']['App']['UpdatePrompt'](arg1);
}

export function UpdateSite(arg1) {
  return window['go']['app']['App']['UpdateSite'](arg1);
}

export function UpdateTopic(arg1) {
  return window['go']['app']['App']['UpdateTopic'](arg1);
}

export function ValidateExecution(arg1, arg2) {
  return window['go']['app']['App']['ValidateExecution'](arg1, arg2);
}

export function ValidateModel(arg1, arg2) {
  return window['go']['app']['App']['ValidateModel'](arg1, arg2);
}
