// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function AssignTopicToSite(arg1:number,arg2:number,arg3:number,arg4:string):Promise<dto.Response_string_>;

export function BuildServices():Promise<void>;

export function CheckHealth(arg1:number):Promise<dto.Response_string_>;

export function CountUnusedTopics(arg1:number):Promise<dto.Response_int_>;

export function CreateAIProvider(arg1:dto.AIProviderCreate):Promise<dto.Response_string_>;

export function CreateJob(arg1:dto.Job):Promise<dto.Response_string_>;

export function CreatePrompt(arg1:dto.Prompt):Promise<dto.Response_string_>;

export function CreateSite(arg1:dto.Site):Promise<dto.Response_string_>;

export function CreateTopic(arg1:dto.Topic):Promise<dto.Response_string_>;

export function DeleteAIProvider(arg1:number):Promise<dto.Response_string_>;

export function DeleteJob(arg1:number):Promise<dto.Response_string_>;

export function DeletePrompt(arg1:number):Promise<dto.Response_string_>;

export function DeleteSite(arg1:number):Promise<dto.Response_string_>;

export function DeleteTopic(arg1:number):Promise<dto.Response_string_>;

export function ExecuteJobManually(arg1:number):Promise<dto.Response_string_>;

export function GetAIModels():Promise<dto.Response_Postulator_internal_dto_ModelsByProvider_>;

export function GetAIProvider(arg1:number):Promise<dto.Response_Postulator_internal_dto_AIProvider_>;

export function GetAvailableModels(arg1:string):Promise<dto.Response___string_>;

export function GetAvailableTopic(arg1:number,arg2:string):Promise<dto.Response_Postulator_internal_dto_Topic_>;

export function GetJob(arg1:number):Promise<dto.Response_Postulator_internal_dto_Job_>;

export function GetPendingValidations():Promise<dto.Response___Postulator_internal_dto_Execution_>;

export function GetPrompt(arg1:number):Promise<dto.Response_Postulator_internal_dto_Prompt_>;

export function GetSite(arg1:number):Promise<dto.Response_Postulator_internal_dto_Site_>;

export function GetSiteCategories(arg1:number):Promise<dto.Response___Postulator_internal_dto_Category_>;

export function GetSiteTopics(arg1:number):Promise<dto.Response___Postulator_internal_dto_SiteTopic_>;

export function GetTopic(arg1:number):Promise<dto.Response_Postulator_internal_dto_Topic_>;

export function GetTopicsBySite(arg1:number):Promise<dto.Response___Postulator_internal_dto_Topic_>;

export function ImportAndAssignToSite(arg1:string,arg2:number,arg3:number,arg4:string):Promise<dto.Response_Postulator_internal_dto_ImportResult_>;

export function ImportTopics(arg1:string):Promise<dto.Response_Postulator_internal_dto_ImportResult_>;

export function InitAI():Promise<void>;

export function InitDB():Promise<void>;

export function InitWP():Promise<void>;

export function ListAIProviders():Promise<dto.Response___Postulator_internal_dto_AIProvider_>;

export function ListActiveAIProviders():Promise<dto.Response___Postulator_internal_dto_AIProvider_>;

export function ListJobs():Promise<dto.Response___Postulator_internal_dto_Job_>;

export function ListPrompts():Promise<dto.Response___Postulator_internal_dto_Prompt_>;

export function ListSites():Promise<dto.Response___Postulator_internal_dto_Site_>;

export function ListTopics(arg1:number,arg2:number):Promise<dto.PaginatedResponse_Postulator_internal_dto_Topic_>;

export function MarkTopicAsUsed(arg1:number,arg2:number):Promise<dto.Response_string_>;

export function PauseJob(arg1:number):Promise<dto.Response_string_>;

export function RenderPrompt(arg1:number,arg2:Record<string, string>):Promise<dto.Response_Postulator_internal_dto_PromptRenderResult_>;

export function RestoreScheduler():Promise<dto.Response_string_>;

export function RestoreState(arg1:context.Context):Promise<void>;

export function ResumeJob(arg1:number):Promise<dto.Response_string_>;

export function SetAIProviderStatus(arg1:number,arg2:boolean):Promise<dto.Response_string_>;

export function SetSitePassword(arg1:number,arg2:string):Promise<dto.Response_string_>;

export function Start(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function SyncCategories(arg1:number):Promise<dto.Response_string_>;

export function UnassignTopicFromSite(arg1:number,arg2:number):Promise<dto.Response_string_>;

export function UpdateAIProvider(arg1:dto.AIProviderUpdate):Promise<dto.Response_string_>;

export function UpdateJob(arg1:dto.Job):Promise<dto.Response_string_>;

export function UpdatePrompt(arg1:dto.Prompt):Promise<dto.Response_string_>;

export function UpdateSite(arg1:dto.Site):Promise<dto.Response_string_>;

export function UpdateTopic(arg1:dto.Topic):Promise<dto.Response_string_>;

export function ValidateExecution(arg1:number,arg2:boolean):Promise<dto.Response_string_>;

export function ValidateModel(arg1:string,arg2:string):Promise<dto.Response_string_>;
