"use client";

import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import { Button } from "@/components/ui/button";
import {
    Tooltip,
    TooltipContent,
    TooltipTrigger,
} from "@/components/ui/tooltip";
import { Palette } from "lucide-react";

interface ColorLegendItem {
    color: string;
    label: string;
    description: string;
}

const legendItems: ColorLegendItem[] = [
    {
        color: "bg-primary",
        label: "Root",
        description: "Homepage / Root node",
    },
    {
        color: "bg-green-500",
        label: "Published",
        description: "Content is live on WordPress",
    },
    {
        color: "bg-yellow-500",
        label: "WP Draft",
        description: "Saved as draft in WordPress",
    },
    {
        color: "bg-blue-500",
        label: "WP Pending",
        description: "Pending review in WordPress",
    },
    {
        color: "bg-cyan-500",
        label: "Publishing",
        description: "Currently being published to WP",
    },
    {
        color: "bg-purple-500",
        label: "Generated",
        description: "Content generated by AI, not published",
    },
    {
        color: "bg-purple-400",
        label: "Generating",
        description: "AI is generating content",
    },
    {
        color: "bg-slate-400",
        label: "Queued",
        description: "Waiting in generation queue",
    },
    {
        color: "bg-red-500",
        label: "Failed",
        description: "Generation or publishing failed",
    },
    {
        color: "bg-orange-500",
        label: "Modified",
        description: "Local changes not synced to WordPress",
    },
    {
        color: "bg-muted-foreground/30",
        label: "None",
        description: "No content linked",
    },
];

export function ColorLegendPopover() {
    return (
        <Popover>
            <Tooltip>
                <TooltipTrigger asChild>
                    <PopoverTrigger asChild>
                        <Button variant="outline" size="icon" className="h-7 w-7">
                            <Palette className="h-4 w-4" />
                        </Button>
                    </PopoverTrigger>
                </TooltipTrigger>
                <TooltipContent>
                    <p>Node Status Colors</p>
                </TooltipContent>
            </Tooltip>
            <PopoverContent className="w-64" align="end">
                <div className="space-y-3">
                    <div className="font-medium text-sm">Node Status Colors</div>
                    <div className="space-y-2">
                        {legendItems.map((item) => (
                            <div key={item.label} className="flex items-center gap-2">
                                <div
                                    className={`w-3 h-6 rounded-sm ${item.color}`}
                                />
                                <div className="flex-1 min-w-0">
                                    <div className="text-sm font-medium">{item.label}</div>
                                    <div className="text-xs text-muted-foreground truncate">
                                        {item.description}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </PopoverContent>
        </Popover>
    );
}
