// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateSite(arg1) {
  return window['go']['bindings']['Binder']['ActivateSite'](arg1);
}

export function ActivateSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['ActivateSitePrompt'](arg1);
}

export function ActivateSiteTopic(arg1) {
  return window['go']['bindings']['Binder']['ActivateSiteTopic'](arg1);
}

export function ActivateTopic(arg1) {
  return window['go']['bindings']['Binder']['ActivateTopic'](arg1);
}

export function CheckStrategyAvailability(arg1, arg2) {
  return window['go']['bindings']['Binder']['CheckStrategyAvailability'](arg1, arg2);
}

export function CreatePrompt(arg1) {
  return window['go']['bindings']['Binder']['CreatePrompt'](arg1);
}

export function CreateSite(arg1) {
  return window['go']['bindings']['Binder']['CreateSite'](arg1);
}

export function CreateSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['CreateSitePrompt'](arg1);
}

export function CreateSiteTopic(arg1) {
  return window['go']['bindings']['Binder']['CreateSiteTopic'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['bindings']['Binder']['CreateTopic'](arg1);
}

export function DeactivateSite(arg1) {
  return window['go']['bindings']['Binder']['DeactivateSite'](arg1);
}

export function DeactivateSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['DeactivateSitePrompt'](arg1);
}

export function DeactivateSiteTopic(arg1) {
  return window['go']['bindings']['Binder']['DeactivateSiteTopic'](arg1);
}

export function DeactivateTopic(arg1) {
  return window['go']['bindings']['Binder']['DeactivateTopic'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['bindings']['Binder']['DeletePrompt'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['bindings']['Binder']['DeleteSite'](arg1);
}

export function DeleteSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['DeleteSitePrompt'](arg1);
}

export function DeleteSitePromptBySite(arg1) {
  return window['go']['bindings']['Binder']['DeleteSitePromptBySite'](arg1);
}

export function DeleteSiteTopic(arg1) {
  return window['go']['bindings']['Binder']['DeleteSiteTopic'](arg1);
}

export function DeleteSiteTopicBySiteAndTopic(arg1, arg2) {
  return window['go']['bindings']['Binder']['DeleteSiteTopicBySiteAndTopic'](arg1, arg2);
}

export function DeleteTopic(arg1) {
  return window['go']['bindings']['Binder']['DeleteTopic'](arg1);
}

export function GetActiveTopics() {
  return window['go']['bindings']['Binder']['GetActiveTopics']();
}

export function GetDefaultPrompt() {
  return window['go']['bindings']['Binder']['GetDefaultPrompt']();
}

export function GetPrompt(arg1) {
  return window['go']['bindings']['Binder']['GetPrompt'](arg1);
}

export function GetPromptSites(arg1, arg2) {
  return window['go']['bindings']['Binder']['GetPromptSites'](arg1, arg2);
}

export function GetPrompts(arg1) {
  return window['go']['bindings']['Binder']['GetPrompts'](arg1);
}

export function GetSite(arg1) {
  return window['go']['bindings']['Binder']['GetSite'](arg1);
}

export function GetSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['GetSitePrompt'](arg1);
}

export function GetSiteTopics(arg1, arg2) {
  return window['go']['bindings']['Binder']['GetSiteTopics'](arg1, arg2);
}

export function GetSiteUsageHistory(arg1, arg2) {
  return window['go']['bindings']['Binder']['GetSiteUsageHistory'](arg1, arg2);
}

export function GetSites(arg1) {
  return window['go']['bindings']['Binder']['GetSites'](arg1);
}

export function GetTopic(arg1) {
  return window['go']['bindings']['Binder']['GetTopic'](arg1);
}

export function GetTopicSites(arg1, arg2) {
  return window['go']['bindings']['Binder']['GetTopicSites'](arg1, arg2);
}

export function GetTopicStats(arg1) {
  return window['go']['bindings']['Binder']['GetTopicStats'](arg1);
}

export function GetTopicUsageHistory(arg1, arg2, arg3) {
  return window['go']['bindings']['Binder']['GetTopicUsageHistory'](arg1, arg2, arg3);
}

export function GetTopics(arg1) {
  return window['go']['bindings']['Binder']['GetTopics'](arg1);
}

export function GetTopicsBySiteID(arg1, arg2) {
  return window['go']['bindings']['Binder']['GetTopicsBySiteID'](arg1, arg2);
}

export function SelectTopicForSite(arg1) {
  return window['go']['bindings']['Binder']['SelectTopicForSite'](arg1);
}

export function SetDefaultPrompt(arg1) {
  return window['go']['bindings']['Binder']['SetDefaultPrompt'](arg1);
}

export function SetHandler(arg1) {
  return window['go']['bindings']['Binder']['SetHandler'](arg1);
}

export function SetSiteCheckStatus(arg1, arg2) {
  return window['go']['bindings']['Binder']['SetSiteCheckStatus'](arg1, arg2);
}

export function TestSiteConnection(arg1) {
  return window['go']['bindings']['Binder']['TestSiteConnection'](arg1);
}

export function UpdatePrompt(arg1) {
  return window['go']['bindings']['Binder']['UpdatePrompt'](arg1);
}

export function UpdateSite(arg1) {
  return window['go']['bindings']['Binder']['UpdateSite'](arg1);
}

export function UpdateSitePrompt(arg1) {
  return window['go']['bindings']['Binder']['UpdateSitePrompt'](arg1);
}

export function UpdateSiteTopic(arg1) {
  return window['go']['bindings']['Binder']['UpdateSiteTopic'](arg1);
}

export function UpdateTopic(arg1) {
  return window['go']['bindings']['Binder']['UpdateTopic'](arg1);
}
