// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {handlers} from '../models';

export function ActivateSite(arg1:number):Promise<void>;

export function CheckStrategyAvailability(arg1:number,arg2:string):Promise<dto.StrategyAvailabilityResponse>;

export function CreatePrompt(arg1:dto.CreatePromptRequest):Promise<dto.PromptResponse>;

export function CreateSite(arg1:dto.CreateSiteRequest):Promise<dto.SiteResponse>;

export function CreateSitePrompt(arg1:dto.CreateSitePromptRequest):Promise<dto.SitePromptResponse>;

export function CreateSiteTopic(arg1:dto.CreateSiteTopicRequest):Promise<dto.SiteTopicResponse>;

export function CreateTopic(arg1:dto.CreateTopicRequest):Promise<dto.TopicResponse>;

export function DeactivateSite(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteSite(arg1:number):Promise<void>;

export function DeleteSitePrompt(arg1:number):Promise<void>;

export function DeleteSitePromptBySite(arg1:number):Promise<void>;

export function DeleteSiteTopic(arg1:number):Promise<void>;

export function DeleteSiteTopicBySiteAndTopic(arg1:number,arg2:number):Promise<void>;

export function DeleteTopic(arg1:number):Promise<void>;

export function GetDefaultPrompt():Promise<dto.PromptResponse>;

export function GetPrompt(arg1:number):Promise<dto.PromptResponse>;

export function GetPromptSites(arg1:number,arg2:dto.PaginationRequest):Promise<dto.SitePromptListResponse>;

export function GetPrompts(arg1:dto.PaginationRequest):Promise<dto.PromptListResponse>;

export function GetSite(arg1:number):Promise<dto.SiteResponse>;

export function GetSitePrompt(arg1:number):Promise<dto.SitePromptResponse>;

export function GetSiteTopics(arg1:number,arg2:dto.PaginationRequest):Promise<dto.SiteTopicListResponse>;

export function GetSiteUsageHistory(arg1:number,arg2:dto.PaginationRequest):Promise<dto.TopicUsageListResponse>;

export function GetSites(arg1:dto.PaginationRequest):Promise<dto.SiteListResponse>;

export function GetTopic(arg1:number):Promise<dto.TopicResponse>;

export function GetTopicSites(arg1:number,arg2:dto.PaginationRequest):Promise<dto.SiteTopicListResponse>;

export function GetTopicStats(arg1:number):Promise<dto.TopicStatsResponse>;

export function GetTopicUsageHistory(arg1:number,arg2:number,arg3:dto.PaginationRequest):Promise<dto.TopicUsageListResponse>;

export function GetTopics(arg1:dto.PaginationRequest):Promise<dto.TopicListResponse>;

export function GetTopicsBySiteID(arg1:number,arg2:dto.PaginationRequest):Promise<dto.TopicListResponse>;

export function SelectTopicForSite(arg1:dto.TopicSelectionRequest):Promise<dto.TopicSelectionResponse>;

export function SetDefaultPrompt(arg1:dto.SetDefaultPromptRequest):Promise<void>;

export function SetHandler(arg1:handlers.Handler):Promise<void>;

export function SetSiteCheckStatus(arg1:number,arg2:string):Promise<void>;

export function TestSiteConnection(arg1:dto.TestSiteConnectionRequest):Promise<dto.TestConnectionResponse>;

export function TopicsImport(arg1:number,arg2:dto.TopicsImportRequest):Promise<any>;

export function TopicsReassign(arg1:dto.TopicsReassignRequest):Promise<dto.ReassignResult>;

export function UpdatePrompt(arg1:dto.UpdatePromptRequest):Promise<dto.PromptResponse>;

export function UpdateSite(arg1:dto.UpdateSiteRequest):Promise<dto.SiteResponse>;

export function UpdateSitePrompt(arg1:dto.UpdateSitePromptRequest):Promise<dto.SitePromptResponse>;

export function UpdateSiteTopic(arg1:dto.UpdateSiteTopicRequest):Promise<dto.SiteTopicResponse>;

export function UpdateTopic(arg1:dto.UpdateTopicRequest):Promise<dto.TopicResponse>;
